// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum CNmGraphDocIDEventConditionNode__SearchRule_t : byte
{
    SearchAll = 0,
    OnlySearchGraphEvents = 1,
    OnlySearchAnimEvents = 2,
}
