// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum EBasePredictionEvents : uint
{
    BPE_StringCommand = 128,
    BPE_Teleport = 130,
    BPE_Diagnostic = 16384,
}
