// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum FinishedConditionOption : uint
{
    FinishedConditionOption_OnFinished = 0,
    FinishedConditionOption_OnAlmostFinished = 1,
}
