// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum GCClientLauncherType : uint
{
    GCClientLauncherType_DEFAULT = 0,
    GCClientLauncherType_PERFECTWORLD = 1,
    GCClientLauncherType_STEAMCHINA = 2,
    GCClientLauncherType_SOURCE2 = 3,
}
