// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum GraphCanvasRenderLayer_t : uint
{
    INVALID = uint.MaxValue,
    COMMENTS = 0,
    CONNECTIONS_BACKGROUND = 1,
    GROUP_BACKGROUND = 2,
    DEFAULT = 3,
    NODES = 4,
    CONNECTIONS_FOREGROUND = 5,
    COMMENT_OVERLAY = 6,
    SELECTION_OVERLAY = 7,
    HOVER_OVERLAY = 8,
    STANDARD_LAYER_COUNT = 9,
    SPECIAL_DEBUGGER_OVERLAY = 10,
    SPECIAL_LAYER_HOVER_TOOLTIP = 11,
}
