// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum GraphCanvasPositioning_t : uint
{
    AUTO = 0,
    INSIDE_PARENT = 1,
    OUTSIDE_PARENT = 2,
    ON_PARENT_BORDER = 3,
}
