// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum ImportExportOptionsEditableData_t__ExportEncoding_t : uint
{
    EXPORT_ENCODING_TEXT = 0,
    EXPORT_ENCODING_BINARY = 1,
}
