// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum LayerMaskType_t : uint
{
    LAYER_MASK_LUMINOSITY = 0,
    LAYER_MASK_COLOR_RANGE = 1,
}
