// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum MirrorSpace_t : uint
{
    MIRROR_SPACE_BONE_RELATIVE = 0,
    MIRROR_SPACE_MODEL_RELATIVE = 1,
}
