// <auto-generated />

using SwiftlyS2.Shared.Schemas;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public enum SolveIKChainAnimNodeSettingSource : uint
{
    SOLVEIKCHAINANIMNODESETTINGSOURCE_Default = 0,
    SOLVEIKCHAINANIMNODESETTINGSOURCE_Override = 1,
}
