// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface AI_FacingServices_DebugSnapshotData_t : ISchemaClass<AI_FacingServices_DebugSnapshotData_t>
{
    static AI_FacingServices_DebugSnapshotData_t ISchemaClass<AI_FacingServices_DebugSnapshotData_t>.From(nint handle) => new AI_FacingServices_DebugSnapshotData_tImpl(handle);
    static int ISchemaClass<AI_FacingServices_DebugSnapshotData_t>.Size => 72;
    static string? ISchemaClass<AI_FacingServices_DebugSnapshotData_t>.ClassName => null;


    public ref Vector Npc_position { get; }

    public ref CGlobalSymbol Facing_target_source { get; }

    public ref Vector Facing_target { get; }

    public ref CGlobalSymbol Schedule_facing_priority { get; }

    public ref CGlobalSymbol Strafing_source { get; }

    public ref bool Strafing_enabled { get; }

    public ref CGlobalSymbol Movement_id { get; }


}