// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_CSGO_MapPreviewCameraPath : C_BaseEntity, ISchemaClass<C_CSGO_MapPreviewCameraPath>
{
    static C_CSGO_MapPreviewCameraPath ISchemaClass<C_CSGO_MapPreviewCameraPath>.From(nint handle) => new C_CSGO_MapPreviewCameraPathImpl(handle);
    static int ISchemaClass<C_CSGO_MapPreviewCameraPath>.Size => 1672;
    static string? ISchemaClass<C_CSGO_MapPreviewCameraPath>.ClassName => null;


    public ref float ZFar { get; }

    public ref float ZNear { get; }

    public ref bool Loop { get; }

    public ref bool VerticalFOV { get; }

    public ref bool ConstantSpeed { get; }

    public ref float Duration { get; }

    public ref float PathLength { get; }

    public ref float PathDuration { get; }

    public ref bool DofEnabled { get; }

    public ref float DofNearBlurry { get; }

    public ref float DofNearCrisp { get; }

    public ref float DofFarCrisp { get; }

    public ref float DofFarBlurry { get; }

    public ref float DofTiltToGround { get; }


}