// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_CsmFovOverride : C_BaseEntity, ISchemaClass<C_CsmFovOverride>
{
    static C_CsmFovOverride ISchemaClass<C_CsmFovOverride>.From(nint handle) => new C_CsmFovOverrideImpl(handle);
    static int ISchemaClass<C_CsmFovOverride>.Size => 1552;
    static string? ISchemaClass<C_CsmFovOverride>.ClassName => null;


    public string CameraName { get; set; }

    public ref float CsmFovOverrideValue { get; }


}