// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_CsmFovOverride_API : ISchemaClass<C_CsmFovOverride_API>
{
    static C_CsmFovOverride_API ISchemaClass<C_CsmFovOverride_API>.From(nint handle) => new C_CsmFovOverride_APIImpl(handle);
    static int ISchemaClass<C_CsmFovOverride_API>.Size => 8;
    static string? ISchemaClass<C_CsmFovOverride_API>.ClassName => null;

}