// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_CSGO_MapPreviewCameraPathNode_API : ISchemaClass<C_CSGO_MapPreviewCameraPathNode_API>
{
    static C_CSGO_MapPreviewCameraPathNode_API ISchemaClass<C_CSGO_MapPreviewCameraPathNode_API>.From(nint handle) => new C_CSGO_MapPreviewCameraPathNode_APIImpl(handle);
    static int ISchemaClass<C_CSGO_MapPreviewCameraPathNode_API>.Size => 8;
    static string? ISchemaClass<C_CSGO_MapPreviewCameraPathNode_API>.ClassName => null;

}