// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_EnvCubemapBox : C_EnvCubemap, ISchemaClass<C_EnvCubemapBox>
{
    static C_EnvCubemapBox ISchemaClass<C_EnvCubemapBox>.From(nint handle) => new C_EnvCubemapBoxImpl(handle);
    static int ISchemaClass<C_EnvCubemapBox>.Size => 1768;
    static string? ISchemaClass<C_EnvCubemapBox>.ClassName => null;

}