// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_EnvWindClientside : C_BaseEntity, ISchemaClass<C_EnvWindClientside>
{
    static C_EnvWindClientside ISchemaClass<C_EnvWindClientside>.From(nint handle) => new C_EnvWindClientsideImpl(handle);
    static int ISchemaClass<C_EnvWindClientside>.Size => 1784;
    static string? ISchemaClass<C_EnvWindClientside>.ClassName => null;


    public C_EnvWindShared EnvWindShared { get; }


}