// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_InfoInstructorHintHostageRescueZone : C_PointEntity, ISchemaClass<C_InfoInstructorHintHostageRescueZone>
{
    static C_InfoInstructorHintHostageRescueZone ISchemaClass<C_InfoInstructorHintHostageRescueZone>.From(nint handle) => new C_InfoInstructorHintHostageRescueZoneImpl(handle);
    static int ISchemaClass<C_InfoInstructorHintHostageRescueZone>.Size => 1536;
    static string? ISchemaClass<C_InfoInstructorHintHostageRescueZone>.ClassName => null;

}