// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_InfoLadderDismount : C_BaseEntity, ISchemaClass<C_InfoLadderDismount>
{
    static C_InfoLadderDismount ISchemaClass<C_InfoLadderDismount>.From(nint handle) => new C_InfoLadderDismountImpl(handle);
    static int ISchemaClass<C_InfoLadderDismount>.Size => 1536;
    static string? ISchemaClass<C_InfoLadderDismount>.ClassName => null;

}