// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PathParticleRopeAlias_path_particle_rope_clientside : C_PathParticleRope, ISchemaClass<C_PathParticleRopeAlias_path_particle_rope_clientside>
{
    static C_PathParticleRopeAlias_path_particle_rope_clientside ISchemaClass<C_PathParticleRopeAlias_path_particle_rope_clientside>.From(nint handle) => new C_PathParticleRopeAlias_path_particle_rope_clientsideImpl(handle);
    static int ISchemaClass<C_PathParticleRopeAlias_path_particle_rope_clientside>.Size => 1808;
    static string? ISchemaClass<C_PathParticleRopeAlias_path_particle_rope_clientside>.ClassName => null;

}