// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_PlayerPing : C_BaseEntity, ISchemaClass<C_PlayerPing>
{
    static C_PlayerPing ISchemaClass<C_PlayerPing>.From(nint handle) => new C_PlayerPingImpl(handle);
    static int ISchemaClass<C_PlayerPing>.Size => 1616;
    static string? ISchemaClass<C_PlayerPing>.ClassName => null;


    public ref CHandle<C_CSPlayerPawn> Player { get; }

    public ref CHandle<C_BaseEntity> PingedEntity { get; }

    public ref int Type { get; }

    public ref bool Urgent { get; }

    public string PlaceName { get; set; }


}