// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundOpvarSetOBBWindEntity : C_SoundOpvarSetPointBase, ISchemaClass<C_SoundOpvarSetOBBWindEntity>
{
    static C_SoundOpvarSetOBBWindEntity ISchemaClass<C_SoundOpvarSetOBBWindEntity>.From(nint handle) => new C_SoundOpvarSetOBBWindEntityImpl(handle);
    static int ISchemaClass<C_SoundOpvarSetOBBWindEntity>.Size => 1568;
    static string? ISchemaClass<C_SoundOpvarSetOBBWindEntity>.ClassName => null;

}