// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundEventConeEntity : C_SoundEventEntity, ISchemaClass<C_SoundEventConeEntity>
{
    static C_SoundEventConeEntity ISchemaClass<C_SoundEventConeEntity>.From(nint handle) => new C_SoundEventConeEntityImpl(handle);
    static int ISchemaClass<C_SoundEventConeEntity>.Size => 1752;
    static string? ISchemaClass<C_SoundEventConeEntity>.ClassName => null;


    public ref float EmitterAngle { get; }

    public ref float SweetSpotAngle { get; }

    public ref float AttenMin { get; }

    public ref float AttenMax { get; }

    public string ParameterName { get; set; }


}