// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundOpvarSetOBBEntity : C_SoundOpvarSetAABBEntity, ISchemaClass<C_SoundOpvarSetOBBEntity>
{
    static C_SoundOpvarSetOBBEntity ISchemaClass<C_SoundOpvarSetOBBEntity>.From(nint handle) => new C_SoundOpvarSetOBBEntityImpl(handle);
    static int ISchemaClass<C_SoundOpvarSetOBBEntity>.Size => 1568;
    static string? ISchemaClass<C_SoundOpvarSetOBBEntity>.ClassName => null;

}