// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundAreaEntityOrientedBox : C_SoundAreaEntityBase, ISchemaClass<C_SoundAreaEntityOrientedBox>
{
    static C_SoundAreaEntityOrientedBox ISchemaClass<C_SoundAreaEntityOrientedBox>.From(nint handle) => new C_SoundAreaEntityOrientedBoxImpl(handle);
    static int ISchemaClass<C_SoundAreaEntityOrientedBox>.Size => 1600;
    static string? ISchemaClass<C_SoundAreaEntityOrientedBox>.ClassName => null;


    public ref Vector Min { get; }

    public ref Vector Max { get; }


}