// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundOpvarSetPathCornerEntity : C_SoundOpvarSetPointEntity, ISchemaClass<C_SoundOpvarSetPathCornerEntity>
{
    static C_SoundOpvarSetPathCornerEntity ISchemaClass<C_SoundOpvarSetPathCornerEntity>.From(nint handle) => new C_SoundOpvarSetPathCornerEntityImpl(handle);
    static int ISchemaClass<C_SoundOpvarSetPathCornerEntity>.Size => 1568;
    static string? ISchemaClass<C_SoundOpvarSetPathCornerEntity>.ClassName => null;

}