// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundEventAABBEntity : C_SoundEventEntity, ISchemaClass<C_SoundEventAABBEntity>
{
    static C_SoundEventAABBEntity ISchemaClass<C_SoundEventAABBEntity>.From(nint handle) => new C_SoundEventAABBEntityImpl(handle);
    static int ISchemaClass<C_SoundEventAABBEntity>.Size => 1752;
    static string? ISchemaClass<C_SoundEventAABBEntity>.ClassName => null;


    public ref Vector Mins { get; }

    public ref Vector Maxs { get; }


}