// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_SoundOpvarSetPointBase : C_BaseEntity, ISchemaClass<C_SoundOpvarSetPointBase>
{
    static C_SoundOpvarSetPointBase ISchemaClass<C_SoundOpvarSetPointBase>.From(nint handle) => new C_SoundOpvarSetPointBaseImpl(handle);
    static int ISchemaClass<C_SoundOpvarSetPointBase>.Size => 1568;
    static string? ISchemaClass<C_SoundOpvarSetPointBase>.ClassName => null;


    public string StackName { get; set; }

    public string OperatorName { get; set; }

    public string OpvarName { get; set; }

    public ref int OpvarIndex { get; }

    public ref bool UseAutoCompare { get; }

    public ref bool FastRefresh { get; }


}