// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_TeamplayRules : C_MultiplayRules, ISchemaClass<C_TeamplayRules>
{
    static C_TeamplayRules ISchemaClass<C_TeamplayRules>.From(nint handle) => new C_TeamplayRulesImpl(handle);
    static int ISchemaClass<C_TeamplayRules>.Size => 64;
    static string? ISchemaClass<C_TeamplayRules>.ClassName => null;

}