// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface C_VoteController : C_BaseEntity, ISchemaClass<C_VoteController>
{
    static C_VoteController ISchemaClass<C_VoteController>.From(nint handle) => new C_VoteControllerImpl(handle);
    static int ISchemaClass<C_VoteController>.Size => 1592;
    static string? ISchemaClass<C_VoteController>.ClassName => null;


    public ref int ActiveIssueIndex { get; }

    public ref int OnlyTeamToVote { get; }

    public ISchemaFixedArray<int> VoteOptionCount { get; }

    public ref int PotentialVotes { get; }

    public ref bool VotesDirty { get; }

    public ref bool TypeDirty { get; }

    public ref bool IsYesNoVote { get; }


}