// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_MotionParameter : ISchemaClass<CAnimGraphDoc_MotionParameter>
{
    static CAnimGraphDoc_MotionParameter ISchemaClass<CAnimGraphDoc_MotionParameter>.From(nint handle) => new CAnimGraphDoc_MotionParameterImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_MotionParameter>.Size => 48;
    static string? ISchemaClass<CAnimGraphDoc_MotionParameter>.ClassName => null;


    public string Name { get; set; }

    public AnimParamID Id { get; }

    public ref float MinValue { get; }

    public ref float MaxValue { get; }

    public ref int Samples { get; }


}