// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_MotionParameterManager : ISchemaClass<CAnimGraphDoc_MotionParameterManager>
{
    static CAnimGraphDoc_MotionParameterManager ISchemaClass<CAnimGraphDoc_MotionParameterManager>.From(nint handle) => new CAnimGraphDoc_MotionParameterManagerImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_MotionParameterManager>.Size => 40;
    static string? ISchemaClass<CAnimGraphDoc_MotionParameterManager>.ClassName => null;


    public ref CUtlVector<SchemaUntypedField> Params { get; }


}