// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_StateTransition : ISchemaClass<CAnimGraphDoc_StateTransition>
{
    static CAnimGraphDoc_StateTransition ISchemaClass<CAnimGraphDoc_StateTransition>.From(nint handle) => new CAnimGraphDoc_StateTransitionImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_StateTransition>.Size => 112;
    static string? ISchemaClass<CAnimGraphDoc_StateTransition>.ClassName => null;


    public CAnimGraphDoc_ConditionContainer ConditionList { get; }

    public AnimStateID SrcState { get; }

    public AnimStateID DestState { get; }

    public string Comment { get; set; }

    public ref bool Disabled { get; }


}