// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_ZeroPoseNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_ZeroPoseNode>
{
    static CAnimGraphDoc_ZeroPoseNode ISchemaClass<CAnimGraphDoc_ZeroPoseNode>.From(nint handle) => new CAnimGraphDoc_ZeroPoseNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_ZeroPoseNode>.Size => 64;
    static string? ISchemaClass<CAnimGraphDoc_ZeroPoseNode>.ClassName => null;

}