// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_ToggleComponentAction : CAnimGraphDoc_Action, ISchemaClass<CAnimGraphDoc_ToggleComponentAction>
{
    static CAnimGraphDoc_ToggleComponentAction ISchemaClass<CAnimGraphDoc_ToggleComponentAction>.From(nint handle) => new CAnimGraphDoc_ToggleComponentActionImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_ToggleComponentAction>.Size => 48;
    static string? ISchemaClass<CAnimGraphDoc_ToggleComponentAction>.ClassName => null;


    public AnimComponentID ComponentID { get; }

    public ref bool SetEnabled { get; }


}