// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_GroupNode : CAnimGraphDoc_ContainerNodeBase, ISchemaClass<CAnimGraphDoc_GroupNode>
{
    static CAnimGraphDoc_GroupNode ISchemaClass<CAnimGraphDoc_GroupNode>.From(nint handle) => new CAnimGraphDoc_GroupNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_GroupNode>.Size => 184;
    static string? ISchemaClass<CAnimGraphDoc_GroupNode>.ClassName => null;


    public CAnimGraphDoc_NodeManager NodeMgr { get; }


}