// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphControllerPtr : ISchemaClass<CAnimGraphControllerPtr>
{
    static CAnimGraphControllerPtr ISchemaClass<CAnimGraphControllerPtr>.From(nint handle) => new CAnimGraphControllerPtrImpl(handle);
    static int ISchemaClass<CAnimGraphControllerPtr>.Size => 8;
    static string? ISchemaClass<CAnimGraphControllerPtr>.ClassName => null;


    public CAnimGraphControllerBase? Controller { get; }


}