// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_TargetWarpNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_TargetWarpNode>
{
    static CAnimGraphDoc_TargetWarpNode ISchemaClass<CAnimGraphDoc_TargetWarpNode>.From(nint handle) => new CAnimGraphDoc_TargetWarpNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_TargetWarpNode>.Size => 128;
    static string? ISchemaClass<CAnimGraphDoc_TargetWarpNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public ref TargetWarpLinearRootMotionMode LinearRootMotionMode { get; }

    public ref TargetWarpAngleMode_t AngleMode { get; }

    public ref TargetWarpCorrectionMethod CorrectionMethod { get; }

    public ref TargetWarpTimingMethod TargetWarpTimingMethod { get; }

    public AnimParamID MoveHeadingParamID { get; }

    public AnimParamID DesiredMoveHeadingParamID { get; }

    public AnimParamID TargetPositionParamID { get; }

    public ref bool TargetPositionIsWorldSpace { get; }

    public AnimParamID TargetFacePositionParamID { get; }

    public ref bool TargetFacePositionIsWorldSpace { get; }

    public AnimParamID TargetUpVectorParamID { get; }

    public ref bool OnlyWarpWhenTagIsFound { get; }

    public ref bool WarpOrientationDuringTranslation { get; }

    public ref float MaxAngle { get; }

    public ref bool WarpAroundCenter { get; }


}