// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_LeanMatrixNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_LeanMatrixNode>
{
    static CAnimGraphDoc_LeanMatrixNode ISchemaClass<CAnimGraphDoc_LeanMatrixNode>.From(nint handle) => new CAnimGraphDoc_LeanMatrixNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_LeanMatrixNode>.Size => 152;
    static string? ISchemaClass<CAnimGraphDoc_LeanMatrixNode>.ClassName => null;


    public string SequenceName { get; set; }

    public ref float MaxValue { get; }

    public ref AnimVectorSource BlendSource { get; }

    public string ParamName { get; set; }

    public AnimParamID Param { get; }

    public ref Vector VerticalAxisDirection { get; }

    public ref Vector HorizontalAxisDirection { get; }

    public CAnimInputDamping Damping { get; }


}