// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_BlockSelectionMetric : CAnimGraphDoc_MotionMetric, ISchemaClass<CAnimGraphDoc_BlockSelectionMetric>
{
    static CAnimGraphDoc_BlockSelectionMetric ISchemaClass<CAnimGraphDoc_BlockSelectionMetric>.From(nint handle) => new CAnimGraphDoc_BlockSelectionMetricImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_BlockSelectionMetric>.Size => 40;
    static string? ISchemaClass<CAnimGraphDoc_BlockSelectionMetric>.ClassName => null;

}