// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_TagSpan : ISchemaClass<CAnimGraphDoc_TagSpan>
{
    static CAnimGraphDoc_TagSpan ISchemaClass<CAnimGraphDoc_TagSpan>.From(nint handle) => new CAnimGraphDoc_TagSpanImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_TagSpan>.Size => 48;
    static string? ISchemaClass<CAnimGraphDoc_TagSpan>.ClassName => null;


    public AnimTagID Id { get; }

    public ref float StartCycle { get; }

    public ref float Duration { get; }


}