// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_GroupInputNode : CAnimGraphDoc_ProxyNodeBase, ISchemaClass<CAnimGraphDoc_GroupInputNode>
{
    static CAnimGraphDoc_GroupInputNode ISchemaClass<CAnimGraphDoc_GroupInputNode>.From(nint handle) => new CAnimGraphDoc_GroupInputNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_GroupInputNode>.Size => 104;
    static string? ISchemaClass<CAnimGraphDoc_GroupInputNode>.ClassName => null;

}