// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_FutureVelocityMetric : CAnimGraphDoc_MotionMetric, ISchemaClass<CAnimGraphDoc_FutureVelocityMetric>
{
    static CAnimGraphDoc_FutureVelocityMetric ISchemaClass<CAnimGraphDoc_FutureVelocityMetric>.From(nint handle) => new CAnimGraphDoc_FutureVelocityMetricImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_FutureVelocityMetric>.Size => 56;
    static string? ISchemaClass<CAnimGraphDoc_FutureVelocityMetric>.ClassName => null;


    public ref float Distance { get; }

    public ref float StoppingDistance { get; }

    public ref VelocityMetricMode Mode { get; }

    public ref bool AutoTargetSpeed { get; }

    public ref float ManualTargetSpeed { get; }


}