// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_StateMachineNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_StateMachineNode>
{
    static CAnimGraphDoc_StateMachineNode ISchemaClass<CAnimGraphDoc_StateMachineNode>.From(nint handle) => new CAnimGraphDoc_StateMachineNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_StateMachineNode>.Size => 112;
    static string? ISchemaClass<CAnimGraphDoc_StateMachineNode>.ClassName => null;


    public ref bool BlockWaningTags { get; }

    public ref bool LockStateWhenWaning { get; }

    public ref bool ResetWhenActivated { get; }


}