// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_MoverNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_MoverNode>
{
    static CAnimGraphDoc_MoverNode ISchemaClass<CAnimGraphDoc_MoverNode>.From(nint handle) => new CAnimGraphDoc_MoverNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_MoverNode>.Size => 168;
    static string? ISchemaClass<CAnimGraphDoc_MoverNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public ref bool ApplyMovement { get; }

    public string MoveVectorParamName { get; set; }

    public AnimParamID MoveVectorParam { get; }

    public ref bool OrientMovement { get; }

    public string MoveHeadingParamName { get; set; }

    public AnimParamID MoveHeadingParam { get; }

    public ref bool Additive { get; }

    public ref bool TurnToFace { get; }

    public ref AnimValueSource FacingTarget { get; }

    public string ParamName { get; set; }

    public AnimParamID Param { get; }

    public ref bool LimitOnly { get; }

    public ref float TurnToFaceOffset { get; }

    public ref float TurnToFaceLimit { get; }

    public CAnimInputDamping Damping { get; }


}