// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_RagdollNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_RagdollNode>
{
    static CAnimGraphDoc_RagdollNode ISchemaClass<CAnimGraphDoc_RagdollNode>.From(nint handle) => new CAnimGraphDoc_RagdollNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_RagdollNode>.Size => 88;
    static string? ISchemaClass<CAnimGraphDoc_RagdollNode>.ClassName => null;


    public string WeightListName { get; set; }

    public ref RagdollPoseControl PoseControlMethod { get; }

    public CAnimGraphDoc_NodeConnection InputConnection { get; }


}