// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_CommentNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_CommentNode>
{
    static CAnimGraphDoc_CommentNode ISchemaClass<CAnimGraphDoc_CommentNode>.From(nint handle) => new CAnimGraphDoc_CommentNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_CommentNode>.Size => 88;
    static string? ISchemaClass<CAnimGraphDoc_CommentNode>.ClassName => null;


    public string CommentText { get; set; }

    public ref Vector2D Size { get; }

    public ref Color Color { get; }


}