// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_SpeedScaleNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_SpeedScaleNode>
{
    static CAnimGraphDoc_SpeedScaleNode ISchemaClass<CAnimGraphDoc_SpeedScaleNode>.From(nint handle) => new CAnimGraphDoc_SpeedScaleNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_SpeedScaleNode>.Size => 88;
    static string? ISchemaClass<CAnimGraphDoc_SpeedScaleNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public string ParamName { get; set; }

    public AnimParamID Param { get; }


}