// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_FootPositionMetric : CAnimGraphDoc_MotionMetric, ISchemaClass<CAnimGraphDoc_FootPositionMetric>
{
    static CAnimGraphDoc_FootPositionMetric ISchemaClass<CAnimGraphDoc_FootPositionMetric>.From(nint handle) => new CAnimGraphDoc_FootPositionMetricImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_FootPositionMetric>.Size => 72;
    static string? ISchemaClass<CAnimGraphDoc_FootPositionMetric>.ClassName => null;


    public ref CUtlVector<CUtlString> Feet { get; }

    public ref bool IgnoreSlope { get; }


}