// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_MotionItem : ISchemaClass<CAnimGraphDoc_MotionItem>
{
    static CAnimGraphDoc_MotionItem ISchemaClass<CAnimGraphDoc_MotionItem>.From(nint handle) => new CAnimGraphDoc_MotionItemImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_MotionItem>.Size => 168;
    static string? ISchemaClass<CAnimGraphDoc_MotionItem>.ClassName => null;


    public CAnimGraphDoc_MotionParameterManager ParamManager { get; }

    public ref CUtlVector<SchemaUntypedField> BlockSpans { get; }

    public ref CUtlVector<SchemaUntypedField> TagSpans { get; }

    public ref CUtlVector<SchemaUntypedField> ParamSpans { get; }

    public ref bool Loop { get; }


}