// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_NodeList : ISchemaClass<CAnimGraphDoc_NodeList>
{
    static CAnimGraphDoc_NodeList ISchemaClass<CAnimGraphDoc_NodeList>.From(nint handle) => new CAnimGraphDoc_NodeListImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_NodeList>.Size => 40;
    static string? ISchemaClass<CAnimGraphDoc_NodeList>.ClassName => null;


    public ref CUtlVector<PointerTo<CAnimGraphDoc_Node>> Nodes { get; }


}