// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_ParamSpan : ISchemaClass<CAnimGraphDoc_ParamSpan>
{
    static CAnimGraphDoc_ParamSpan ISchemaClass<CAnimGraphDoc_ParamSpan>.From(nint handle) => new CAnimGraphDoc_ParamSpanImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_ParamSpan>.Size => 80;
    static string? ISchemaClass<CAnimGraphDoc_ParamSpan>.ClassName => null;


    public ref CUtlVector<CAnimGraphDoc_ParamSpanSample> Samples { get; }

    public string ParamName { get; set; }

    public AnimParamID Id { get; }

    public ref float StartCycle { get; }

    public ref float EndCycle { get; }


}