// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_State : ISchemaClass<CAnimGraphDoc_State>
{
    static CAnimGraphDoc_State ISchemaClass<CAnimGraphDoc_State>.From(nint handle) => new CAnimGraphDoc_StateImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_State>.Size => 128;
    static string? ISchemaClass<CAnimGraphDoc_State>.ClassName => null;


    public ref CUtlVector<SchemaUntypedField> Transitions { get; }

    public ref CUtlVector<CStateAction> Actions { get; }

    public string Name { get; set; }

    public string Comment { get; set; }

    public AnimStateID StateID { get; }

    public ref Vector2D Position { get; }

    public ref bool IsStartState { get; }

    public ref bool IsEndtState { get; }

    public ref bool IsInputToGraph { get; }

    public ref bool IsPassthrough { get; }

    public ref bool IsPassthroughRootMotion { get; }

    public ref bool PreEvaluatePassthroughTransitionPath { get; }


}