// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_BoneMaskNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_BoneMaskNode>
{
    static CAnimGraphDoc_BoneMaskNode ISchemaClass<CAnimGraphDoc_BoneMaskNode>.From(nint handle) => new CAnimGraphDoc_BoneMaskNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_BoneMaskNode>.Size => 136;
    static string? ISchemaClass<CAnimGraphDoc_BoneMaskNode>.ClassName => null;


    public string WeightListName { get; set; }

    public CAnimGraphDoc_NodeConnection InputConnection1 { get; }

    public CAnimGraphDoc_NodeConnection InputConnection2 { get; }

    public ref BoneMaskBlendSpace BlendSpace { get; }

    public ref bool UseBlendScale { get; }

    public ref AnimValueSource BlendValueSource { get; }

    public string BlendParameterName { get; set; }

    public AnimParamID BlendParameter { get; }

    public ref BinaryNodeTiming TimingBehavior { get; }

    public ref float TimingBlend { get; }

    public ref float RootMotionBlend { get; }

    public ref BinaryNodeChildOption FootMotionTiming { get; }

    public ref bool ResetChild1 { get; }

    public ref bool ResetChild2 { get; }


}