// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_FootLockNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_FootLockNode>
{
    static CAnimGraphDoc_FootLockNode ISchemaClass<CAnimGraphDoc_FootLockNode>.From(nint handle) => new CAnimGraphDoc_FootLockNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_FootLockNode>.Size => 296;
    static string? ISchemaClass<CAnimGraphDoc_FootLockNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public ref CUtlVector<CFootLockItem> Items { get; }

    public string HipBoneName { get; set; }

    public ref float BlendTime { get; }

    public ref bool ApplyFootRotationLimits { get; }

    public ref bool ResetChild { get; }

    public ref IKSolverType IkSolverType { get; }

    public ref bool AlwaysUseFallbackHinge { get; }

    public ref bool ApplyLegTwistLimits { get; }

    public ref float MaxLegTwist { get; }

    public ref float StrideCurveScale { get; }

    public ref float StrideCurveLimitScale { get; }

    public ref bool EnableVerticalCurvedPaths { get; }

    public ref bool ModulateStepHeight { get; }

    public ref float StepHeightIncreaseScale { get; }

    public ref float StepHeightDecreaseScale { get; }

    public ref bool EnableHipShift { get; }

    public ref float HipShiftScale { get; }

    public CAnimInputDamping HipShiftDamping { get; }

    public ref bool ApplyTilt { get; }

    public ref float TiltPlanePitchSpringStrength { get; }

    public ref float TiltPlaneRollSpringStrength { get; }

    public ref bool EnableLockBreaking { get; }

    public ref float LockBreakTolerance { get; }

    public ref float LockBreakBlendTime { get; }

    public ref bool EnableStretching { get; }

    public ref float MaxStretchAmount { get; }

    public ref float StretchExtensionScale { get; }

    public ref bool EnableGroundTracing { get; }

    public ref float TraceAngleBlend { get; }

    public ref bool ApplyHipDrop { get; }

    public ref float MaxFootHeight { get; }

    public ref float ExtensionScale { get; }

    public CAnimInputDamping HipDampingSettings { get; }

    public ref bool EnableRootHeightDamping { get; }

    public CAnimInputDamping RootHeightDamping { get; }

    public ref float MaxRootHeightOffset { get; }

    public ref float MinRootHeightOffset { get; }


}