// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_Motor : ISchemaClass<CAnimGraphDoc_Motor>
{
    static CAnimGraphDoc_Motor ISchemaClass<CAnimGraphDoc_Motor>.From(nint handle) => new CAnimGraphDoc_MotorImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_Motor>.Size => 48;
    static string? ISchemaClass<CAnimGraphDoc_Motor>.ClassName => null;


    public string Name { get; set; }

    public ref bool Default { get; }


}