// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_FinishedCondition : CAnimGraphDoc_Condition, ISchemaClass<CAnimGraphDoc_FinishedCondition>
{
    static CAnimGraphDoc_FinishedCondition ISchemaClass<CAnimGraphDoc_FinishedCondition>.From(nint handle) => new CAnimGraphDoc_FinishedConditionImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_FinishedCondition>.Size => 48;
    static string? ISchemaClass<CAnimGraphDoc_FinishedCondition>.ClassName => null;


    public ref FinishedConditionOption Option { get; }

    public ref bool IsFinished { get; }


}