// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_PathMotor : CAnimGraphDoc_PathMotorBase, ISchemaClass<CAnimGraphDoc_PathMotor>
{
    static CAnimGraphDoc_PathMotor ISchemaClass<CAnimGraphDoc_PathMotor>.From(nint handle) => new CAnimGraphDoc_PathMotorImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_PathMotor>.Size => 56;
    static string? ISchemaClass<CAnimGraphDoc_PathMotor>.ClassName => null;

}