// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_MotionMatchingNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_MotionMatchingNode>
{
    static CAnimGraphDoc_MotionMatchingNode ISchemaClass<CAnimGraphDoc_MotionMatchingNode>.From(nint handle) => new CAnimGraphDoc_MotionMatchingNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_MotionMatchingNode>.Size => 216;
    static string? ISchemaClass<CAnimGraphDoc_MotionMatchingNode>.ClassName => null;


    public ref CUtlVector<SchemaUntypedField> Groups { get; }

    public ref CUtlVector<SchemaUntypedField> Metrics { get; }

    public CBlendCurve BlendCurve { get; }

    public ref int RandomSeed { get; }

    public ref float SampleRate { get; }

    public ref bool SearchEveryTick { get; }

    public ref float SearchInterval { get; }

    public ref bool SearchWhenMotionEnds { get; }

    public ref bool SearchWhenGoalChanges { get; }

    public ref float BlendTime { get; }

    public ref float SelectionThreshold { get; }

    public ref float ReselectionTimeWindow { get; }

    public ref bool LockSelectionWhenWaning { get; }

    public ref bool EnableRotationCorrection { get; }

    public ref bool GoalAssist { get; }

    public ref float GoalAssistDistance { get; }

    public ref float GoalAssistTolerance { get; }

    public ref bool EnableDistanceScaling { get; }

    public ref float DistanceScale_OuterRadius { get; }

    public ref float DistanceScale_InnerRadius { get; }

    public ref float DistanceScale_MaxScale { get; }

    public ref float DistanceScale_MinScale { get; }

    public CAnimInputDamping DistanceScale_Damping { get; }


}