// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_Component : ISchemaClass<CAnimGraphDoc_Component>
{
    static CAnimGraphDoc_Component ISchemaClass<CAnimGraphDoc_Component>.From(nint handle) => new CAnimGraphDoc_ComponentImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_Component>.Size => 56;
    static string? ISchemaClass<CAnimGraphDoc_Component>.ClassName => null;


    public string Group { get; set; }

    public AnimComponentID Id { get; }

    public ref bool StartEnabled { get; }

    public ref int Priority { get; }

    public ref AnimNodeNetworkMode NetworkMode { get; }


}