// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_FootPinningNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_FootPinningNode>
{
    static CAnimGraphDoc_FootPinningNode ISchemaClass<CAnimGraphDoc_FootPinningNode>.From(nint handle) => new CAnimGraphDoc_FootPinningNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_FootPinningNode>.Size => 144;
    static string? ISchemaClass<CAnimGraphDoc_FootPinningNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public ref CUtlVector<CFootPinningItem> Items { get; }

    public ref FootPinningTimingSource TimingSource { get; }

    public ref float BlendTime { get; }

    public ref float LockBreakDistance { get; }

    public ref float MaxLegStraightAmount { get; }

    public ref bool ApplyFootRotationLimits { get; }

    public string HipBoneName { get; set; }

    public ref bool ApplyLegTwistLimits { get; }

    public ref float MaxLegTwist { get; }

    public ref bool ResetChild { get; }


}