// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_AddNode : CAnimGraphDoc_Node, ISchemaClass<CAnimGraphDoc_AddNode>
{
    static CAnimGraphDoc_AddNode ISchemaClass<CAnimGraphDoc_AddNode>.From(nint handle) => new CAnimGraphDoc_AddNodeImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_AddNode>.Size => 104;
    static string? ISchemaClass<CAnimGraphDoc_AddNode>.ClassName => null;


    public CAnimGraphDoc_NodeConnection BaseInput { get; }

    public CAnimGraphDoc_NodeConnection AdditiveInput { get; }

    public ref BinaryNodeTiming TimingBehavior { get; }

    public ref float TimingBlend { get; }

    public ref BinaryNodeChildOption FootMotionTiming { get; }

    public ref bool ApplyToFootMotion { get; }

    public ref bool ResetBase { get; }

    public ref bool ResetAdditive { get; }

    public ref bool ApplyChannelsSeparately { get; }

    public ref bool UseModelSpace { get; }

    public ref bool ApplyScale { get; }


}