// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAnimGraphDoc_PathMotorBase : CAnimGraphDoc_Motor, ISchemaClass<CAnimGraphDoc_PathMotorBase>
{
    static CAnimGraphDoc_PathMotorBase ISchemaClass<CAnimGraphDoc_PathMotorBase>.From(nint handle) => new CAnimGraphDoc_PathMotorBaseImpl(handle);
    static int ISchemaClass<CAnimGraphDoc_PathMotorBase>.Size => 56;
    static string? ISchemaClass<CAnimGraphDoc_PathMotorBase>.ClassName => null;


    public ref bool LockToPath { get; }


}