// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAssetWarning : ISchemaClass<CAssetWarning>
{
    static CAssetWarning ISchemaClass<CAssetWarning>.From(nint handle) => new CAssetWarningImpl(handle);
    static int ISchemaClass<CAssetWarning>.Size => 64;
    static string? ISchemaClass<CAssetWarning>.ClassName => null;


    public ref CBufferString Title { get; }

    public ref CBufferString Message { get; }

    public ref CUtlVector<CAssetWarningCheck> Checks { get; }


}