// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAssetTypeConfig : ISchemaClass<CAssetTypeConfig>
{
    static CAssetTypeConfig ISchemaClass<CAssetTypeConfig>.From(nint handle) => new CAssetTypeConfigImpl(handle);
    static int ISchemaClass<CAssetTypeConfig>.Size => 72;
    static string? ISchemaClass<CAssetTypeConfig>.ClassName => null;


    public ref CUtlVector<PointerTo<CSimpleAssetTypeInfo>> AssetTypes { get; }

    public ref CUtlVector<PointerTo<CSubassetTypeInfo>> SubassetTypes { get; }

    public ref CUtlVector<PointerTo<CAssetWarning>> AssetWarnings { get; }


}