// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioEffectChainNodeDesc : CVAudioNodeBaseDesc, ISchemaClass<CAudioEffectChainNodeDesc>
{
    static CAudioEffectChainNodeDesc ISchemaClass<CAudioEffectChainNodeDesc>.From(nint handle) => new CAudioEffectChainNodeDescImpl(handle);
    static int ISchemaClass<CAudioEffectChainNodeDesc>.Size => 136;
    static string? ISchemaClass<CAudioEffectChainNodeDesc>.ClassName => null;

}