// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioDynamicsNodeDesc : CVNodeTypeDesc, ISchemaClass<CAudioDynamicsNodeDesc>
{
    static CAudioDynamicsNodeDesc ISchemaClass<CAudioDynamicsNodeDesc>.From(nint handle) => new CAudioDynamicsNodeDescImpl(handle);
    static int ISchemaClass<CAudioDynamicsNodeDesc>.Size => 136;
    static string? ISchemaClass<CAudioDynamicsNodeDesc>.ClassName => null;

}