// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioOutputNodeDesc : CVNodeTypeDesc, ISchemaClass<CAudioOutputNodeDesc>
{
    static CAudioOutputNodeDesc ISchemaClass<CAudioOutputNodeDesc>.From(nint handle) => new CAudioOutputNodeDescImpl(handle);
    static int ISchemaClass<CAudioOutputNodeDesc>.Size => 136;
    static string? ISchemaClass<CAudioOutputNodeDesc>.ClassName => null;

}