// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioProcessorNodeDesc : CVAudioNodeBaseDesc, ISchemaClass<CAudioProcessorNodeDesc>
{
    static CAudioProcessorNodeDesc ISchemaClass<CAudioProcessorNodeDesc>.From(nint handle) => new CAudioProcessorNodeDescImpl(handle);
    static int ISchemaClass<CAudioProcessorNodeDesc>.Size => 136;
    static string? ISchemaClass<CAudioProcessorNodeDesc>.ClassName => null;

}