// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CAudioFlangerNodeDesc : CVAudioNodeBaseDesc, ISchemaClass<CAudioFlangerNodeDesc>
{
    static CAudioFlangerNodeDesc ISchemaClass<CAudioFlangerNodeDesc>.From(nint handle) => new CAudioFlangerNodeDescImpl(handle);
    static int ISchemaClass<CAudioFlangerNodeDesc>.Size => 136;
    static string? ISchemaClass<CAudioFlangerNodeDesc>.ClassName => null;

}