// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CChoiceNodeChild : ISchemaClass<CChoiceNodeChild>
{
    static CChoiceNodeChild ISchemaClass<CChoiceNodeChild>.From(nint handle) => new CChoiceNodeChildImpl(handle);
    static int ISchemaClass<CChoiceNodeChild>.Size => 24;
    static string? ISchemaClass<CChoiceNodeChild>.ClassName => null;


    public CAnimGraphDoc_NodeConnection InputConnection { get; }

    public string Name { get; set; }

    public ref float Weight { get; }

    public ref float BlendTime { get; }


}