// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CColorCorrectionLayer : ISchemaClass<CColorCorrectionLayer>
{
    static CColorCorrectionLayer ISchemaClass<CColorCorrectionLayer>.From(nint handle) => new CColorCorrectionLayerImpl(handle);
    static int ISchemaClass<CColorCorrectionLayer>.Size => 40;
    static string? ISchemaClass<CColorCorrectionLayer>.ClassName => null;


    public string Name { get; set; }

    public ref int OpacityPercent { get; }

    public ref bool Visible { get; }

    public CLayerMask? LayerMask { get; }


}