// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCompositeMaterialEditorDoc : ISchemaClass<CCompositeMaterialEditorDoc>
{
    static CCompositeMaterialEditorDoc ISchemaClass<CCompositeMaterialEditorDoc>.From(nint handle) => new CCompositeMaterialEditorDocImpl(handle);
    static int ISchemaClass<CCompositeMaterialEditorDoc>.Size => 56;
    static string? ISchemaClass<CCompositeMaterialEditorDoc>.ClassName => null;


    public ref int Version { get; }

    public ref CUtlVector<CompositeMaterialEditorPoint_t> Points { get; }

    // KeyValues3
    public SchemaUntypedField KVthumbnail { get; }


}