// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CControlCrossfadeNodeDesc : CVControlNodeBaseDesc, ISchemaClass<CControlCrossfadeNodeDesc>
{
    static CControlCrossfadeNodeDesc ISchemaClass<CControlCrossfadeNodeDesc>.From(nint handle) => new CControlCrossfadeNodeDescImpl(handle);
    static int ISchemaClass<CControlCrossfadeNodeDesc>.Size => 136;
    static string? ISchemaClass<CControlCrossfadeNodeDesc>.ClassName => null;

}