// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSGO_TeamPreviewCharacterPosition_API : ISchemaClass<CCSGO_TeamPreviewCharacterPosition_API>
{
    static CCSGO_TeamPreviewCharacterPosition_API ISchemaClass<CCSGO_TeamPreviewCharacterPosition_API>.From(nint handle) => new CCSGO_TeamPreviewCharacterPosition_APIImpl(handle);
    static int ISchemaClass<CCSGO_TeamPreviewCharacterPosition_API>.Size => 8;
    static string? ISchemaClass<CCSGO_TeamPreviewCharacterPosition_API>.ClassName => null;

}