// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSObserverPawn_API : ISchemaClass<CCSObserverPawn_API>
{
    static CCSObserverPawn_API ISchemaClass<CCSObserverPawn_API>.From(nint handle) => new CCSObserverPawn_APIImpl(handle);
    static int ISchemaClass<CCSObserverPawn_API>.Size => 8;
    static string? ISchemaClass<CCSObserverPawn_API>.ClassName => null;

}