// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CCSWeaponBase_API : ISchemaClass<CCSWeaponBase_API>
{
    static CCSWeaponBase_API ISchemaClass<CCSWeaponBase_API>.From(nint handle) => new CCSWeaponBase_APIImpl(handle);
    static int ISchemaClass<CCSWeaponBase_API>.Size => 8;
    static string? ISchemaClass<CCSWeaponBase_API>.ClassName => null;

}