// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CDemoSettingsComponent : CAnimGraphDoc_Component, ISchemaClass<CDemoSettingsComponent>
{
    static CDemoSettingsComponent ISchemaClass<CDemoSettingsComponent>.From(nint handle) => new CDemoSettingsComponentImpl(handle);
    static int ISchemaClass<CDemoSettingsComponent>.Size => 184;
    static string? ISchemaClass<CDemoSettingsComponent>.ClassName => null;


    public CAnimDemoCaptureSettings Settings { get; }


}