// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CEnvSkyAPI : ISchemaClass<CEnvSkyAPI>
{
    static CEnvSkyAPI ISchemaClass<CEnvSkyAPI>.From(nint handle) => new CEnvSkyAPIImpl(handle);
    static int ISchemaClass<CEnvSkyAPI>.Size => 8;
    static string? ISchemaClass<CEnvSkyAPI>.ClassName => null;

}