// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CExternalAnimGraphList : ISchemaClass<CExternalAnimGraphList>
{
    static CExternalAnimGraphList ISchemaClass<CExternalAnimGraphList>.From(nint handle) => new CExternalAnimGraphListImpl(handle);
    static int ISchemaClass<CExternalAnimGraphList>.Size => 32;
    static string? ISchemaClass<CExternalAnimGraphList>.ClassName => null;

}