// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFootLockItem : ISchemaClass<CFootLockItem>
{
    static CFootLockItem ISchemaClass<CFootLockItem>.From(nint handle) => new CFootLockItemImpl(handle);
    static int ISchemaClass<CFootLockItem>.Size => 64;
    static string? ISchemaClass<CFootLockItem>.ClassName => null;


    public string FootName { get; set; }

    public string TargetBoneName { get; set; }

    public string IkChainName { get; set; }

    public ref CGlobalSymbol DisableTagName { get; }

    public AnimTagID DisableTagID { get; }

    public ref float MaxRotationLeft { get; }

    public ref float MaxRotationRight { get; }

    public ref CGlobalSymbol FootstepLandedTagName { get; }

    public AnimTagID FootstepLandedTag { get; }


}