// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CFuncConveyor_API : ISchemaClass<CFuncConveyor_API>
{
    static CFuncConveyor_API ISchemaClass<CFuncConveyor_API>.From(nint handle) => new CFuncConveyor_APIImpl(handle);
    static int ISchemaClass<CFuncConveyor_API>.Size => 8;
    static string? ISchemaClass<CFuncConveyor_API>.ClassName => null;

}