// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CGraphPreviewList : ISchemaClass<CGraphPreviewList>
{
    static CGraphPreviewList ISchemaClass<CGraphPreviewList>.From(nint handle) => new CGraphPreviewListImpl(handle);
    static int ISchemaClass<CGraphPreviewList>.Size => 40;
    static string? ISchemaClass<CGraphPreviewList>.ClassName => null;


    public ref float Volume { get; }

    public CPreviewList PreviewList { get; }


}