// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CLightRigPostProcessing : ISchemaClass<CLightRigPostProcessing>
{
    static CLightRigPostProcessing ISchemaClass<CLightRigPostProcessing>.From(nint handle) => new CLightRigPostProcessingImpl(handle);
    static int ISchemaClass<CLightRigPostProcessing>.Size => 8;
    static string? ISchemaClass<CLightRigPostProcessing>.ClassName => null;


    public ref CStrongHandle<InfoForResourceTypeCPostProcessingResource> PostProcessing { get; }


}