// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMapInfo_API : ISchemaClass<CMapInfo_API>
{
    static CMapInfo_API ISchemaClass<CMapInfo_API>.From(nint handle) => new CMapInfo_APIImpl(handle);
    static int ISchemaClass<CMapInfo_API>.Size => 8;
    static string? ISchemaClass<CMapInfo_API>.ClassName => null;

}