// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMarkupSearch_PathCostAreaFilter : INavPathCostAreaFilter, ISchemaClass<CMarkupSearch_PathCostAreaFilter>
{
    static CMarkupSearch_PathCostAreaFilter ISchemaClass<CMarkupSearch_PathCostAreaFilter>.From(nint handle) => new CMarkupSearch_PathCostAreaFilterImpl(handle);
    static int ISchemaClass<CMarkupSearch_PathCostAreaFilter>.Size => 696;
    static string? ISchemaClass<CMarkupSearch_PathCostAreaFilter>.ClassName => null;


    public CMarkupSearchHelper SearchHelper { get; }


}