// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixDynamics3Band : CMixPropertyBase, ISchemaClass<CMixDynamics3Band>
{
    static CMixDynamics3Band ISchemaClass<CMixDynamics3Band>.From(nint handle) => new CMixDynamics3BandImpl(handle);
    static int ISchemaClass<CMixDynamics3Band>.Size => 184;
    static string? ISchemaClass<CMixDynamics3Band>.ClassName => null;


    public ref int Channels { get; }

    public ref float FldbOutputGain { get; }

    public ref float RMSTime { get; }

    public ref float Depth { get; }

    public ref float WetMix { get; }

    public ref float TimeScale { get; }

    public ref float FldbKneeWidth { get; }

    public ref float LowCutoffFreq { get; }

    public ref float HighCutoffFreq { get; }

    public ref bool PeakMode { get; }

    public ref int SelectedPage { get; }

    public ISchemaClassFixedArray<VMixDynamicsBand_t> Bands { get; }


}