// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixSum : CMixPropertyBase, ISchemaClass<CMixSum>
{
    static CMixSum ISchemaClass<CMixSum>.From(nint handle) => new CMixSumImpl(handle);
    static int ISchemaClass<CMixSum>.Size => 128;
    static string? ISchemaClass<CMixSum>.ClassName => null;


    public ref float Volume1 { get; }

    public ref float Volume2 { get; }

    public ref float Volume3 { get; }

    public ref float Volume4 { get; }

    public ref float Volume5 { get; }

    public ref float Volume6 { get; }

    public ref float Volume7 { get; }

    public ref float Volume8 { get; }

    public ISchemaUtlStringFixedArray ChannelName { get; }


}