// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixSteamAudioPathing : CMixPropertyBase, ISchemaClass<CMixSteamAudioPathing>
{
    static CMixSteamAudioPathing ISchemaClass<CMixSteamAudioPathing>.From(nint handle) => new CMixSteamAudioPathingImpl(handle);
    static int ISchemaClass<CMixSteamAudioPathing>.Size => 96;
    static string? ISchemaClass<CMixSteamAudioPathing>.ClassName => null;


    public ref float PathingMixLevel { get; }

    public ISchemaFixedArray<float> PathingEQ { get; }

    public ref CUtlVector<float> PathingCoeffs { get; }

    public ref CUtlVector<float> PathingEQ1 { get; }


}