// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixDynamics : CMixPropertyBase, ISchemaClass<CMixDynamics>
{
    static CMixDynamics ISchemaClass<CMixDynamics>.From(nint handle) => new CMixDynamicsImpl(handle);
    static int ISchemaClass<CMixDynamics>.Size => 88;
    static string? ISchemaClass<CMixDynamics>.ClassName => null;


    public ref int Channels { get; }

    public ref float FldbNoiseGateThreshold { get; }

    public ref float FldbGain { get; }

    public ref float FldbCompressionThreshold { get; }

    public ref float FldbLimiterThreshold { get; }

    public ref float FldbKneeWidth { get; }

    public ref float Ratio { get; }

    public ref float LimiterRatio { get; }

    public ref float AttackTime { get; }

    public ref float ReleaseTime { get; }

    public ref float RMSTime { get; }

    public ref float WetMix { get; }

    public ref bool PeakMode { get; }

    public ref int UIPage { get; }


}