// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixEnvelopeTrigger : CMixPropertyBase, ISchemaClass<CMixEnvelopeTrigger>
{
    static CMixEnvelopeTrigger ISchemaClass<CMixEnvelopeTrigger>.From(nint handle) => new CMixEnvelopeTriggerImpl(handle);
    static int ISchemaClass<CMixEnvelopeTrigger>.Size => 56;
    static string? ISchemaClass<CMixEnvelopeTrigger>.ClassName => null;


    public ref float BaseValue { get; }

    public ref float DestinationValue { get; }

    public ref float AttackTime { get; }

    public ref float HoldTime { get; }

    public ref float ReleaseTime { get; }


}