// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixSplitterBlend : CMixPropertyBase, ISchemaClass<CMixSplitterBlend>
{
    static CMixSplitterBlend ISchemaClass<CMixSplitterBlend>.From(nint handle) => new CMixSplitterBlendImpl(handle);
    static int ISchemaClass<CMixSplitterBlend>.Size => 40;
    static string? ISchemaClass<CMixSplitterBlend>.ClassName => null;


    public ref float LockAmount { get; }


}