// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixEvelopeTriggerDesc : CVControlNodeBaseDesc, ISchemaClass<CMixEvelopeTriggerDesc>
{
    static CMixEvelopeTriggerDesc ISchemaClass<CMixEvelopeTriggerDesc>.From(nint handle) => new CMixEvelopeTriggerDescImpl(handle);
    static int ISchemaClass<CMixEvelopeTriggerDesc>.Size => 136;
    static string? ISchemaClass<CMixEvelopeTriggerDesc>.ClassName => null;

}