// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixGroupBoxDesc : CVNodeTypeDesc, ISchemaClass<CMixGroupBoxDesc>
{
    static CMixGroupBoxDesc ISchemaClass<CMixGroupBoxDesc>.From(nint handle) => new CMixGroupBoxDescImpl(handle);
    static int ISchemaClass<CMixGroupBoxDesc>.Size => 136;
    static string? ISchemaClass<CMixGroupBoxDesc>.ClassName => null;

}