// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixOsc : CMixPropertyBase, ISchemaClass<CMixOsc>
{
    static CMixOsc ISchemaClass<CMixOsc>.From(nint handle) => new CMixOscImpl(handle);
    static int ISchemaClass<CMixOsc>.Size => 48;
    static string? ISchemaClass<CMixOsc>.ClassName => null;


    public VMixOscDesc_t Desc { get; }


}