// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixSteamAudioHybridReverb : CMixPropertyBase, ISchemaClass<CMixSteamAudioHybridReverb>
{
    static CMixSteamAudioHybridReverb ISchemaClass<CMixSteamAudioHybridReverb>.From(nint handle) => new CMixSteamAudioHybridReverbImpl(handle);
    static int ISchemaClass<CMixSteamAudioHybridReverb>.Size => 72;
    static string? ISchemaClass<CMixSteamAudioHybridReverb>.ClassName => null;


    public ref float ReverbTimeLow { get; }

    public ref float ReverbTimeMid { get; }

    public ref float ReverbTimeHigh { get; }

    public ref CUtlVector<float> ReverbTime { get; }


}