// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixGroupBox : CMixPropertyBase, ISchemaClass<CMixGroupBox>
{
    static CMixGroupBox ISchemaClass<CMixGroupBox>.From(nint handle) => new CMixGroupBoxImpl(handle);
    static int ISchemaClass<CMixGroupBox>.Size => 40;
    static string? ISchemaClass<CMixGroupBox>.ClassName => null;


    public ref Color Color { get; }

    public ref bool MovesNodes { get; }


}