// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CMixSplitter : CMixPropertyBase, ISchemaClass<CMixSplitter>
{
    static CMixSplitter ISchemaClass<CMixSplitter>.From(nint handle) => new CMixSplitterImpl(handle);
    static int ISchemaClass<CMixSplitter>.Size => 64;
    static string? ISchemaClass<CMixSplitter>.ClassName => null;


    public ref float Volume1 { get; }

    public ref float Volume2 { get; }

    public ref float Volume3 { get; }

    public ref float Volume4 { get; }

    public ref float Volume5 { get; }

    public ref float Volume6 { get; }

    public ref float Volume7 { get; }

    public ref float Volume8 { get; }


}