// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNavFlags : ISchemaClass<CNavFlags>
{
    static CNavFlags ISchemaClass<CNavFlags>.From(nint handle) => new CNavFlagsImpl(handle);
    static int ISchemaClass<CNavFlags>.Size => 8;
    static string? ISchemaClass<CNavFlags>.ClassName => null;


    public ref ulong Flags { get; }


}