// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmBlendSpace1D : ISchemaClass<CNmBlendSpace1D>
{
    static CNmBlendSpace1D ISchemaClass<CNmBlendSpace1D>.From(nint handle) => new CNmBlendSpace1DImpl(handle);
    static int ISchemaClass<CNmBlendSpace1D>.Size => 24;
    static string? ISchemaClass<CNmBlendSpace1D>.ClassName => null;


    public ref CUtlVector<CNmBlendSpace1D__Point_t> Points { get; }


}