// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmBlendSpace1D__Point_t : ISchemaClass<CNmBlendSpace1D__Point_t>
{
    static CNmBlendSpace1D__Point_t ISchemaClass<CNmBlendSpace1D__Point_t>.From(nint handle) => new CNmBlendSpace1D__Point_tImpl(handle);
    static int ISchemaClass<CNmBlendSpace1D__Point_t>.Size => 32;
    static string? ISchemaClass<CNmBlendSpace1D__Point_t>.ClassName => null;


    public string Name { get; set; }

    public ref float Value { get; }

    // V_uuid_t
    public SchemaUntypedField PinID { get; }


}