// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmClipDocEventTrack : ISchemaClass<CNmClipDocEventTrack>
{
    static CNmClipDocEventTrack ISchemaClass<CNmClipDocEventTrack>.From(nint handle) => new CNmClipDocEventTrackImpl(handle);
    static int ISchemaClass<CNmClipDocEventTrack>.Size => 40;
    static string? ISchemaClass<CNmClipDocEventTrack>.ClassName => null;


    public ref CUtlVector<PointerTo<CNmClipDocEvent>> Events { get; }

    public string EventClassName { get; set; }

    public ref CNmClipDocEventTrack__Type_t Type { get; }

    public ref bool IsSyncTrack { get; }

    public ref bool IsDisabled { get; }


}