// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocAnimationPoseNode__CData : CNmGraphDocVariationDataNode__CData, ISchemaClass<CNmGraphDocAnimationPoseNode__CData>
{
    static CNmGraphDocAnimationPoseNode__CData ISchemaClass<CNmGraphDocAnimationPoseNode__CData>.From(nint handle) => new CNmGraphDocAnimationPoseNode__CDataImpl(handle);
    static int ISchemaClass<CNmGraphDocAnimationPoseNode__CData>.Size => 24;
    static string? ISchemaClass<CNmGraphDocAnimationPoseNode__CData>.ClassName => null;


    public string Clip { get; set; }

    public ref float VariationTimeValue { get; }


}