// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CnmGraphDocTwoBoneIKNode__CData : CNmGraphDocVariationDataNode__CData, ISchemaClass<CnmGraphDocTwoBoneIKNode__CData>
{
    static CnmGraphDocTwoBoneIKNode__CData ISchemaClass<CnmGraphDocTwoBoneIKNode__CData>.From(nint handle) => new CnmGraphDocTwoBoneIKNode__CDataImpl(handle);
    static int ISchemaClass<CnmGraphDocTwoBoneIKNode__CData>.Size => 24;
    static string? ISchemaClass<CnmGraphDocTwoBoneIKNode__CData>.ClassName => null;


    public string EffectorBoneName { get; set; }

    public ref float BlendTimeSeconds { get; }


}