// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocBoneMaskNode__CData : CNmGraphDocVariationDataNode__CData, ISchemaClass<CNmGraphDocBoneMaskNode__CData>
{
    static CNmGraphDocBoneMaskNode__CData ISchemaClass<CNmGraphDocBoneMaskNode__CData>.From(nint handle) => new CNmGraphDocBoneMaskNode__CDataImpl(handle);
    static int ISchemaClass<CNmGraphDocBoneMaskNode__CData>.Size => 16;
    static string? ISchemaClass<CNmGraphDocBoneMaskNode__CData>.ClassName => null;


    public ref CGlobalSymbol OverrideMaskID { get; }


}