// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocVariationDataNode__CData : ISchemaClass<CNmGraphDocVariationDataNode__CData>
{
    static CNmGraphDocVariationDataNode__CData ISchemaClass<CNmGraphDocVariationDataNode__CData>.From(nint handle) => new CNmGraphDocVariationDataNode__CDataImpl(handle);
    static int ISchemaClass<CNmGraphDocVariationDataNode__CData>.Size => 8;
    static string? ISchemaClass<CNmGraphDocVariationDataNode__CData>.ClassName => null;

}