// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmGraphDocStateNode__TimedStateEvent_t : ISchemaClass<CNmGraphDocStateNode__TimedStateEvent_t>
{
    static CNmGraphDocStateNode__TimedStateEvent_t ISchemaClass<CNmGraphDocStateNode__TimedStateEvent_t>.From(nint handle) => new CNmGraphDocStateNode__TimedStateEvent_tImpl(handle);
    static int ISchemaClass<CNmGraphDocStateNode__TimedStateEvent_t>.Size => 24;
    static string? ISchemaClass<CNmGraphDocStateNode__TimedStateEvent_t>.ClassName => null;


    public ref CGlobalSymbol ID { get; }

    public ref CNmGraphDocStateNode__TimedStateEventType_t Type { get; }

    public ref CNmStateNode__TimedEvent_t__Comparison_t ComparisonOperator { get; }

    public ref float TimeValueSeconds { get; }


}