// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CNmSkeletonDocument__SecondarySkeleton_t : ISchemaClass<CNmSkeletonDocument__SecondarySkeleton_t>
{
    static CNmSkeletonDocument__SecondarySkeleton_t ISchemaClass<CNmSkeletonDocument__SecondarySkeleton_t>.From(nint handle) => new CNmSkeletonDocument__SecondarySkeleton_tImpl(handle);
    static int ISchemaClass<CNmSkeletonDocument__SecondarySkeleton_t>.Size => 16;
    static string? ISchemaClass<CNmSkeletonDocument__SecondarySkeleton_t>.ClassName => null;


    public string Skeleton { get; set; }

    public ref CGlobalSymbol AttachToBoneID { get; }


}