// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CompositeMaterialAssemblyProcedure_t : ISchemaClass<CompositeMaterialAssemblyProcedure_t>
{
    static CompositeMaterialAssemblyProcedure_t ISchemaClass<CompositeMaterialAssemblyProcedure_t>.From(nint handle) => new CompositeMaterialAssemblyProcedure_tImpl(handle);
    static int ISchemaClass<CompositeMaterialAssemblyProcedure_t>.Size => 96;
    static string? ISchemaClass<CompositeMaterialAssemblyProcedure_t>.ClassName => null;


    public ref CUtlVector<SchemaUntypedField> CompMatIncludes { get; }

    public ref CUtlVector<CompositeMaterialMatchFilter_t> MatchFilters { get; }

    public ref CUtlVector<CompositeMaterialInputContainer_t> CompositeInputContainers { get; }

    public ref CUtlVector<CompMatPropertyMutator_t> PropertyMutators { get; }


}