// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CompositeMaterialEditorPoint_t : ISchemaClass<CompositeMaterialEditorPoint_t>
{
    static CompositeMaterialEditorPoint_t ISchemaClass<CompositeMaterialEditorPoint_t>.From(nint handle) => new CompositeMaterialEditorPoint_tImpl(handle);
    static int ISchemaClass<CompositeMaterialEditorPoint_t>.Size => 536;
    static string? ISchemaClass<CompositeMaterialEditorPoint_t>.ClassName => null;


    // CResourceNameTyped< CWeakHandle< InfoForResourceTypeCModel > >
    public SchemaUntypedField ModelName { get; }

    public ref int SequenceIndex { get; }

    public ref float Cycle { get; }

    // KeyValues3
    public SchemaUntypedField KVModelStateChoices { get; }

    public ref bool EnableChildModel { get; }

    // CResourceNameTyped< CWeakHandle< InfoForResourceTypeCModel > >
    public SchemaUntypedField ChildModelName { get; }

    public ref CUtlVector<CompositeMaterialAssemblyProcedure_t> CompositeMaterialAssemblyProcedures { get; }

    public ref CUtlVector<CompositeMaterial_t> CompositeMaterials { get; }


}