// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CompositeMaterialMatchFilter_t : ISchemaClass<CompositeMaterialMatchFilter_t>
{
    static CompositeMaterialMatchFilter_t ISchemaClass<CompositeMaterialMatchFilter_t>.From(nint handle) => new CompositeMaterialMatchFilter_tImpl(handle);
    static int ISchemaClass<CompositeMaterialMatchFilter_t>.Size => 32;
    static string? ISchemaClass<CompositeMaterialMatchFilter_t>.ClassName => null;


    public ref CompositeMaterialMatchFilterType_t CompositeMaterialMatchFilterType { get; }

    public string StrMatchFilter { get; set; }

    public string StrMatchValue { get; set; }

    public ref bool PassWhenTrue { get; }


}