// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPreviewList : ISchemaClass<CPreviewList>
{
    static CPreviewList ISchemaClass<CPreviewList>.From(nint handle) => new CPreviewListImpl(handle);
    static int ISchemaClass<CPreviewList>.Size => 32;
    static string? ISchemaClass<CPreviewList>.ClassName => null;


    public ref CUtlVector<CPreviewEntry> Sounds { get; }

    public ref bool PreviewInGame { get; }


}