// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulse_InstructionDebug : ISchemaClass<CPulse_InstructionDebug>
{
    static CPulse_InstructionDebug ISchemaClass<CPulse_InstructionDebug>.From(nint handle) => new CPulse_InstructionDebugImpl(handle);
    static int ISchemaClass<CPulse_InstructionDebug>.Size => 24;
    static string? ISchemaClass<CPulse_InstructionDebug>.ClassName => null;


    public PulseDocNodeID_t FlowNodeID { get; }

    public PulseDocNodeID_t ValueNodeID { get; }

    // PulseSymbol_t
    public SchemaUntypedField SequencePointName { get; }


}