// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseStringlib : ISchemaClass<CPulseStringlib>
{
    static CPulseStringlib ISchemaClass<CPulseStringlib>.From(nint handle) => new CPulseStringlibImpl(handle);
    static int ISchemaClass<CPulseStringlib>.Size => 1;
    static string? ISchemaClass<CPulseStringlib>.ClassName => null;

}