// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_TestWaitWithAutoTracepoints : CPulseCell_BaseYieldingInflow, ISchemaClass<CPulseCell_TestWaitWithAutoTracepoints>
{
    static CPulseCell_TestWaitWithAutoTracepoints ISchemaClass<CPulseCell_TestWaitWithAutoTracepoints>.From(nint handle) => new CPulseCell_TestWaitWithAutoTracepointsImpl(handle);
    static int ISchemaClass<CPulseCell_TestWaitWithAutoTracepoints>.Size => 296;
    static string? ISchemaClass<CPulseCell_TestWaitWithAutoTracepoints>.ClassName => null;


    public string TracePrefix { get; set; }

    public CPulse_ResumePoint WakeResume { get; }


}