// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CPulseCell_Outflow_PlayDynamicVCD : CPulseCell_Outflow_PlayVCDBase, ISchemaClass<CPulseCell_Outflow_PlayDynamicVCD>
{
    static CPulseCell_Outflow_PlayDynamicVCD ISchemaClass<CPulseCell_Outflow_PlayDynamicVCD>.From(nint handle) => new CPulseCell_Outflow_PlayDynamicVCDImpl(handle);
    static int ISchemaClass<CPulseCell_Outflow_PlayDynamicVCD>.Size => 312;
    static string? ISchemaClass<CPulseCell_Outflow_PlayDynamicVCD>.ClassName => null;

}