// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CRigidBodyWeight : ISchemaClass<CRigidBodyWeight>
{
    static CRigidBodyWeight ISchemaClass<CRigidBodyWeight>.From(nint handle) => new CRigidBodyWeightImpl(handle);
    static int ISchemaClass<CRigidBodyWeight>.Size => 16;
    static string? ISchemaClass<CRigidBodyWeight>.ClassName => null;


    public string Name { get; set; }

    public ref float Weight { get; }


}