// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSlopeComponent : CAnimGraphDoc_Component, ISchemaClass<CSlopeComponent>
{
    static CSlopeComponent ISchemaClass<CSlopeComponent>.From(nint handle) => new CSlopeComponentImpl(handle);
    static int ISchemaClass<CSlopeComponent>.Size => 88;
    static string? ISchemaClass<CSlopeComponent>.ClassName => null;


    public ref float TraceDistance { get; }

    public AnimParamID SlopeAngleID { get; }

    public AnimParamID SlopeHeadingID { get; }

    public AnimParamID SlopeAngleSideID { get; }

    public AnimParamID SlopeAngleFrontID { get; }

    public AnimParamID SlopeNormalID { get; }

    public AnimParamID SlopeNormal_WorldSpaceID { get; }


}