// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSndBeatPatternManager : ISchemaClass<CSndBeatPatternManager>
{
    static CSndBeatPatternManager ISchemaClass<CSndBeatPatternManager>.From(nint handle) => new CSndBeatPatternManagerImpl(handle);
    static int ISchemaClass<CSndBeatPatternManager>.Size => 144;
    static string? ISchemaClass<CSndBeatPatternManager>.ClassName => null;


    public ref CUtlVector<CSndBeatPattern> Patterns { get; }

    public ref CUtlVector<CSndBeatTrack> ActiveTracks { get; }


}