// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSprayedDataPreset : ISchemaClass<CSprayedDataPreset>
{
    static CSprayedDataPreset ISchemaClass<CSprayedDataPreset>.From(nint handle) => new CSprayedDataPresetImpl(handle);
    static int ISchemaClass<CSprayedDataPreset>.Size => 48;
    static string? ISchemaClass<CSprayedDataPreset>.ClassName => null;


    public ref int CounterMin { get; }

    public ref int CounterMax { get; }

    public ref float Spacing { get; }

    public ref float Radius { get; }

    public ref float EraseAmount { get; }

    public ref bool ConstantDensity { get; }

    public ref bool OnlyHitMeshes { get; }

    public ref bool RadialFalloff { get; }

    public ref CUtlVector<CSprayedDataPresetElement> Elements { get; }


}