// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSteamAudioSceneData : ISchemaClass<CSteamAudioSceneData>
{
    static CSteamAudioSceneData ISchemaClass<CSteamAudioSceneData>.From(nint handle) => new CSteamAudioSceneDataImpl(handle);
    static int ISchemaClass<CSteamAudioSceneData>.Size => 16;
    static string? ISchemaClass<CSteamAudioSceneData>.ClassName => null;


    // IPLScene
    public SchemaUntypedField Scene { get; }

    // IPLStaticMesh
    public SchemaUntypedField StaticMesh { get; }


}