// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CSubassetTypeInfo : ISchemaClass<CSubassetTypeInfo>
{
    static CSubassetTypeInfo ISchemaClass<CSubassetTypeInfo>.From(nint handle) => new CSubassetTypeInfoImpl(handle);
    static int ISchemaClass<CSubassetTypeInfo>.Size => 16;
    static string? ISchemaClass<CSubassetTypeInfo>.ClassName => null;


    public ref bool FollowReferences { get; }

    public ref bool AllowDefinitions { get; }

    public ref bool AllowReferences { get; }


}