// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CTextureSheetDoc_SequenceDecalParams : ISchemaClass<CTextureSheetDoc_SequenceDecalParams>
{
    static CTextureSheetDoc_SequenceDecalParams ISchemaClass<CTextureSheetDoc_SequenceDecalParams>.From(nint handle) => new CTextureSheetDoc_SequenceDecalParamsImpl(handle);
    static int ISchemaClass<CTextureSheetDoc_SequenceDecalParams>.Size => 36;
    static string? ISchemaClass<CTextureSheetDoc_SequenceDecalParams>.ClassName => null;


    public ref float Scale { get; }

    public ref float Depth { get; }

    public ref float ScaleVariation { get; }

    public ref float StartFadeTime { get; }

    public ref float FadeDuration { get; }

    public ref float AnimationScale { get; }

    public ref float AnimationStartTime { get; }

    public ref float AlignWithGravityFactor { get; }

    public ref DecalRtEncoding_t DecalRtEncoding { get; }


}