// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CToneMappingLayer : CColorCorrectionLayer, ISchemaClass<CToneMappingLayer>
{
    static CToneMappingLayer ISchemaClass<CToneMappingLayer>.From(nint handle) => new CToneMappingLayerImpl(handle);
    static int ISchemaClass<CToneMappingLayer>.Size => 104;
    static string? ISchemaClass<CToneMappingLayer>.ClassName => null;


    public PostProcessingTonemapParameters_t Params { get; }


}