// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVibranceColorCorrectionLayer : CColorCorrectionLayer, ISchemaClass<CVibranceColorCorrectionLayer>
{
    static CVibranceColorCorrectionLayer ISchemaClass<CVibranceColorCorrectionLayer>.From(nint handle) => new CVibranceColorCorrectionLayerImpl(handle);
    static int ISchemaClass<CVibranceColorCorrectionLayer>.Size => 48;
    static string? ISchemaClass<CVibranceColorCorrectionLayer>.ClassName => null;


    public ref int Vibrance { get; }

    public ref int Saturation { get; }


}