// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVMixToolEditorData : ISchemaClass<CVMixToolEditorData>
{
    static CVMixToolEditorData ISchemaClass<CVMixToolEditorData>.From(nint handle) => new CVMixToolEditorDataImpl(handle);
    static int ISchemaClass<CVMixToolEditorData>.Size => 8;
    static string? ISchemaClass<CVMixToolEditorData>.ClassName => null;


    public ref int SelectedGraph { get; }

    public ref int SelectedEffectPreset { get; }


}