// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerAnalysisBase : ISchemaClass<CVoiceContainerAnalysisBase>
{
    static CVoiceContainerAnalysisBase ISchemaClass<CVoiceContainerAnalysisBase>.From(nint handle) => new CVoiceContainerAnalysisBaseImpl(handle);
    static int ISchemaClass<CVoiceContainerAnalysisBase>.Size => 72;
    static string? ISchemaClass<CVoiceContainerAnalysisBase>.ClassName => null;


    // CPiecewiseCurve
    public SchemaUntypedField Curve { get; }


}