// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface CVoiceContainerLoopTriggerWithRandomPanner : CVoiceContainerLoopTrigger, ISchemaClass<CVoiceContainerLoopTriggerWithRandomPanner>
{
    static CVoiceContainerLoopTriggerWithRandomPanner ISchemaClass<CVoiceContainerLoopTriggerWithRandomPanner>.From(nint handle) => new CVoiceContainerLoopTriggerWithRandomPannerImpl(handle);
    static int ISchemaClass<CVoiceContainerLoopTriggerWithRandomPanner>.Size => 192;
    static string? ISchemaClass<CVoiceContainerLoopTriggerWithRandomPanner>.ClassName => null;


    public CRandomPannerControls RandomPannerControls { get; }


}