// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface FeBoneMergeLink_t : ISchemaClass<FeBoneMergeLink_t>
{
    static FeBoneMergeLink_t ISchemaClass<FeBoneMergeLink_t>.From(nint handle) => new FeBoneMergeLink_tImpl(handle);
    static int ISchemaClass<FeBoneMergeLink_t>.Size => 8;
    static string? ISchemaClass<FeBoneMergeLink_t>.ClassName => null;


    public ref uint ParentHash { get; }

    public ref ushort ChildNode { get; }


}