// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface GeneratedTextureHandle_t : ISchemaClass<GeneratedTextureHandle_t>
{
    static GeneratedTextureHandle_t ISchemaClass<GeneratedTextureHandle_t>.From(nint handle) => new GeneratedTextureHandle_tImpl(handle);
    static int ISchemaClass<GeneratedTextureHandle_t>.Size => 96;
    static string? ISchemaClass<GeneratedTextureHandle_t>.ClassName => null;


    public string StrBitmapName { get; set; }


}