// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface globalentitydatabase_t : ISchemaClass<globalentitydatabase_t>
{
    static globalentitydatabase_t ISchemaClass<globalentitydatabase_t>.From(nint handle) => new globalentitydatabase_tImpl(handle);
    static int ISchemaClass<globalentitydatabase_t>.Size => 120;
    static string? ISchemaClass<globalentitydatabase_t>.ClassName => null;


    public ref CUtlVector<globalentity_t> List { get; }


}