// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface inv_image_clearcolor_t : ISchemaClass<inv_image_clearcolor_t>
{
    static inv_image_clearcolor_t ISchemaClass<inv_image_clearcolor_t>.From(nint handle) => new inv_image_clearcolor_tImpl(handle);
    static int ISchemaClass<inv_image_clearcolor_t>.Size => 12;
    static string? ISchemaClass<inv_image_clearcolor_t>.ClassName => null;


    public ref Vector Color { get; }


}