// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface screenfade_t : ISchemaClass<screenfade_t>
{
    static screenfade_t ISchemaClass<screenfade_t>.From(nint handle) => new screenfade_tImpl(handle);
    static int ISchemaClass<screenfade_t>.Size => 40;
    static string? ISchemaClass<screenfade_t>.ClassName => null;


    public ref float Speed { get; }

    public ref float End { get; }

    public ref float Reset { get; }

    public ref Color Color { get; }

    public ref int Flags { get; }


}