// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SpawnPoint_API : ISchemaClass<SpawnPoint_API>
{
    static SpawnPoint_API ISchemaClass<SpawnPoint_API>.From(nint handle) => new SpawnPoint_APIImpl(handle);
    static int ISchemaClass<SpawnPoint_API>.Size => 8;
    static string? ISchemaClass<SpawnPoint_API>.ClassName => null;

}