// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SteamAudioPathSettings_t : ISchemaClass<SteamAudioPathSettings_t>
{
    static SteamAudioPathSettings_t ISchemaClass<SteamAudioPathSettings_t>.From(nint handle) => new SteamAudioPathSettings_tImpl(handle);
    static int ISchemaClass<SteamAudioPathSettings_t>.Size => 16;
    static string? ISchemaClass<SteamAudioPathSettings_t>.ClassName => null;


    public ref int NumVisSamples { get; }

    public ref float ProbeVisRadius { get; }

    public ref float ProbeVisThreshold { get; }

    public ref float ProbePathRange { get; }


}