// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface SteamAudioCustomDataOcclusionSettings_t : ISchemaClass<SteamAudioCustomDataOcclusionSettings_t>
{
    static SteamAudioCustomDataOcclusionSettings_t ISchemaClass<SteamAudioCustomDataOcclusionSettings_t>.From(nint handle) => new SteamAudioCustomDataOcclusionSettings_tImpl(handle);
    static int ISchemaClass<SteamAudioCustomDataOcclusionSettings_t>.Size => 12;
    static string? ISchemaClass<SteamAudioCustomDataOcclusionSettings_t>.ClassName => null;


    public ref bool EnablePathing { get; }

    public ref bool EnableReflections { get; }

    public ref int ReflectionRays { get; }

    public ref int ReflectionBounces { get; }


}