// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.SchemaDefinitions;

namespace SwiftlyS2.Shared.SchemaDefinitions;

public partial interface TagStatus : ISchemaClass<TagStatus>
{
    static TagStatus ISchemaClass<TagStatus>.From(nint handle) => new TagStatusImpl(handle);
    static int ISchemaClass<TagStatus>.Size => 8;
    static string? ISchemaClass<TagStatus>.ClassName => null;


    public ref TagActionStatus TagStatus { get; }

    public ref float TagStartAnimTime { get; }


}