// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class ActorMapping_tImpl : SchemaClass, ActorMapping_t
{
    public ActorMapping_tImpl(nint handle) : base(handle) { }

    private static nint? _ActorNameOffset;

    public string ActorName
    {
        get
        {
            _ActorNameOffset = _ActorNameOffset ?? Schema.GetOffset(0x8CCE1717B76E7478);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ActorNameOffset!.Value));
        }
        set
        {
            _ActorNameOffset = _ActorNameOffset ?? Schema.GetOffset(0x8CCE1717B76E7478);
            Schema.SetCUtlString(_Handle, _ActorNameOffset!.Value, value);
        }
    }
    private static nint? _EntityOffset;

    public ref CHandle<CBaseEntity> Entity
    {
        get
        {
            _EntityOffset = _EntityOffset ?? Schema.GetOffset(0x8CCE17176EBADCB0);
            return ref _Handle.AsRef<CHandle<CBaseEntity>>(_EntityOffset!.Value);
        }
    }

}