// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class AI_Navigator_DebugSnapshotData_tImpl : SchemaClass, AI_Navigator_DebugSnapshotData_t
{
    public AI_Navigator_DebugSnapshotData_tImpl(nint handle) : base(handle) { }

    private static nint? _S_movement_idOffset;

    public ref CGlobalSymbol S_movement_id
    {
        get
        {
            _S_movement_idOffset = _S_movement_idOffset ?? Schema.GetOffset(0x48159FC62DEAD6BE);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_movement_idOffset!.Value);
        }
    }
    private static nint? _S_movement_serial_numberOffset;

    public ref uint S_movement_serial_number
    {
        get
        {
            _S_movement_serial_numberOffset = _S_movement_serial_numberOffset ?? Schema.GetOffset(0x48159FC6B552A149);
            return ref _Handle.AsRef<uint>(_S_movement_serial_numberOffset!.Value);
        }
    }
    private static nint? _S_goal_source_locationOffset;

    public string S_goal_source_location
    {
        get
        {
            _S_goal_source_locationOffset = _S_goal_source_locationOffset ?? Schema.GetOffset(0x48159FC660679B76);
            return Schema.GetCUtlString(_Handle.Read<nint>(_S_goal_source_locationOffset!.Value));
        }
        set
        {
            _S_goal_source_locationOffset = _S_goal_source_locationOffset ?? Schema.GetOffset(0x48159FC660679B76);
            Schema.SetCUtlString(_Handle, _S_goal_source_locationOffset!.Value, value);
        }
    }
    private static nint? _Last_waypoint_posOffset;

    public ref Vector Last_waypoint_pos
    {
        get
        {
            _Last_waypoint_posOffset = _Last_waypoint_posOffset ?? Schema.GetOffset(0x48159FC621F16944);
            return ref _Handle.AsRef<Vector>(_Last_waypoint_posOffset!.Value);
        }
    }
    private static nint? _Goal_locationOffset;

    public ref Vector Goal_location
    {
        get
        {
            _Goal_locationOffset = _Goal_locationOffset ?? Schema.GetOffset(0x48159FC69DA1E84C);
            return ref _Handle.AsRef<Vector>(_Goal_locationOffset!.Value);
        }
    }
    private static nint? _WaypointsOffset;

    public ref CUtlVector<AI_Navigator_DebugSnapshotData_t__Waypoint_t> Waypoints
    {
        get
        {
            _WaypointsOffset = _WaypointsOffset ?? Schema.GetOffset(0x48159FC67A0ABB2B);
            return ref _Handle.AsRef<CUtlVector<AI_Navigator_DebugSnapshotData_t__Waypoint_t>>(_WaypointsOffset!.Value);
        }
    }
    private static nint? _S_arrival_movement_gait_setOffset;

    public ref CGlobalSymbol S_arrival_movement_gait_set
    {
        get
        {
            _S_arrival_movement_gait_setOffset = _S_arrival_movement_gait_setOffset ?? Schema.GetOffset(0x48159FC6F533C81F);
            return ref _Handle.AsRef<CGlobalSymbol>(_S_arrival_movement_gait_setOffset!.Value);
        }
    }

}