// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_BaseButtonImpl : C_BaseToggleImpl, C_BaseButton
{
    public C_BaseButtonImpl(nint handle) : base(handle) { }

    private static nint? _GlowEntityOffset;

    public ref CHandle<C_BaseModelEntity> GlowEntity
    {
        get
        {
            _GlowEntityOffset = _GlowEntityOffset ?? Schema.GetOffset(0xCD6BF32235C883E7);
            return ref _Handle.AsRef<CHandle<C_BaseModelEntity>>(_GlowEntityOffset!.Value);
        }
    }
    private static nint? _UsableOffset;

    public ref bool Usable
    {
        get
        {
            _UsableOffset = _UsableOffset ?? Schema.GetOffset(0xCD6BF32244B8E369);
            return ref _Handle.AsRef<bool>(_UsableOffset!.Value);
        }
    }
    private static nint? _DisplayTextOffset;

    public string DisplayText
    {
        get
        {
            _DisplayTextOffset = _DisplayTextOffset ?? Schema.GetOffset(0xCD6BF322DE5320C5);
            return Schema.GetString(_Handle.Read<nint>(_DisplayTextOffset!.Value));
        }
        set
        {
            _DisplayTextOffset = _DisplayTextOffset ?? Schema.GetOffset(0xCD6BF322DE5320C5);
            Schema.SetString(_Handle, _DisplayTextOffset!.Value, value);
        }
    }

}