// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_BaseClientUIEntityImpl : C_BaseModelEntityImpl, C_BaseClientUIEntity
{
    public C_BaseClientUIEntityImpl(nint handle) : base(handle) { }

    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0x6695E9D06154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _DialogXMLNameOffset;

    public string DialogXMLName
    {
        get
        {
            _DialogXMLNameOffset = _DialogXMLNameOffset ?? Schema.GetOffset(0x6695E9D0D13858C9);
            return Schema.GetString(_Handle.Read<nint>(_DialogXMLNameOffset!.Value));
        }
        set
        {
            _DialogXMLNameOffset = _DialogXMLNameOffset ?? Schema.GetOffset(0x6695E9D0D13858C9);
            Schema.SetString(_Handle, _DialogXMLNameOffset!.Value, value);
        }
    }
    private static nint? _PanelClassNameOffset;

    public string PanelClassName
    {
        get
        {
            _PanelClassNameOffset = _PanelClassNameOffset ?? Schema.GetOffset(0x6695E9D05C958CBC);
            return Schema.GetString(_Handle.Read<nint>(_PanelClassNameOffset!.Value));
        }
        set
        {
            _PanelClassNameOffset = _PanelClassNameOffset ?? Schema.GetOffset(0x6695E9D05C958CBC);
            Schema.SetString(_Handle, _PanelClassNameOffset!.Value, value);
        }
    }
    private static nint? _PanelIDOffset;

    public string PanelID
    {
        get
        {
            _PanelIDOffset = _PanelIDOffset ?? Schema.GetOffset(0x6695E9D007A4EF60);
            return Schema.GetString(_Handle.Read<nint>(_PanelIDOffset!.Value));
        }
        set
        {
            _PanelIDOffset = _PanelIDOffset ?? Schema.GetOffset(0x6695E9D007A4EF60);
            Schema.SetString(_Handle, _PanelIDOffset!.Value, value);
        }
    }

}