// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_BreakablePropImpl : CBasePropImpl, C_BreakableProp
{
    public C_BreakablePropImpl(nint handle) : base(handle) { }

    private static nint? _CPropDataComponentOffset;
    private CPropDataComponentImpl? _CPropDataComponentInstance;

    public CPropDataComponent CPropDataComponent
    {
        get
        {
            _CPropDataComponentOffset = _CPropDataComponentOffset ?? Schema.GetOffset(0x6A873A3FACBC1DDE);
            var instance = _CPropDataComponentInstance ??= new CPropDataComponentImpl(0);
            instance.DangerousSetHandle(_Handle + _CPropDataComponentOffset!.Value);
            return instance;
        }
    }
    private static nint? _OnStartDeathOffset;

    public ref CEntityIOOutput OnStartDeath
    {
        get
        {
            _OnStartDeathOffset = _OnStartDeathOffset ?? Schema.GetOffset(0x6A873A3FF3ED4C8E);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnStartDeathOffset!.Value);
        }
    }
    private static nint? _OnBreakOffset;

    public ref CEntityIOOutput OnBreak
    {
        get
        {
            _OnBreakOffset = _OnBreakOffset ?? Schema.GetOffset(0x6A873A3F46BFEC4F);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnBreakOffset!.Value);
        }
    }
    private static nint? _OnHealthChangedOffset;
    private SchemaUntypedField? _OnHealthChangedInstance;

    public SchemaUntypedField OnHealthChanged
    {
        get
        {
            _OnHealthChangedOffset = _OnHealthChangedOffset ?? Schema.GetOffset(0x6A873A3FEAC125B2);
            var instance = _OnHealthChangedInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OnHealthChangedOffset!.Value);
            return instance;
        }
    }
    private static nint? _OnTakeDamageOffset;

    public ref CEntityIOOutput OnTakeDamage
    {
        get
        {
            _OnTakeDamageOffset = _OnTakeDamageOffset ?? Schema.GetOffset(0x6A873A3FCC9E35D2);
            return ref _Handle.AsRef<CEntityIOOutput>(_OnTakeDamageOffset!.Value);
        }
    }
    private static nint? _ImpactEnergyScaleOffset;

    public ref float ImpactEnergyScale
    {
        get
        {
            _ImpactEnergyScaleOffset = _ImpactEnergyScaleOffset ?? Schema.GetOffset(0x6A873A3FC66BAC1B);
            return ref _Handle.AsRef<float>(_ImpactEnergyScaleOffset!.Value);
        }
    }
    private static nint? _MinHealthDmgOffset;

    public ref int MinHealthDmg
    {
        get
        {
            _MinHealthDmgOffset = _MinHealthDmgOffset ?? Schema.GetOffset(0x6A873A3F91F14A4A);
            return ref _Handle.AsRef<int>(_MinHealthDmgOffset!.Value);
        }
    }
    private static nint? _PressureDelayOffset;

    public ref float PressureDelay
    {
        get
        {
            _PressureDelayOffset = _PressureDelayOffset ?? Schema.GetOffset(0x6A873A3F4852270B);
            return ref _Handle.AsRef<float>(_PressureDelayOffset!.Value);
        }
    }
    private static nint? _DefBurstScaleOffset;

    public ref float DefBurstScale
    {
        get
        {
            _DefBurstScaleOffset = _DefBurstScaleOffset ?? Schema.GetOffset(0x6A873A3F8D3953C6);
            return ref _Handle.AsRef<float>(_DefBurstScaleOffset!.Value);
        }
    }
    private static nint? _DefBurstOffsetOffset;

    public ref Vector DefBurstOffset
    {
        get
        {
            _DefBurstOffsetOffset = _DefBurstOffsetOffset ?? Schema.GetOffset(0x6A873A3F1E951FF1);
            return ref _Handle.AsRef<Vector>(_DefBurstOffsetOffset!.Value);
        }
    }
    private static nint? _BreakerOffset;

    public ref CHandle<C_BaseEntity> Breaker
    {
        get
        {
            _BreakerOffset = _BreakerOffset ?? Schema.GetOffset(0x6A873A3F161604FD);
            return ref _Handle.AsRef<CHandle<C_BaseEntity>>(_BreakerOffset!.Value);
        }
    }
    private static nint? _PerformanceModeOffset;

    public ref PerformanceMode_t PerformanceMode
    {
        get
        {
            _PerformanceModeOffset = _PerformanceModeOffset ?? Schema.GetOffset(0x6A873A3FC12B4C52);
            return ref _Handle.AsRef<PerformanceMode_t>(_PerformanceModeOffset!.Value);
        }
    }
    private static nint? _PreventDamageBeforeTimeOffset;
    private GameTime_tImpl? _PreventDamageBeforeTimeInstance;

    public GameTime_t PreventDamageBeforeTime
    {
        get
        {
            _PreventDamageBeforeTimeOffset = _PreventDamageBeforeTimeOffset ?? Schema.GetOffset(0x6A873A3F431B46E8);
            var instance = _PreventDamageBeforeTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _PreventDamageBeforeTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _BreakableContentsTypeOffset;

    public ref BreakableContentsType_t BreakableContentsType
    {
        get
        {
            _BreakableContentsTypeOffset = _BreakableContentsTypeOffset ?? Schema.GetOffset(0x6A873A3FC332D3A2);
            return ref _Handle.AsRef<BreakableContentsType_t>(_BreakableContentsTypeOffset!.Value);
        }
    }
    private static nint? _StrBreakableContentsPropGroupOverrideOffset;

    public string StrBreakableContentsPropGroupOverride
    {
        get
        {
            _StrBreakableContentsPropGroupOverrideOffset = _StrBreakableContentsPropGroupOverrideOffset ?? Schema.GetOffset(0x6A873A3FFEDC11AB);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrBreakableContentsPropGroupOverrideOffset!.Value));
        }
        set
        {
            _StrBreakableContentsPropGroupOverrideOffset = _StrBreakableContentsPropGroupOverrideOffset ?? Schema.GetOffset(0x6A873A3FFEDC11AB);
            Schema.SetCUtlString(_Handle, _StrBreakableContentsPropGroupOverrideOffset!.Value, value);
        }
    }
    private static nint? _StrBreakableContentsParticleOverrideOffset;

    public string StrBreakableContentsParticleOverride
    {
        get
        {
            _StrBreakableContentsParticleOverrideOffset = _StrBreakableContentsParticleOverrideOffset ?? Schema.GetOffset(0x6A873A3F61C07367);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrBreakableContentsParticleOverrideOffset!.Value));
        }
        set
        {
            _StrBreakableContentsParticleOverrideOffset = _StrBreakableContentsParticleOverrideOffset ?? Schema.GetOffset(0x6A873A3F61C07367);
            Schema.SetCUtlString(_Handle, _StrBreakableContentsParticleOverrideOffset!.Value, value);
        }
    }
    private static nint? _HasBreakPiecesOrCommandsOffset;

    public ref bool HasBreakPiecesOrCommands
    {
        get
        {
            _HasBreakPiecesOrCommandsOffset = _HasBreakPiecesOrCommandsOffset ?? Schema.GetOffset(0x6A873A3F8BD56C36);
            return ref _Handle.AsRef<bool>(_HasBreakPiecesOrCommandsOffset!.Value);
        }
    }
    private static nint? _ExplodeDamageOffset;

    public ref float ExplodeDamage
    {
        get
        {
            _ExplodeDamageOffset = _ExplodeDamageOffset ?? Schema.GetOffset(0x6A873A3FEADCF523);
            return ref _Handle.AsRef<float>(_ExplodeDamageOffset!.Value);
        }
    }
    private static nint? _ExplodeRadiusOffset;

    public ref float ExplodeRadius
    {
        get
        {
            _ExplodeRadiusOffset = _ExplodeRadiusOffset ?? Schema.GetOffset(0x6A873A3F229BEC64);
            return ref _Handle.AsRef<float>(_ExplodeRadiusOffset!.Value);
        }
    }
    private static nint? _ExplosionTypeOffset;

    public ref CGlobalSymbol ExplosionType
    {
        get
        {
            _ExplosionTypeOffset = _ExplosionTypeOffset ?? Schema.GetOffset(0x6A873A3F4867BD6D);
            return ref _Handle.AsRef<CGlobalSymbol>(_ExplosionTypeOffset!.Value);
        }
    }
    private static nint? _ExplosionDelayOffset;

    public ref float ExplosionDelay
    {
        get
        {
            _ExplosionDelayOffset = _ExplosionDelayOffset ?? Schema.GetOffset(0x6A873A3F9DB4A86F);
            return ref _Handle.AsRef<float>(_ExplosionDelayOffset!.Value);
        }
    }
    private static nint? _ExplosionBuildupSoundOffset;

    public string ExplosionBuildupSound
    {
        get
        {
            _ExplosionBuildupSoundOffset = _ExplosionBuildupSoundOffset ?? Schema.GetOffset(0x6A873A3F835ABA6C);
            return Schema.GetString(_Handle.Read<nint>(_ExplosionBuildupSoundOffset!.Value));
        }
        set
        {
            _ExplosionBuildupSoundOffset = _ExplosionBuildupSoundOffset ?? Schema.GetOffset(0x6A873A3F835ABA6C);
            Schema.SetString(_Handle, _ExplosionBuildupSoundOffset!.Value, value);
        }
    }
    private static nint? _ExplosionCustomEffectOffset;

    public string ExplosionCustomEffect
    {
        get
        {
            _ExplosionCustomEffectOffset = _ExplosionCustomEffectOffset ?? Schema.GetOffset(0x6A873A3FBC8BEFBE);
            return Schema.GetString(_Handle.Read<nint>(_ExplosionCustomEffectOffset!.Value));
        }
        set
        {
            _ExplosionCustomEffectOffset = _ExplosionCustomEffectOffset ?? Schema.GetOffset(0x6A873A3FBC8BEFBE);
            Schema.SetString(_Handle, _ExplosionCustomEffectOffset!.Value, value);
        }
    }
    private static nint? _ExplosionCustomSoundOffset;

    public string ExplosionCustomSound
    {
        get
        {
            _ExplosionCustomSoundOffset = _ExplosionCustomSoundOffset ?? Schema.GetOffset(0x6A873A3FE729842A);
            return Schema.GetString(_Handle.Read<nint>(_ExplosionCustomSoundOffset!.Value));
        }
        set
        {
            _ExplosionCustomSoundOffset = _ExplosionCustomSoundOffset ?? Schema.GetOffset(0x6A873A3FE729842A);
            Schema.SetString(_Handle, _ExplosionCustomSoundOffset!.Value, value);
        }
    }
    private static nint? _ExplosionModifierOffset;

    public string ExplosionModifier
    {
        get
        {
            _ExplosionModifierOffset = _ExplosionModifierOffset ?? Schema.GetOffset(0x6A873A3F531D2849);
            return Schema.GetString(_Handle.Read<nint>(_ExplosionModifierOffset!.Value));
        }
        set
        {
            _ExplosionModifierOffset = _ExplosionModifierOffset ?? Schema.GetOffset(0x6A873A3F531D2849);
            Schema.SetString(_Handle, _ExplosionModifierOffset!.Value, value);
        }
    }
    private static nint? _PhysicsAttackerOffset;

    public ref CHandle<C_BasePlayerPawn> PhysicsAttacker
    {
        get
        {
            _PhysicsAttackerOffset = _PhysicsAttackerOffset ?? Schema.GetOffset(0x6A873A3F7A5EB877);
            return ref _Handle.AsRef<CHandle<C_BasePlayerPawn>>(_PhysicsAttackerOffset!.Value);
        }
    }
    private static nint? _LastPhysicsInfluenceTimeOffset;
    private GameTime_tImpl? _LastPhysicsInfluenceTimeInstance;

    public GameTime_t LastPhysicsInfluenceTime
    {
        get
        {
            _LastPhysicsInfluenceTimeOffset = _LastPhysicsInfluenceTimeOffset ?? Schema.GetOffset(0x6A873A3F5B5C0E32);
            var instance = _LastPhysicsInfluenceTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _LastPhysicsInfluenceTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _DefaultFadeScaleOffset;

    public ref float DefaultFadeScale
    {
        get
        {
            _DefaultFadeScaleOffset = _DefaultFadeScaleOffset ?? Schema.GetOffset(0x6A873A3F4DA9700C);
            return ref _Handle.AsRef<float>(_DefaultFadeScaleOffset!.Value);
        }
    }
    private static nint? _LastAttackerOffset;

    public ref CHandle<C_BaseEntity> LastAttacker
    {
        get
        {
            _LastAttackerOffset = _LastAttackerOffset ?? Schema.GetOffset(0x6A873A3F65CAEF84);
            return ref _Handle.AsRef<CHandle<C_BaseEntity>>(_LastAttackerOffset!.Value);
        }
    }

}