// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_ColorCorrectionVolumeImpl : C_BaseTriggerImpl, C_ColorCorrectionVolume
{
    public C_ColorCorrectionVolumeImpl(nint handle) : base(handle) { }

    private static nint? _LastEnterWeightOffset;

    public ref float LastEnterWeight
    {
        get
        {
            _LastEnterWeightOffset = _LastEnterWeightOffset ?? Schema.GetOffset(0xF61E5F042F53D64D);
            return ref _Handle.AsRef<float>(_LastEnterWeightOffset!.Value);
        }
    }
    private static nint? _LastEnterTimeOffset;
    private GameTime_tImpl? _LastEnterTimeInstance;

    public GameTime_t LastEnterTime
    {
        get
        {
            _LastEnterTimeOffset = _LastEnterTimeOffset ?? Schema.GetOffset(0xF61E5F0401977F10);
            var instance = _LastEnterTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _LastEnterTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _LastExitWeightOffset;

    public ref float LastExitWeight
    {
        get
        {
            _LastExitWeightOffset = _LastExitWeightOffset ?? Schema.GetOffset(0xF61E5F0459C9642D);
            return ref _Handle.AsRef<float>(_LastExitWeightOffset!.Value);
        }
    }
    private static nint? _LastExitTimeOffset;
    private GameTime_tImpl? _LastExitTimeInstance;

    public GameTime_t LastExitTime
    {
        get
        {
            _LastExitTimeOffset = _LastExitTimeOffset ?? Schema.GetOffset(0xF61E5F04183C8DF0);
            var instance = _LastExitTimeInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _LastExitTimeOffset!.Value);
            return instance;
        }
    }
    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0xF61E5F046154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _MaxWeightOffset;

    public ref float MaxWeight
    {
        get
        {
            _MaxWeightOffset = _MaxWeightOffset ?? Schema.GetOffset(0xF61E5F04EE8A2F2D);
            return ref _Handle.AsRef<float>(_MaxWeightOffset!.Value);
        }
    }
    private static nint? _FadeDurationOffset;

    public ref float FadeDuration
    {
        get
        {
            _FadeDurationOffset = _FadeDurationOffset ?? Schema.GetOffset(0xF61E5F0446550027);
            return ref _Handle.AsRef<float>(_FadeDurationOffset!.Value);
        }
    }
    private static nint? _WeightOffset;

    public ref float Weight
    {
        get
        {
            _WeightOffset = _WeightOffset ?? Schema.GetOffset(0xF61E5F04BF415739);
            return ref _Handle.AsRef<float>(_WeightOffset!.Value);
        }
    }
    private static nint? _LookupFilenameOffset;

    public string LookupFilename
    {
        get
        {
            _LookupFilenameOffset = _LookupFilenameOffset ?? Schema.GetOffset(0xF61E5F042611A2C6);
            return Schema.GetString(_Handle + _LookupFilenameOffset!.Value);
        }
        set
        {
            _LookupFilenameOffset = _LookupFilenameOffset ?? Schema.GetOffset(0xF61E5F042611A2C6);
            Schema.SetFixedString(_Handle, _LookupFilenameOffset!.Value, value, 512);
        }
    }

}