// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_CSPlayerResourceImpl : C_BaseEntityImpl, C_CSPlayerResource
{
    public C_CSPlayerResourceImpl(nint handle) : base(handle) { }

    private static nint? _HostageAliveOffset;
    private SchemaFixedArray<bool>? _HostageAliveInstance;

    public ISchemaFixedArray<bool> HostageAlive
    {
        get
        {
            _HostageAliveOffset = _HostageAliveOffset ?? Schema.GetOffset(0xF034A77C4C5B2E7F);
            var instance = _HostageAliveInstance ??= new SchemaFixedArray<bool>(0, 0xF034A77C4C5B2E7F, 12, 1, 1);
            instance.DangerousSetHandle(_Handle + _HostageAliveOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsHostageFollowingSomeoneOffset;
    private SchemaFixedArray<bool>? _IsHostageFollowingSomeoneInstance;

    public ISchemaFixedArray<bool> IsHostageFollowingSomeone
    {
        get
        {
            _IsHostageFollowingSomeoneOffset = _IsHostageFollowingSomeoneOffset ?? Schema.GetOffset(0xF034A77C3F8AA9BB);
            var instance = _IsHostageFollowingSomeoneInstance ??= new SchemaFixedArray<bool>(0, 0xF034A77C3F8AA9BB, 12, 1, 1);
            instance.DangerousSetHandle(_Handle + _IsHostageFollowingSomeoneOffset!.Value);
            return instance;
        }
    }
    private static nint? _HostageEntityIDsOffset;
    private SchemaFixedArray<uint>? _HostageEntityIDsInstance;

    public ISchemaFixedArray<uint> HostageEntityIDs
    {
        get
        {
            _HostageEntityIDsOffset = _HostageEntityIDsOffset ?? Schema.GetOffset(0xF034A77C0EEFA350);
            var instance = _HostageEntityIDsInstance ??= new SchemaFixedArray<uint>(0, 0xF034A77C0EEFA350, 12, 4, 4);
            instance.DangerousSetHandle(_Handle + _HostageEntityIDsOffset!.Value);
            return instance;
        }
    }
    private static nint? _BombsiteCenterAOffset;

    public ref Vector BombsiteCenterA
    {
        get
        {
            _BombsiteCenterAOffset = _BombsiteCenterAOffset ?? Schema.GetOffset(0xF034A77CA11A73BA);
            return ref _Handle.AsRef<Vector>(_BombsiteCenterAOffset!.Value);
        }
    }
    private static nint? _BombsiteCenterBOffset;

    public ref Vector BombsiteCenterB
    {
        get
        {
            _BombsiteCenterBOffset = _BombsiteCenterBOffset ?? Schema.GetOffset(0xF034A77CA01A7227);
            return ref _Handle.AsRef<Vector>(_BombsiteCenterBOffset!.Value);
        }
    }
    private static nint? _HostageRescueXOffset;
    private SchemaFixedArray<int>? _HostageRescueXInstance;

    public ISchemaFixedArray<int> HostageRescueX
    {
        get
        {
            _HostageRescueXOffset = _HostageRescueXOffset ?? Schema.GetOffset(0xF034A77C84FE2109);
            var instance = _HostageRescueXInstance ??= new SchemaFixedArray<int>(0, 0xF034A77C84FE2109, 4, 4, 4);
            instance.DangerousSetHandle(_Handle + _HostageRescueXOffset!.Value);
            return instance;
        }
    }
    private static nint? _HostageRescueYOffset;
    private SchemaFixedArray<int>? _HostageRescueYInstance;

    public ISchemaFixedArray<int> HostageRescueY
    {
        get
        {
            _HostageRescueYOffset = _HostageRescueYOffset ?? Schema.GetOffset(0xF034A77C83FE1F76);
            var instance = _HostageRescueYInstance ??= new SchemaFixedArray<int>(0, 0xF034A77C83FE1F76, 4, 4, 4);
            instance.DangerousSetHandle(_Handle + _HostageRescueYOffset!.Value);
            return instance;
        }
    }
    private static nint? _HostageRescueZOffset;
    private SchemaFixedArray<int>? _HostageRescueZInstance;

    public ISchemaFixedArray<int> HostageRescueZ
    {
        get
        {
            _HostageRescueZOffset = _HostageRescueZOffset ?? Schema.GetOffset(0xF034A77C82FE1DE3);
            var instance = _HostageRescueZInstance ??= new SchemaFixedArray<int>(0, 0xF034A77C82FE1DE3, 4, 4, 4);
            instance.DangerousSetHandle(_Handle + _HostageRescueZOffset!.Value);
            return instance;
        }
    }
    private static nint? _EndMatchNextMapAllVotedOffset;

    public ref bool EndMatchNextMapAllVoted
    {
        get
        {
            _EndMatchNextMapAllVotedOffset = _EndMatchNextMapAllVotedOffset ?? Schema.GetOffset(0xF034A77CE1946791);
            return ref _Handle.AsRef<bool>(_EndMatchNextMapAllVotedOffset!.Value);
        }
    }
    private static nint? _FoundGoalPositionsOffset;

    public ref bool FoundGoalPositions
    {
        get
        {
            _FoundGoalPositionsOffset = _FoundGoalPositionsOffset ?? Schema.GetOffset(0xF034A77CA90F0670);
            return ref _Handle.AsRef<bool>(_FoundGoalPositionsOffset!.Value);
        }
    }

}