// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_CsmFovOverrideImpl : C_BaseEntityImpl, C_CsmFovOverride
{
    public C_CsmFovOverrideImpl(nint handle) : base(handle) { }

    private static nint? _CameraNameOffset;

    public string CameraName
    {
        get
        {
            _CameraNameOffset = _CameraNameOffset ?? Schema.GetOffset(0x3E65115B6461442D);
            return Schema.GetCUtlString(_Handle.Read<nint>(_CameraNameOffset!.Value));
        }
        set
        {
            _CameraNameOffset = _CameraNameOffset ?? Schema.GetOffset(0x3E65115B6461442D);
            Schema.SetCUtlString(_Handle, _CameraNameOffset!.Value, value);
        }
    }
    private static nint? _CsmFovOverrideValueOffset;

    public ref float CsmFovOverrideValue
    {
        get
        {
            _CsmFovOverrideValueOffset = _CsmFovOverrideValueOffset ?? Schema.GetOffset(0x3E65115BE5932D70);
            return ref _Handle.AsRef<float>(_CsmFovOverrideValueOffset!.Value);
        }
    }

}