// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_CSGO_TeamPreviewCameraImpl : C_CSGO_MapPreviewCameraPathImpl, C_CSGO_TeamPreviewCamera
{
    public C_CSGO_TeamPreviewCameraImpl(nint handle) : base(handle) { }

    private static nint? _VariantOffset;

    public ref int Variant
    {
        get
        {
            _VariantOffset = _VariantOffset ?? Schema.GetOffset(0x8EC5BA78B2DB2B42);
            return ref _Handle.AsRef<int>(_VariantOffset!.Value);
        }
    }

}