// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volumeImpl : C_EnvCombinedLightProbeVolumeImpl, C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volume
{
    public C_EnvCombinedLightProbeVolumeAlias_func_combined_light_probe_volumeImpl(nint handle) : base(handle) { }

}