// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_EnvDecalImpl : C_BaseModelEntityImpl, C_EnvDecal
{
    public C_EnvDecalImpl(nint handle) : base(handle) { }

    private static nint? _DecalMaterialOffset;

    public ref CStrongHandle<InfoForResourceTypeIMaterial2> DecalMaterial
    {
        get
        {
            _DecalMaterialOffset = _DecalMaterialOffset ?? Schema.GetOffset(0x38BDE927D892BA39);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIMaterial2>>(_DecalMaterialOffset!.Value);
        }
    }
    private static nint? _WidthOffset;

    public ref float Width
    {
        get
        {
            _WidthOffset = _WidthOffset ?? Schema.GetOffset(0x38BDE927B91935E1);
            return ref _Handle.AsRef<float>(_WidthOffset!.Value);
        }
    }
    private static nint? _HeightOffset;

    public ref float Height
    {
        get
        {
            _HeightOffset = _HeightOffset ?? Schema.GetOffset(0x38BDE927EADD7FB0);
            return ref _Handle.AsRef<float>(_HeightOffset!.Value);
        }
    }
    private static nint? _DepthOffset;

    public ref float Depth
    {
        get
        {
            _DepthOffset = _DepthOffset ?? Schema.GetOffset(0x38BDE927D3AD54E8);
            return ref _Handle.AsRef<float>(_DepthOffset!.Value);
        }
    }
    private static nint? _RenderOrderOffset;

    public ref uint RenderOrder
    {
        get
        {
            _RenderOrderOffset = _RenderOrderOffset ?? Schema.GetOffset(0x38BDE927554E763B);
            return ref _Handle.AsRef<uint>(_RenderOrderOffset!.Value);
        }
    }
    private static nint? _ProjectOnWorldOffset;

    public ref bool ProjectOnWorld
    {
        get
        {
            _ProjectOnWorldOffset = _ProjectOnWorldOffset ?? Schema.GetOffset(0x38BDE927213B0285);
            return ref _Handle.AsRef<bool>(_ProjectOnWorldOffset!.Value);
        }
    }
    private static nint? _ProjectOnCharactersOffset;

    public ref bool ProjectOnCharacters
    {
        get
        {
            _ProjectOnCharactersOffset = _ProjectOnCharactersOffset ?? Schema.GetOffset(0x38BDE927E0371FB7);
            return ref _Handle.AsRef<bool>(_ProjectOnCharactersOffset!.Value);
        }
    }
    private static nint? _ProjectOnWaterOffset;

    public ref bool ProjectOnWater
    {
        get
        {
            _ProjectOnWaterOffset = _ProjectOnWaterOffset ?? Schema.GetOffset(0x38BDE927D4AF2E96);
            return ref _Handle.AsRef<bool>(_ProjectOnWaterOffset!.Value);
        }
    }
    private static nint? _DepthSortBiasOffset;

    public ref float DepthSortBias
    {
        get
        {
            _DepthSortBiasOffset = _DepthSortBiasOffset ?? Schema.GetOffset(0x38BDE927D8EE79D9);
            return ref _Handle.AsRef<float>(_DepthSortBiasOffset!.Value);
        }
    }

}