// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_FuncTrackTrainImpl : C_BaseModelEntityImpl, C_FuncTrackTrain
{
    public C_FuncTrackTrainImpl(nint handle) : base(handle) { }

    private static nint? _LongAxisOffset;

    public ref int LongAxis
    {
        get
        {
            _LongAxisOffset = _LongAxisOffset ?? Schema.GetOffset(0x5640726DE6D8F0A);
            return ref _Handle.AsRef<int>(_LongAxisOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x56407265ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _LineLengthOffset;

    public ref float LineLength
    {
        get
        {
            _LineLengthOffset = _LineLengthOffset ?? Schema.GetOffset(0x564072608A049AD);
            return ref _Handle.AsRef<float>(_LineLengthOffset!.Value);
        }
    }

}