// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_LocalTempEntityImpl : CBaseAnimGraphImpl, C_LocalTempEntity
{
    public C_LocalTempEntityImpl(nint handle) : base(handle) { }

    private static nint? _FlagsOffset;

    public ref int Flags
    {
        get
        {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x3D70697F9C677A2C);
            return ref _Handle.AsRef<int>(_FlagsOffset!.Value);
        }
    }
    private static nint? _DieOffset;
    private GameTime_tImpl? _DieInstance;

    public GameTime_t Die
    {
        get
        {
            _DieOffset = _DieOffset ?? Schema.GetOffset(0x3D70697FD86296D1);
            var instance = _DieInstance ??= new GameTime_tImpl(0);
            instance.DangerousSetHandle(_Handle + _DieOffset!.Value);
            return instance;
        }
    }
    private static nint? _FrameMaxOffset;

    public ref float FrameMax
    {
        get
        {
            _FrameMaxOffset = _FrameMaxOffset ?? Schema.GetOffset(0x3D70697FD39C85E2);
            return ref _Handle.AsRef<float>(_FrameMaxOffset!.Value);
        }
    }
    private static nint? _XOffset;

    public ref float X
    {
        get
        {
            _XOffset = _XOffset ?? Schema.GetOffset(0x3D70697FFD0C5087);
            return ref _Handle.AsRef<float>(_XOffset!.Value);
        }
    }
    private static nint? _YOffset;

    public ref float Y
    {
        get
        {
            _YOffset = _YOffset ?? Schema.GetOffset(0x3D70697FFC0C4EF4);
            return ref _Handle.AsRef<float>(_YOffset!.Value);
        }
    }
    private static nint? _FadeSpeedOffset;

    public ref float FadeSpeed
    {
        get
        {
            _FadeSpeedOffset = _FadeSpeedOffset ?? Schema.GetOffset(0x3D70697F785C93EE);
            return ref _Handle.AsRef<float>(_FadeSpeedOffset!.Value);
        }
    }
    private static nint? _BounceFactorOffset;

    public ref float BounceFactor
    {
        get
        {
            _BounceFactorOffset = _BounceFactorOffset ?? Schema.GetOffset(0x3D70697F3447A1EE);
            return ref _Handle.AsRef<float>(_BounceFactorOffset!.Value);
        }
    }
    private static nint? _HitSoundOffset;

    public ref int HitSound
    {
        get
        {
            _HitSoundOffset = _HitSoundOffset ?? Schema.GetOffset(0x3D70697F0D1009A1);
            return ref _Handle.AsRef<int>(_HitSoundOffset!.Value);
        }
    }
    private static nint? _PriorityOffset;

    public ref int Priority
    {
        get
        {
            _PriorityOffset = _PriorityOffset ?? Schema.GetOffset(0x3D70697F94E4E309);
            return ref _Handle.AsRef<int>(_PriorityOffset!.Value);
        }
    }
    private static nint? _TentOffsetOffset;

    public ref Vector TentOffset
    {
        get
        {
            _TentOffsetOffset = _TentOffsetOffset ?? Schema.GetOffset(0x3D70697F1FB084E3);
            return ref _Handle.AsRef<Vector>(_TentOffsetOffset!.Value);
        }
    }
    private static nint? _TempEntAngVelocityOffset;

    public ref QAngle TempEntAngVelocity
    {
        get
        {
            _TempEntAngVelocityOffset = _TempEntAngVelocityOffset ?? Schema.GetOffset(0x3D70697F10DE2607);
            return ref _Handle.AsRef<QAngle>(_TempEntAngVelocityOffset!.Value);
        }
    }
    private static nint? _Tempent_renderamtOffset;

    public ref int Tempent_renderamt
    {
        get
        {
            _Tempent_renderamtOffset = _Tempent_renderamtOffset ?? Schema.GetOffset(0x3D70697F54508DB1);
            return ref _Handle.AsRef<int>(_Tempent_renderamtOffset!.Value);
        }
    }
    private static nint? _NormalOffset;

    public ref Vector Normal
    {
        get
        {
            _NormalOffset = _NormalOffset ?? Schema.GetOffset(0x3D70697F363057B2);
            return ref _Handle.AsRef<Vector>(_NormalOffset!.Value);
        }
    }
    private static nint? _SpriteScaleOffset;

    public ref float SpriteScale
    {
        get
        {
            _SpriteScaleOffset = _SpriteScaleOffset ?? Schema.GetOffset(0x3D70697FE39D2B84);
            return ref _Handle.AsRef<float>(_SpriteScaleOffset!.Value);
        }
    }
    private static nint? _FlickerFrameOffset;

    public ref int FlickerFrame
    {
        get
        {
            _FlickerFrameOffset = _FlickerFrameOffset ?? Schema.GetOffset(0x3D70697FFE048CE0);
            return ref _Handle.AsRef<int>(_FlickerFrameOffset!.Value);
        }
    }
    private static nint? _FrameRateOffset;

    public ref float FrameRate
    {
        get
        {
            _FrameRateOffset = _FrameRateOffset ?? Schema.GetOffset(0x3D70697F74BE5A46);
            return ref _Handle.AsRef<float>(_FrameRateOffset!.Value);
        }
    }
    private static nint? _FrameOffset;

    public ref float Frame
    {
        get
        {
            _FrameOffset = _FrameOffset ?? Schema.GetOffset(0x3D70697FF836C9F4);
            return ref _Handle.AsRef<float>(_FrameOffset!.Value);
        }
    }
    private static nint? _ImpactEffectOffset;

    public string ImpactEffect
    {
        get
        {
            _ImpactEffectOffset = _ImpactEffectOffset ?? Schema.GetOffset(0x3D70697F6C7A9371);
            return Schema.GetString(_Handle.Read<nint>(_ImpactEffectOffset!.Value));
        }
        set
        {
            _ImpactEffectOffset = _ImpactEffectOffset ?? Schema.GetOffset(0x3D70697F6C7A9371);
            Schema.SetString(_Handle, _ImpactEffectOffset!.Value, value);
        }
    }
    private static nint? _ParticleEffectOffset;

    public string ParticleEffect
    {
        get
        {
            _ParticleEffectOffset = _ParticleEffectOffset ?? Schema.GetOffset(0x3D70697FD9595AED);
            return Schema.GetString(_Handle.Read<nint>(_ParticleEffectOffset!.Value));
        }
        set
        {
            _ParticleEffectOffset = _ParticleEffectOffset ?? Schema.GetOffset(0x3D70697FD9595AED);
            Schema.SetString(_Handle, _ParticleEffectOffset!.Value, value);
        }
    }
    private static nint? _ParticleCollisionOffset;

    public ref bool ParticleCollision
    {
        get
        {
            _ParticleCollisionOffset = _ParticleCollisionOffset ?? Schema.GetOffset(0x3D70697F6F4333F1);
            return ref _Handle.AsRef<bool>(_ParticleCollisionOffset!.Value);
        }
    }
    private static nint? _LastCollisionFrameOffset;

    public ref int LastCollisionFrame
    {
        get
        {
            _LastCollisionFrameOffset = _LastCollisionFrameOffset ?? Schema.GetOffset(0x3D70697FD1C537F9);
            return ref _Handle.AsRef<int>(_LastCollisionFrameOffset!.Value);
        }
    }
    private static nint? _LastCollisionOriginOffset;

    public ref Vector LastCollisionOrigin
    {
        get
        {
            _LastCollisionOriginOffset = _LastCollisionOriginOffset ?? Schema.GetOffset(0x3D70697F552ADE49);
            return ref _Handle.AsRef<Vector>(_LastCollisionOriginOffset!.Value);
        }
    }
    private static nint? _TempEntVelocityOffset;

    public ref Vector TempEntVelocity
    {
        get
        {
            _TempEntVelocityOffset = _TempEntVelocityOffset ?? Schema.GetOffset(0x3D70697FFD14115F);
            return ref _Handle.AsRef<Vector>(_TempEntVelocityOffset!.Value);
        }
    }
    private static nint? _PrevAbsOriginOffset;

    public ref Vector PrevAbsOrigin
    {
        get
        {
            _PrevAbsOriginOffset = _PrevAbsOriginOffset ?? Schema.GetOffset(0x3D70697F8F24D3A2);
            return ref _Handle.AsRef<Vector>(_PrevAbsOriginOffset!.Value);
        }
    }
    private static nint? _TempEntAccelerationOffset;

    public ref Vector TempEntAcceleration
    {
        get
        {
            _TempEntAccelerationOffset = _TempEntAccelerationOffset ?? Schema.GetOffset(0x3D70697F0CF41E18);
            return ref _Handle.AsRef<Vector>(_TempEntAccelerationOffset!.Value);
        }
    }

}