// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_MolotovProjectileImpl : C_BaseCSGrenadeProjectileImpl, C_MolotovProjectile
{
    public C_MolotovProjectileImpl(nint handle) : base(handle) { }

    private static nint? _IsIncGrenadeOffset;

    public ref bool IsIncGrenade
    {
        get
        {
            _IsIncGrenadeOffset = _IsIncGrenadeOffset ?? Schema.GetOffset(0xF6CA69EC9D1C12B7);
            return ref _Handle.AsRef<bool>(_IsIncGrenadeOffset!.Value);
        }
    }

}