// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_OP_MaxVelocityImpl : CParticleFunctionOperatorImpl, C_OP_MaxVelocity
{
    public C_OP_MaxVelocityImpl(nint handle) : base(handle) { }

    private static nint? _MaxVelocityOffset;

    public CPerParticleFloatInput MaxVelocity
    {
        get
        {
            _MaxVelocityOffset = _MaxVelocityOffset ?? Schema.GetOffset(0xE7D67D7E281BD640);
            return new CPerParticleFloatInputImpl(_Handle + _MaxVelocityOffset!.Value);
        }
    }
    private static nint? _MinVelocityOffset;

    public CPerParticleFloatInput MinVelocity
    {
        get
        {
            _MinVelocityOffset = _MinVelocityOffset ?? Schema.GetOffset(0xE7D67D7EAE8F0ADE);
            return new CPerParticleFloatInputImpl(_Handle + _MinVelocityOffset!.Value);
        }
    }

}