// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_PlayerVisibilityImpl : C_BaseEntityImpl, C_PlayerVisibility
{
    public C_PlayerVisibilityImpl(nint handle) : base(handle) { }

    private static nint? _VisibilityStrengthOffset;

    public ref float VisibilityStrength
    {
        get
        {
            _VisibilityStrengthOffset = _VisibilityStrengthOffset ?? Schema.GetOffset(0x67FF23E69B9E8E4E);
            return ref _Handle.AsRef<float>(_VisibilityStrengthOffset!.Value);
        }
    }
    private static nint? _FogDistanceMultiplierOffset;

    public ref float FogDistanceMultiplier
    {
        get
        {
            _FogDistanceMultiplierOffset = _FogDistanceMultiplierOffset ?? Schema.GetOffset(0x67FF23E6DB1CD031);
            return ref _Handle.AsRef<float>(_FogDistanceMultiplierOffset!.Value);
        }
    }
    private static nint? _FogMaxDensityMultiplierOffset;

    public ref float FogMaxDensityMultiplier
    {
        get
        {
            _FogMaxDensityMultiplierOffset = _FogMaxDensityMultiplierOffset ?? Schema.GetOffset(0x67FF23E67F993C70);
            return ref _Handle.AsRef<float>(_FogMaxDensityMultiplierOffset!.Value);
        }
    }
    private static nint? _FadeTimeOffset;

    public ref float FadeTime
    {
        get
        {
            _FadeTimeOffset = _FadeTimeOffset ?? Schema.GetOffset(0x67FF23E600BEDB08);
            return ref _Handle.AsRef<float>(_FadeTimeOffset!.Value);
        }
    }
    private static nint? _StartDisabledOffset;

    public ref bool StartDisabled
    {
        get
        {
            _StartDisabledOffset = _StartDisabledOffset ?? Schema.GetOffset(0x67FF23E661ED0C4F);
            return ref _Handle.AsRef<bool>(_StartDisabledOffset!.Value);
        }
    }
    private static nint? _IsEnabledOffset;

    public ref bool IsEnabled
    {
        get
        {
            _IsEnabledOffset = _IsEnabledOffset ?? Schema.GetOffset(0x67FF23E65360D70E);
            return ref _Handle.AsRef<bool>(_IsEnabledOffset!.Value);
        }
    }

}