// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_PointCameraImpl : C_BaseEntityImpl, C_PointCamera
{
    public C_PointCameraImpl(nint handle) : base(handle) { }

    private static nint? _FOVOffset;

    public ref float FOV
    {
        get
        {
            _FOVOffset = _FOVOffset ?? Schema.GetOffset(0xF2B5EC605C3A63DC);
            return ref _Handle.AsRef<float>(_FOVOffset!.Value);
        }
    }
    private static nint? _ResolutionOffset;

    public ref float Resolution
    {
        get
        {
            _ResolutionOffset = _ResolutionOffset ?? Schema.GetOffset(0xF2B5EC60B9351D0F);
            return ref _Handle.AsRef<float>(_ResolutionOffset!.Value);
        }
    }
    private static nint? _FogEnableOffset;

    public ref bool FogEnable
    {
        get
        {
            _FogEnableOffset = _FogEnableOffset ?? Schema.GetOffset(0xF2B5EC607ED6A448);
            return ref _Handle.AsRef<bool>(_FogEnableOffset!.Value);
        }
    }
    private static nint? _FogColorOffset;

    public ref Color FogColor
    {
        get
        {
            _FogColorOffset = _FogColorOffset ?? Schema.GetOffset(0xF2B5EC60C5585AAE);
            return ref _Handle.AsRef<Color>(_FogColorOffset!.Value);
        }
    }
    private static nint? _FogStartOffset;

    public ref float FogStart
    {
        get
        {
            _FogStartOffset = _FogStartOffset ?? Schema.GetOffset(0xF2B5EC602A8DE023);
            return ref _Handle.AsRef<float>(_FogStartOffset!.Value);
        }
    }
    private static nint? _FogEndOffset;

    public ref float FogEnd
    {
        get
        {
            _FogEndOffset = _FogEndOffset ?? Schema.GetOffset(0xF2B5EC6034D4BC16);
            return ref _Handle.AsRef<float>(_FogEndOffset!.Value);
        }
    }
    private static nint? _FogMaxDensityOffset;

    public ref float FogMaxDensity
    {
        get
        {
            _FogMaxDensityOffset = _FogMaxDensityOffset ?? Schema.GetOffset(0xF2B5EC6043CD4C8B);
            return ref _Handle.AsRef<float>(_FogMaxDensityOffset!.Value);
        }
    }
    private static nint? _ActiveOffset;

    public ref bool Active
    {
        get
        {
            _ActiveOffset = _ActiveOffset ?? Schema.GetOffset(0xF2B5EC608334208F);
            return ref _Handle.AsRef<bool>(_ActiveOffset!.Value);
        }
    }
    private static nint? _UseScreenAspectRatioOffset;

    public ref bool UseScreenAspectRatio
    {
        get
        {
            _UseScreenAspectRatioOffset = _UseScreenAspectRatioOffset ?? Schema.GetOffset(0xF2B5EC6053101AA3);
            return ref _Handle.AsRef<bool>(_UseScreenAspectRatioOffset!.Value);
        }
    }
    private static nint? _AspectRatioOffset;

    public ref float AspectRatio
    {
        get
        {
            _AspectRatioOffset = _AspectRatioOffset ?? Schema.GetOffset(0xF2B5EC6081C7922E);
            return ref _Handle.AsRef<float>(_AspectRatioOffset!.Value);
        }
    }
    private static nint? _NoSkyOffset;

    public ref bool NoSky
    {
        get
        {
            _NoSkyOffset = _NoSkyOffset ?? Schema.GetOffset(0xF2B5EC60760FF03B);
            return ref _Handle.AsRef<bool>(_NoSkyOffset!.Value);
        }
    }
    private static nint? _BrightnessOffset;

    public ref float Brightness
    {
        get
        {
            _BrightnessOffset = _BrightnessOffset ?? Schema.GetOffset(0xF2B5EC602E2B25BE);
            return ref _Handle.AsRef<float>(_BrightnessOffset!.Value);
        }
    }
    private static nint? _ZFarOffset;

    public ref float ZFar
    {
        get
        {
            _ZFarOffset = _ZFarOffset ?? Schema.GetOffset(0xF2B5EC60578834A4);
            return ref _Handle.AsRef<float>(_ZFarOffset!.Value);
        }
    }
    private static nint? _ZNearOffset;

    public ref float ZNear
    {
        get
        {
            _ZNearOffset = _ZNearOffset ?? Schema.GetOffset(0xF2B5EC60C81DED31);
            return ref _Handle.AsRef<float>(_ZNearOffset!.Value);
        }
    }
    private static nint? _CanHLTVUseOffset;

    public ref bool CanHLTVUse
    {
        get
        {
            _CanHLTVUseOffset = _CanHLTVUseOffset ?? Schema.GetOffset(0xF2B5EC60EF15745A);
            return ref _Handle.AsRef<bool>(_CanHLTVUseOffset!.Value);
        }
    }
    private static nint? _AlignWithParentOffset;

    public ref bool AlignWithParent
    {
        get
        {
            _AlignWithParentOffset = _AlignWithParentOffset ?? Schema.GetOffset(0xF2B5EC6071E0F322);
            return ref _Handle.AsRef<bool>(_AlignWithParentOffset!.Value);
        }
    }
    private static nint? _DofEnabledOffset;

    public ref bool DofEnabled
    {
        get
        {
            _DofEnabledOffset = _DofEnabledOffset ?? Schema.GetOffset(0xF2B5EC60EDC8F923);
            return ref _Handle.AsRef<bool>(_DofEnabledOffset!.Value);
        }
    }
    private static nint? _DofNearBlurryOffset;

    public ref float DofNearBlurry
    {
        get
        {
            _DofNearBlurryOffset = _DofNearBlurryOffset ?? Schema.GetOffset(0xF2B5EC607C69D002);
            return ref _Handle.AsRef<float>(_DofNearBlurryOffset!.Value);
        }
    }
    private static nint? _DofNearCrispOffset;

    public ref float DofNearCrisp
    {
        get
        {
            _DofNearCrispOffset = _DofNearCrispOffset ?? Schema.GetOffset(0xF2B5EC60B0E97BC1);
            return ref _Handle.AsRef<float>(_DofNearCrispOffset!.Value);
        }
    }
    private static nint? _DofFarCrispOffset;

    public ref float DofFarCrisp
    {
        get
        {
            _DofFarCrispOffset = _DofFarCrispOffset ?? Schema.GetOffset(0xF2B5EC602EC98B88);
            return ref _Handle.AsRef<float>(_DofFarCrispOffset!.Value);
        }
    }
    private static nint? _DofFarBlurryOffset;

    public ref float DofFarBlurry
    {
        get
        {
            _DofFarBlurryOffset = _DofFarBlurryOffset ?? Schema.GetOffset(0xF2B5EC60312C6605);
            return ref _Handle.AsRef<float>(_DofFarBlurryOffset!.Value);
        }
    }
    private static nint? _DofTiltToGroundOffset;

    public ref float DofTiltToGround
    {
        get
        {
            _DofTiltToGroundOffset = _DofTiltToGroundOffset ?? Schema.GetOffset(0xF2B5EC603DF50E81);
            return ref _Handle.AsRef<float>(_DofTiltToGroundOffset!.Value);
        }
    }
    private static nint? _TargetFOVOffset;

    public ref float TargetFOV
    {
        get
        {
            _TargetFOVOffset = _TargetFOVOffset ?? Schema.GetOffset(0xF2B5EC605BA7ABEB);
            return ref _Handle.AsRef<float>(_TargetFOVOffset!.Value);
        }
    }
    private static nint? _DegreesPerSecondOffset;

    public ref float DegreesPerSecond
    {
        get
        {
            _DegreesPerSecondOffset = _DegreesPerSecondOffset ?? Schema.GetOffset(0xF2B5EC60469C1605);
            return ref _Handle.AsRef<float>(_DegreesPerSecondOffset!.Value);
        }
    }
    private static nint? _IsOnOffset;

    public ref bool IsOn
    {
        get
        {
            _IsOnOffset = _IsOnOffset ?? Schema.GetOffset(0xF2B5EC606387DB60);
            return ref _Handle.AsRef<bool>(_IsOnOffset!.Value);
        }
    }
    private static nint? _NextOffset;
    private C_PointCameraImpl? _NextInstance;

    public C_PointCamera? Next
    {
        get
        {
            _NextOffset = _NextOffset ?? Schema.GetOffset(0xF2B5EC6032B11E0E);
            var ptr = _Handle.Read<nint>(_NextOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _NextInstance ??= new C_PointCameraImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }

}