// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_SceneEntity__QueuedEvents_tImpl : SchemaClass, C_SceneEntity__QueuedEvents_t
{
    public C_SceneEntity__QueuedEvents_tImpl(nint handle) : base(handle) { }

    private static nint? _StarttimeOffset;

    public ref float Starttime
    {
        get
        {
            _StarttimeOffset = _StarttimeOffset ?? Schema.GetOffset(0xA0CC44B98A708DEE);
            return ref _Handle.AsRef<float>(_StarttimeOffset!.Value);
        }
    }

}