// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class C_SoundEventSphereEntityImpl : C_SoundEventEntityImpl, C_SoundEventSphereEntity
{
    public C_SoundEventSphereEntityImpl(nint handle) : base(handle) { }

    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0x551C00B05ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }

}