// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_FollowTargetNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_FollowTargetNode
{
    public CAnimGraphDoc_FollowTargetNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0x610C9261F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _BoneNameOffset;

    public string BoneName
    {
        get
        {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0x610C926FDEE0E0C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_BoneNameOffset!.Value));
        }
        set
        {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0x610C926FDEE0E0C);
            Schema.SetCUtlString(_Handle, _BoneNameOffset!.Value, value);
        }
    }
    private static nint? _TargetSettingsOffset;
    private IKTargetSettings_tImpl? _TargetSettingsInstance;

    public IKTargetSettings_t TargetSettings
    {
        get
        {
            _TargetSettingsOffset = _TargetSettingsOffset ?? Schema.GetOffset(0x610C926D6828E35);
            var instance = _TargetSettingsInstance ??= new IKTargetSettings_tImpl(0);
            instance.DangerousSetHandle(_Handle + _TargetSettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _MatchTargetOrientationOffset;

    public ref bool MatchTargetOrientation
    {
        get
        {
            _MatchTargetOrientationOffset = _MatchTargetOrientationOffset ?? Schema.GetOffset(0x610C92642E0C3DB);
            return ref _Handle.AsRef<bool>(_MatchTargetOrientationOffset!.Value);
        }
    }

}