// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_TwoBoneIKNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_TwoBoneIKNode
{
    public CAnimGraphDoc_TwoBoneIKNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0xFC2D3A7E1F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _IkChainNameOffset;

    public string IkChainName
    {
        get
        {
            _IkChainNameOffset = _IkChainNameOffset ?? Schema.GetOffset(0xFC2D3A7E50E152ED);
            return Schema.GetCUtlString(_Handle.Read<nint>(_IkChainNameOffset!.Value));
        }
        set
        {
            _IkChainNameOffset = _IkChainNameOffset ?? Schema.GetOffset(0xFC2D3A7E50E152ED);
            Schema.SetCUtlString(_Handle, _IkChainNameOffset!.Value, value);
        }
    }
    private static nint? _AutoDetectHingeAxisOffset;

    public ref bool AutoDetectHingeAxis
    {
        get
        {
            _AutoDetectHingeAxisOffset = _AutoDetectHingeAxisOffset ?? Schema.GetOffset(0xFC2D3A7E1393C829);
            return ref _Handle.AsRef<bool>(_AutoDetectHingeAxisOffset!.Value);
        }
    }
    private static nint? _EndEffectorTypeOffset;

    public ref IkEndEffectorType EndEffectorType
    {
        get
        {
            _EndEffectorTypeOffset = _EndEffectorTypeOffset ?? Schema.GetOffset(0xFC2D3A7E687CB4CE);
            return ref _Handle.AsRef<IkEndEffectorType>(_EndEffectorTypeOffset!.Value);
        }
    }
    private static nint? _EndEffectorAttachmentNameOffset;

    public string EndEffectorAttachmentName
    {
        get
        {
            _EndEffectorAttachmentNameOffset = _EndEffectorAttachmentNameOffset ?? Schema.GetOffset(0xFC2D3A7EFDA52480);
            return Schema.GetCUtlString(_Handle.Read<nint>(_EndEffectorAttachmentNameOffset!.Value));
        }
        set
        {
            _EndEffectorAttachmentNameOffset = _EndEffectorAttachmentNameOffset ?? Schema.GetOffset(0xFC2D3A7EFDA52480);
            Schema.SetCUtlString(_Handle, _EndEffectorAttachmentNameOffset!.Value, value);
        }
    }
    private static nint? _TargetTypeOffset;

    public ref IkTargetType TargetType
    {
        get
        {
            _TargetTypeOffset = _TargetTypeOffset ?? Schema.GetOffset(0xFC2D3A7E13C167A0);
            return ref _Handle.AsRef<IkTargetType>(_TargetTypeOffset!.Value);
        }
    }
    private static nint? _AttachmentNameOffset;

    public string AttachmentName
    {
        get
        {
            _AttachmentNameOffset = _AttachmentNameOffset ?? Schema.GetOffset(0xFC2D3A7E295DA9CB);
            return Schema.GetCUtlString(_Handle.Read<nint>(_AttachmentNameOffset!.Value));
        }
        set
        {
            _AttachmentNameOffset = _AttachmentNameOffset ?? Schema.GetOffset(0xFC2D3A7E295DA9CB);
            Schema.SetCUtlString(_Handle, _AttachmentNameOffset!.Value, value);
        }
    }
    private static nint? _TargetBoneNameOffset;

    public string TargetBoneName
    {
        get
        {
            _TargetBoneNameOffset = _TargetBoneNameOffset ?? Schema.GetOffset(0xFC2D3A7EAF85A2D5);
            return Schema.GetCUtlString(_Handle.Read<nint>(_TargetBoneNameOffset!.Value));
        }
        set
        {
            _TargetBoneNameOffset = _TargetBoneNameOffset ?? Schema.GetOffset(0xFC2D3A7EAF85A2D5);
            Schema.SetCUtlString(_Handle, _TargetBoneNameOffset!.Value, value);
        }
    }
    private static nint? _TargetParamNameOffset;

    public string TargetParamName
    {
        get
        {
            _TargetParamNameOffset = _TargetParamNameOffset ?? Schema.GetOffset(0xFC2D3A7EBF8E8ED2);
            return Schema.GetCUtlString(_Handle.Read<nint>(_TargetParamNameOffset!.Value));
        }
        set
        {
            _TargetParamNameOffset = _TargetParamNameOffset ?? Schema.GetOffset(0xFC2D3A7EBF8E8ED2);
            Schema.SetCUtlString(_Handle, _TargetParamNameOffset!.Value, value);
        }
    }
    private static nint? _TargetParamOffset;
    private AnimParamIDImpl? _TargetParamInstance;

    public AnimParamID TargetParam
    {
        get
        {
            _TargetParamOffset = _TargetParamOffset ?? Schema.GetOffset(0xFC2D3A7E012FF719);
            var instance = _TargetParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _TargetParamOffset!.Value);
            return instance;
        }
    }
    private static nint? _MatchTargetOrientationOffset;

    public ref bool MatchTargetOrientation
    {
        get
        {
            _MatchTargetOrientationOffset = _MatchTargetOrientationOffset ?? Schema.GetOffset(0xFC2D3A7E42E0C3DB);
            return ref _Handle.AsRef<bool>(_MatchTargetOrientationOffset!.Value);
        }
    }
    private static nint? _RotationParamNameOffset;

    public string RotationParamName
    {
        get
        {
            _RotationParamNameOffset = _RotationParamNameOffset ?? Schema.GetOffset(0xFC2D3A7E6A009A07);
            return Schema.GetCUtlString(_Handle.Read<nint>(_RotationParamNameOffset!.Value));
        }
        set
        {
            _RotationParamNameOffset = _RotationParamNameOffset ?? Schema.GetOffset(0xFC2D3A7E6A009A07);
            Schema.SetCUtlString(_Handle, _RotationParamNameOffset!.Value, value);
        }
    }
    private static nint? _RotationParamOffset;
    private AnimParamIDImpl? _RotationParamInstance;

    public AnimParamID RotationParam
    {
        get
        {
            _RotationParamOffset = _RotationParamOffset ?? Schema.GetOffset(0xFC2D3A7E489D30EC);
            var instance = _RotationParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _RotationParamOffset!.Value);
            return instance;
        }
    }
    private static nint? _ConstrainTwistOffset;

    public ref bool ConstrainTwist
    {
        get
        {
            _ConstrainTwistOffset = _ConstrainTwistOffset ?? Schema.GetOffset(0xFC2D3A7EDB3DB7ED);
            return ref _Handle.AsRef<bool>(_ConstrainTwistOffset!.Value);
        }
    }
    private static nint? _MaxTwistOffset;

    public ref float MaxTwist
    {
        get
        {
            _MaxTwistOffset = _MaxTwistOffset ?? Schema.GetOffset(0xFC2D3A7EA898EE6E);
            return ref _Handle.AsRef<float>(_MaxTwistOffset!.Value);
        }
    }

}