// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_PlayerInputMotorImpl : CAnimGraphDoc_MotorImpl, CAnimGraphDoc_PlayerInputMotor
{
    public CAnimGraphDoc_PlayerInputMotorImpl(nint handle) : base(handle) { }

    private static nint? _SampleTimesOffset;

    public ref CUtlVector<float> SampleTimes
    {
        get
        {
            _SampleTimesOffset = _SampleTimesOffset ?? Schema.GetOffset(0x314C1356471975DF);
            return ref _Handle.AsRef<CUtlVector<float>>(_SampleTimesOffset!.Value);
        }
    }
    private static nint? _UseAccelerationOffset;

    public ref bool UseAcceleration
    {
        get
        {
            _UseAccelerationOffset = _UseAccelerationOffset ?? Schema.GetOffset(0x314C1356254F8B08);
            return ref _Handle.AsRef<bool>(_UseAccelerationOffset!.Value);
        }
    }
    private static nint? _SpringConstantOffset;

    public ref float SpringConstant
    {
        get
        {
            _SpringConstantOffset = _SpringConstantOffset ?? Schema.GetOffset(0x314C1356CE2260BE);
            return ref _Handle.AsRef<float>(_SpringConstantOffset!.Value);
        }
    }
    private static nint? _AnticipationDistanceOffset;

    public ref float AnticipationDistance
    {
        get
        {
            _AnticipationDistanceOffset = _AnticipationDistanceOffset ?? Schema.GetOffset(0x314C135664273401);
            return ref _Handle.AsRef<float>(_AnticipationDistanceOffset!.Value);
        }
    }
    private static nint? _AnticipationPosParamNameOffset;

    public string AnticipationPosParamName
    {
        get
        {
            _AnticipationPosParamNameOffset = _AnticipationPosParamNameOffset ?? Schema.GetOffset(0x314C1356EBBAA830);
            return Schema.GetCUtlString(_Handle.Read<nint>(_AnticipationPosParamNameOffset!.Value));
        }
        set
        {
            _AnticipationPosParamNameOffset = _AnticipationPosParamNameOffset ?? Schema.GetOffset(0x314C1356EBBAA830);
            Schema.SetCUtlString(_Handle, _AnticipationPosParamNameOffset!.Value, value);
        }
    }
    private static nint? _AnticipationPosParamOffset;
    private AnimParamIDImpl? _AnticipationPosParamInstance;

    public AnimParamID AnticipationPosParam
    {
        get
        {
            _AnticipationPosParamOffset = _AnticipationPosParamOffset ?? Schema.GetOffset(0x314C1356C3BF072B);
            var instance = _AnticipationPosParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _AnticipationPosParamOffset!.Value);
            return instance;
        }
    }
    private static nint? _AnticipationHeadingParamNameOffset;

    public string AnticipationHeadingParamName
    {
        get
        {
            _AnticipationHeadingParamNameOffset = _AnticipationHeadingParamNameOffset ?? Schema.GetOffset(0x314C13560803781C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_AnticipationHeadingParamNameOffset!.Value));
        }
        set
        {
            _AnticipationHeadingParamNameOffset = _AnticipationHeadingParamNameOffset ?? Schema.GetOffset(0x314C13560803781C);
            Schema.SetCUtlString(_Handle, _AnticipationHeadingParamNameOffset!.Value, value);
        }
    }
    private static nint? _AnticipationHeadingParamOffset;
    private AnimParamIDImpl? _AnticipationHeadingParamInstance;

    public AnimParamID AnticipationHeadingParam
    {
        get
        {
            _AnticipationHeadingParamOffset = _AnticipationHeadingParamOffset ?? Schema.GetOffset(0x314C1356D8BD043F);
            var instance = _AnticipationHeadingParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _AnticipationHeadingParamOffset!.Value);
            return instance;
        }
    }

}