// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_ClipDataImpl : SchemaClass, CAnimGraphDoc_ClipData
{
    public CAnimGraphDoc_ClipDataImpl(nint handle) : base(handle) { }

    private static nint? _TagSpansOffset;

    public ref CUtlVector<SchemaUntypedField> TagSpans
    {
        get
        {
            _TagSpansOffset = _TagSpansOffset ?? Schema.GetOffset(0x867ABAF4A56106AC);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_TagSpansOffset!.Value);
        }
    }
    private static nint? _ClipNameOffset;

    public string ClipName
    {
        get
        {
            _ClipNameOffset = _ClipNameOffset ?? Schema.GetOffset(0x867ABAF477D84420);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ClipNameOffset!.Value));
        }
        set
        {
            _ClipNameOffset = _ClipNameOffset ?? Schema.GetOffset(0x867ABAF477D84420);
            Schema.SetCUtlString(_Handle, _ClipNameOffset!.Value, value);
        }
    }

}