// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_TagSpanImpl : SchemaClass, CAnimGraphDoc_TagSpan
{
    public CAnimGraphDoc_TagSpanImpl(nint handle) : base(handle) { }

    private static nint? _IdOffset;
    private AnimTagIDImpl? _IdInstance;

    public AnimTagID Id
    {
        get
        {
            _IdOffset = _IdOffset ?? Schema.GetOffset(0x96F8D342B4B6E980);
            var instance = _IdInstance ??= new AnimTagIDImpl(0);
            instance.DangerousSetHandle(_Handle + _IdOffset!.Value);
            return instance;
        }
    }
    private static nint? _StartCycleOffset;

    public ref float StartCycle
    {
        get
        {
            _StartCycleOffset = _StartCycleOffset ?? Schema.GetOffset(0x96F8D34267649293);
            return ref _Handle.AsRef<float>(_StartCycleOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0x96F8D342A1702439);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }

}