// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_StanceScaleNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_StanceScaleNode
{
    public CAnimGraphDoc_StanceScaleNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0xF0D2CFA01F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParamNameOffset;

    public string ParamName
    {
        get
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0xF0D2CFA0E87A9639);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ParamNameOffset!.Value));
        }
        set
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0xF0D2CFA0E87A9639);
            Schema.SetCUtlString(_Handle, _ParamNameOffset!.Value, value);
        }
    }
    private static nint? _ParamOffset;
    private AnimParamIDImpl? _ParamInstance;

    public AnimParamID Param
    {
        get
        {
            _ParamOffset = _ParamOffset ?? Schema.GetOffset(0xF0D2CFA0BCD4D752);
            var instance = _ParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamOffset!.Value);
            return instance;
        }
    }

}