// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_MotionItemImpl : SchemaClass, CAnimGraphDoc_MotionItem
{
    public CAnimGraphDoc_MotionItemImpl(nint handle) : base(handle) { }

    private static nint? _ParamManagerOffset;
    private CAnimGraphDoc_MotionParameterManagerImpl? _ParamManagerInstance;

    public CAnimGraphDoc_MotionParameterManager ParamManager
    {
        get
        {
            _ParamManagerOffset = _ParamManagerOffset ?? Schema.GetOffset(0x8D5A8D3FF50B25C9);
            var instance = _ParamManagerInstance ??= new CAnimGraphDoc_MotionParameterManagerImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamManagerOffset!.Value);
            return instance;
        }
    }
    private static nint? _BlockSpansOffset;

    public ref CUtlVector<SchemaUntypedField> BlockSpans
    {
        get
        {
            _BlockSpansOffset = _BlockSpansOffset ?? Schema.GetOffset(0x8D5A8D3F44892E43);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_BlockSpansOffset!.Value);
        }
    }
    private static nint? _TagSpansOffset;

    public ref CUtlVector<SchemaUntypedField> TagSpans
    {
        get
        {
            _TagSpansOffset = _TagSpansOffset ?? Schema.GetOffset(0x8D5A8D3FA56106AC);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_TagSpansOffset!.Value);
        }
    }
    private static nint? _ParamSpansOffset;

    public ref CUtlVector<SchemaUntypedField> ParamSpans
    {
        get
        {
            _ParamSpansOffset = _ParamSpansOffset ?? Schema.GetOffset(0x8D5A8D3FDAC91553);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ParamSpansOffset!.Value);
        }
    }
    private static nint? _LoopOffset;

    public ref bool Loop
    {
        get
        {
            _LoopOffset = _LoopOffset ?? Schema.GetOffset(0x8D5A8D3FC668A4CB);
            return ref _Handle.AsRef<bool>(_LoopOffset!.Value);
        }
    }

}