// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_ParameterConditionImpl : CAnimGraphDoc_ConditionImpl, CAnimGraphDoc_ParameterCondition
{
    public CAnimGraphDoc_ParameterConditionImpl(nint handle) : base(handle) { }

    private static nint? _ParamNameOffset;

    public string ParamName
    {
        get
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0xF57A2AF6E87A9639);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ParamNameOffset!.Value));
        }
        set
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0xF57A2AF6E87A9639);
            Schema.SetCUtlString(_Handle, _ParamNameOffset!.Value, value);
        }
    }
    private static nint? _ParamIDOffset;
    private AnimParamIDImpl? _ParamIDInstance;

    public AnimParamID ParamID
    {
        get
        {
            _ParamIDOffset = _ParamIDOffset ?? Schema.GetOffset(0xF57A2AF6D605831F);
            var instance = _ParamIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _ComparisonOpOffset;

    public ref Comparison_t ComparisonOp
    {
        get
        {
            _ComparisonOpOffset = _ComparisonOpOffset ?? Schema.GetOffset(0xF57A2AF6BC2AB253);
            return ref _Handle.AsRef<Comparison_t>(_ComparisonOpOffset!.Value);
        }
    }
    private static nint? _ComparisonValueOffset;
    private SchemaUntypedField? _ComparisonValueInstance;

    public SchemaUntypedField ComparisonValue
    {
        get
        {
            _ComparisonValueOffset = _ComparisonValueOffset ?? Schema.GetOffset(0xF57A2AF6E8EEEB1D);
            var instance = _ComparisonValueInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ComparisonValueOffset!.Value);
            return instance;
        }
    }
    private static nint? _ComparisonStringOffset;

    public string ComparisonString
    {
        get
        {
            _ComparisonStringOffset = _ComparisonStringOffset ?? Schema.GetOffset(0xF57A2AF60AAA1B85);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ComparisonStringOffset!.Value));
        }
        set
        {
            _ComparisonStringOffset = _ComparisonStringOffset ?? Schema.GetOffset(0xF57A2AF60AAA1B85);
            Schema.SetCUtlString(_Handle, _ComparisonStringOffset!.Value, value);
        }
    }

}