// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_PathMetricImpl : CAnimGraphDoc_MotionMetricImpl, CAnimGraphDoc_PathMetric
{
    public CAnimGraphDoc_PathMetricImpl(nint handle) : base(handle) { }

    private static nint? _DistanceOffset;

    public ref float Distance
    {
        get
        {
            _DistanceOffset = _DistanceOffset ?? Schema.GetOffset(0x3686343D00DC4A68);
            return ref _Handle.AsRef<float>(_DistanceOffset!.Value);
        }
    }
    private static nint? _PathSamplesOffset;

    public ref CUtlVector<float> PathSamples
    {
        get
        {
            _PathSamplesOffset = _PathSamplesOffset ?? Schema.GetOffset(0x3686343D1F55BC75);
            return ref _Handle.AsRef<CUtlVector<float>>(_PathSamplesOffset!.Value);
        }
    }
    private static nint? _ExtrapolateMovementOffset;

    public ref bool ExtrapolateMovement
    {
        get
        {
            _ExtrapolateMovementOffset = _ExtrapolateMovementOffset ?? Schema.GetOffset(0x3686343DCBEE3025);
            return ref _Handle.AsRef<bool>(_ExtrapolateMovementOffset!.Value);
        }
    }
    private static nint? _MinExtrapolationSpeedOffset;

    public ref float MinExtrapolationSpeed
    {
        get
        {
            _MinExtrapolationSpeedOffset = _MinExtrapolationSpeedOffset ?? Schema.GetOffset(0x3686343D9F6FB95C);
            return ref _Handle.AsRef<float>(_MinExtrapolationSpeedOffset!.Value);
        }
    }

}