// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimConflictInfo_tImpl : SchemaClass, CAnimConflictInfo_t
{
    public CAnimConflictInfo_tImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xC971E2824D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xC971E2824D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _GroupNameOffset;

    public string GroupName
    {
        get
        {
            _GroupNameOffset = _GroupNameOffset ?? Schema.GetOffset(0xC971E282025FB2C7);
            return Schema.GetCUtlString(_Handle.Read<nint>(_GroupNameOffset!.Value));
        }
        set
        {
            _GroupNameOffset = _GroupNameOffset ?? Schema.GetOffset(0xC971E282025FB2C7);
            Schema.SetCUtlString(_Handle, _GroupNameOffset!.Value, value);
        }
    }
    private static nint? _SubgraphNameOffset;

    public string SubgraphName
    {
        get
        {
            _SubgraphNameOffset = _SubgraphNameOffset ?? Schema.GetOffset(0xC971E282DB801374);
            return Schema.GetCUtlString(_Handle.Read<nint>(_SubgraphNameOffset!.Value));
        }
        set
        {
            _SubgraphNameOffset = _SubgraphNameOffset ?? Schema.GetOffset(0xC971E282DB801374);
            Schema.SetCUtlString(_Handle, _SubgraphNameOffset!.Value, value);
        }
    }
    private static nint? _IdOffset;

    public ref uint Id
    {
        get
        {
            _IdOffset = _IdOffset ?? Schema.GetOffset(0xC971E282B4B6E980);
            return ref _Handle.AsRef<uint>(_IdOffset!.Value);
        }
    }

}