// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_FinishedConditionImpl : CAnimGraphDoc_ConditionImpl, CAnimGraphDoc_FinishedCondition
{
    public CAnimGraphDoc_FinishedConditionImpl(nint handle) : base(handle) { }

    private static nint? _OptionOffset;

    public ref FinishedConditionOption Option
    {
        get
        {
            _OptionOffset = _OptionOffset ?? Schema.GetOffset(0x6627D63985C51534);
            return ref _Handle.AsRef<FinishedConditionOption>(_OptionOffset!.Value);
        }
    }
    private static nint? _IsFinishedOffset;

    public ref bool IsFinished
    {
        get
        {
            _IsFinishedOffset = _IsFinishedOffset ?? Schema.GetOffset(0x6627D639F0384393);
            return ref _Handle.AsRef<bool>(_IsFinishedOffset!.Value);
        }
    }

}