// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_StopAtGoalNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_StopAtGoalNode
{
    public CAnimGraphDoc_StopAtGoalNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0x744814641F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _OuterRadiusOffset;

    public ref float OuterRadius
    {
        get
        {
            _OuterRadiusOffset = _OuterRadiusOffset ?? Schema.GetOffset(0x744814647B66A818);
            return ref _Handle.AsRef<float>(_OuterRadiusOffset!.Value);
        }
    }
    private static nint? _InnerRadiusOffset;

    public ref float InnerRadius
    {
        get
        {
            _InnerRadiusOffset = _InnerRadiusOffset ?? Schema.GetOffset(0x7448146432121407);
            return ref _Handle.AsRef<float>(_InnerRadiusOffset!.Value);
        }
    }
    private static nint? _MaxScaleOffset;

    public ref float MaxScale
    {
        get
        {
            _MaxScaleOffset = _MaxScaleOffset ?? Schema.GetOffset(0x74481464FF4EC8E7);
            return ref _Handle.AsRef<float>(_MaxScaleOffset!.Value);
        }
    }
    private static nint? _MinScaleOffset;

    public ref float MinScale
    {
        get
        {
            _MinScaleOffset = _MinScaleOffset ?? Schema.GetOffset(0x74481464D125D67D);
            return ref _Handle.AsRef<float>(_MinScaleOffset!.Value);
        }
    }
    private static nint? _DampingOffset;
    private CAnimInputDampingImpl? _DampingInstance;

    public CAnimInputDamping Damping
    {
        get
        {
            _DampingOffset = _DampingOffset ?? Schema.GetOffset(0x7448146415440FB5);
            var instance = _DampingInstance ??= new CAnimInputDampingImpl(0);
            instance.DangerousSetHandle(_Handle + _DampingOffset!.Value);
            return instance;
        }
    }

}