// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_SingleFrameNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_SingleFrameNode
{
    public CAnimGraphDoc_SingleFrameNodeImpl(nint handle) : base(handle) { }

    private static nint? _SequenceNameOffset;

    public string SequenceName
    {
        get
        {
            _SequenceNameOffset = _SequenceNameOffset ?? Schema.GetOffset(0x47C509C32B4A24CB);
            return Schema.GetCUtlString(_Handle.Read<nint>(_SequenceNameOffset!.Value));
        }
        set
        {
            _SequenceNameOffset = _SequenceNameOffset ?? Schema.GetOffset(0x47C509C32B4A24CB);
            Schema.SetCUtlString(_Handle, _SequenceNameOffset!.Value, value);
        }
    }
    private static nint? _FrameSelectionOffset;

    public ref SingleFrameSelection FrameSelection
    {
        get
        {
            _FrameSelectionOffset = _FrameSelectionOffset ?? Schema.GetOffset(0x47C509C33188AC2D);
            return ref _Handle.AsRef<SingleFrameSelection>(_FrameSelectionOffset!.Value);
        }
    }
    private static nint? _FrameIndexOffset;

    public ref int FrameIndex
    {
        get
        {
            _FrameIndexOffset = _FrameIndexOffset ?? Schema.GetOffset(0x47C509C3A816E9B6);
            return ref _Handle.AsRef<int>(_FrameIndexOffset!.Value);
        }
    }
    private static nint? _ActionsOffset;

    public ref CUtlVector<SchemaUntypedField> Actions
    {
        get
        {
            _ActionsOffset = _ActionsOffset ?? Schema.GetOffset(0x47C509C38D622684);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ActionsOffset!.Value);
        }
    }

}