// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimConflictBaseImpl : SchemaClass, CAnimConflictBase
{
    public CAnimConflictBaseImpl(nint handle) : base(handle) { }

    private static nint? _ConflictDescOffset;

    public string ConflictDesc
    {
        get
        {
            _ConflictDescOffset = _ConflictDescOffset ?? Schema.GetOffset(0x29013DC31507801);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ConflictDescOffset!.Value));
        }
        set
        {
            _ConflictDescOffset = _ConflictDescOffset ?? Schema.GetOffset(0x29013DC31507801);
            Schema.SetCUtlString(_Handle, _ConflictDescOffset!.Value, value);
        }
    }
    private static nint? _ResolveIdxOffset;

    public ref int ResolveIdx
    {
        get
        {
            _ResolveIdxOffset = _ResolveIdxOffset ?? Schema.GetOffset(0x29013DC4E58CCBE);
            return ref _Handle.AsRef<int>(_ResolveIdxOffset!.Value);
        }
    }
    private static nint? _ConflictDataOffset;
    private SchemaClassFixedArray<CAnimConflictInfo_t>? _ConflictDataInstance;

    public ISchemaClassFixedArray<CAnimConflictInfo_t> ConflictData
    {
        get
        {
            _ConflictDataOffset = _ConflictDataOffset ?? Schema.GetOffset(0x29013DC8B7AD5D7);
            var instance = _ConflictDataInstance ??= new SchemaClassFixedArray<CAnimConflictInfo_t>(0, 0x29013DC8B7AD5D7, 2, 32, 8);
            instance.DangerousSetHandle(_Handle + _ConflictDataOffset!.Value);
            return instance;
        }
    }
    private static nint? _ConflictTypeOffset;

    public ref AnimConflictType_t ConflictType
    {
        get
        {
            _ConflictTypeOffset = _ConflictTypeOffset ?? Schema.GetOffset(0x29013DCCC569E92);
            return ref _Handle.AsRef<AnimConflictType_t>(_ConflictTypeOffset!.Value);
        }
    }

}