// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_ConflictManagerImpl : SchemaClass, CAnimGraphDoc_ConflictManager
{
    public CAnimGraphDoc_ConflictManagerImpl(nint handle) : base(handle) { }

    private static nint? _ConflictsOffset;

    public ref CUtlVector<SchemaUntypedField> Conflicts
    {
        get
        {
            _ConflictsOffset = _ConflictsOffset ?? Schema.GetOffset(0xE8DA1997CBA22314);
            return ref _Handle.AsRef<CUtlVector<SchemaUntypedField>>(_ConflictsOffset!.Value);
        }
    }

}