// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_WayPointHelperNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_WayPointHelperNode
{
    public CAnimGraphDoc_WayPointHelperNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0x68FC746D1F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _StartCycleOffset;

    public ref float StartCycle
    {
        get
        {
            _StartCycleOffset = _StartCycleOffset ?? Schema.GetOffset(0x68FC746DABB46051);
            return ref _Handle.AsRef<float>(_StartCycleOffset!.Value);
        }
    }
    private static nint? _EndCycleOffset;

    public ref float EndCycle
    {
        get
        {
            _EndCycleOffset = _EndCycleOffset ?? Schema.GetOffset(0x68FC746D176E8F62);
            return ref _Handle.AsRef<float>(_EndCycleOffset!.Value);
        }
    }
    private static nint? _OnlyGoalsOffset;

    public ref bool OnlyGoals
    {
        get
        {
            _OnlyGoalsOffset = _OnlyGoalsOffset ?? Schema.GetOffset(0x68FC746D3526BA11);
            return ref _Handle.AsRef<bool>(_OnlyGoalsOffset!.Value);
        }
    }
    private static nint? _PreventOvershootOffset;

    public ref bool PreventOvershoot
    {
        get
        {
            _PreventOvershootOffset = _PreventOvershootOffset ?? Schema.GetOffset(0x68FC746DB161EADA);
            return ref _Handle.AsRef<bool>(_PreventOvershootOffset!.Value);
        }
    }
    private static nint? _PreventUndershootOffset;

    public ref bool PreventUndershoot
    {
        get
        {
            _PreventUndershootOffset = _PreventUndershootOffset ?? Schema.GetOffset(0x68FC746DC22276F8);
            return ref _Handle.AsRef<bool>(_PreventUndershootOffset!.Value);
        }
    }

}