// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_ExpressionActionImpl : CAnimGraphDoc_ActionImpl, CAnimGraphDoc_ExpressionAction
{
    public CAnimGraphDoc_ExpressionActionImpl(nint handle) : base(handle) { }

    private static nint? _ParamNameOffset;

    public string ParamName
    {
        get
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0x4BB4EF32E87A9639);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ParamNameOffset!.Value));
        }
        set
        {
            _ParamNameOffset = _ParamNameOffset ?? Schema.GetOffset(0x4BB4EF32E87A9639);
            Schema.SetCUtlString(_Handle, _ParamNameOffset!.Value, value);
        }
    }
    private static nint? _ParamOffset;
    private AnimParamIDImpl? _ParamInstance;

    public AnimParamID Param
    {
        get
        {
            _ParamOffset = _ParamOffset ?? Schema.GetOffset(0x4BB4EF32BCD4D752);
            var instance = _ParamInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamOffset!.Value);
            return instance;
        }
    }
    private static nint? _ExpressionOffset;

    public string Expression
    {
        get
        {
            _ExpressionOffset = _ExpressionOffset ?? Schema.GetOffset(0x4BB4EF3287957D8B);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ExpressionOffset!.Value));
        }
        set
        {
            _ExpressionOffset = _ExpressionOffset ?? Schema.GetOffset(0x4BB4EF3287957D8B);
            Schema.SetCUtlString(_Handle, _ExpressionOffset!.Value, value);
        }
    }

}