// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAnimGraphDoc_DirectPlaybackNodeImpl : CAnimGraphDoc_NodeImpl, CAnimGraphDoc_DirectPlaybackNode
{
    public CAnimGraphDoc_DirectPlaybackNodeImpl(nint handle) : base(handle) { }

    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0x34956BFA1F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }
    private static nint? _FinishEarlyOffset;

    public ref bool FinishEarly
    {
        get
        {
            _FinishEarlyOffset = _FinishEarlyOffset ?? Schema.GetOffset(0x34956BFAC2E75991);
            return ref _Handle.AsRef<bool>(_FinishEarlyOffset!.Value);
        }
    }
    private static nint? _ResetOnFinishOffset;

    public ref bool ResetOnFinish
    {
        get
        {
            _ResetOnFinishOffset = _ResetOnFinishOffset ?? Schema.GetOffset(0x34956BFAD5293C96);
            return ref _Handle.AsRef<bool>(_ResetOnFinishOffset!.Value);
        }
    }

}