// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CAssetWarningCheckImpl : SchemaClass, CAssetWarningCheck
{
    public CAssetWarningCheckImpl(nint handle) : base(handle) { }

    private static nint? _AssetTypeOffset;

    public string AssetType
    {
        get
        {
            _AssetTypeOffset = _AssetTypeOffset ?? Schema.GetOffset(0xF974B37A8C74FD23);
            return Schema.GetCUtlString(_Handle.Read<nint>(_AssetTypeOffset!.Value));
        }
        set
        {
            _AssetTypeOffset = _AssetTypeOffset ?? Schema.GetOffset(0xF974B37A8C74FD23);
            Schema.SetCUtlString(_Handle, _AssetTypeOffset!.Value, value);
        }
    }
    private static nint? _RequireSearchableIntKeyOffset;

    public ref CBufferString RequireSearchableIntKey
    {
        get
        {
            _RequireSearchableIntKeyOffset = _RequireSearchableIntKeyOffset ?? Schema.GetOffset(0xF974B37A144BC088);
            return ref _Handle.AsRef<CBufferString>(_RequireSearchableIntKeyOffset!.Value);
        }
    }
    private static nint? _RequireSearchableIntValueOffset;

    public ref int RequireSearchableIntValue
    {
        get
        {
            _RequireSearchableIntValueOffset = _RequireSearchableIntValueOffset ?? Schema.GetOffset(0xF974B37A2D71D52E);
            return ref _Handle.AsRef<int>(_RequireSearchableIntValueOffset!.Value);
        }
    }
    private static nint? _OnlyWarnIfGameFilePresentOffset;

    public ref bool OnlyWarnIfGameFilePresent
    {
        get
        {
            _OnlyWarnIfGameFilePresentOffset = _OnlyWarnIfGameFilePresentOffset ?? Schema.GetOffset(0xF974B37A73754713);
            return ref _Handle.AsRef<bool>(_OnlyWarnIfGameFilePresentOffset!.Value);
        }
    }
    private static nint? _OnlyWarnIfContentFilePresentOffset;

    public ref bool OnlyWarnIfContentFilePresent
    {
        get
        {
            _OnlyWarnIfContentFilePresentOffset = _OnlyWarnIfContentFilePresentOffset ?? Schema.GetOffset(0xF974B37A3E99382E);
            return ref _Handle.AsRef<bool>(_OnlyWarnIfContentFilePresentOffset!.Value);
        }
    }
    private static nint? _OnlyWarnAddonsOffset;

    public ref bool OnlyWarnAddons
    {
        get
        {
            _OnlyWarnAddonsOffset = _OnlyWarnAddonsOffset ?? Schema.GetOffset(0xF974B37A118E1348);
            return ref _Handle.AsRef<bool>(_OnlyWarnAddonsOffset!.Value);
        }
    }
    private static nint? _ExcludeAddonNamesOffset;

    public ref CUtlVector<CUtlString> ExcludeAddonNames
    {
        get
        {
            _ExcludeAddonNamesOffset = _ExcludeAddonNamesOffset ?? Schema.GetOffset(0xF974B37A42F6C753);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_ExcludeAddonNamesOffset!.Value);
        }
    }
    private static nint? _FixDescriptionOffset;

    public string FixDescription
    {
        get
        {
            _FixDescriptionOffset = _FixDescriptionOffset ?? Schema.GetOffset(0xF974B37AD5B11952);
            return Schema.GetCUtlString(_Handle.Read<nint>(_FixDescriptionOffset!.Value));
        }
        set
        {
            _FixDescriptionOffset = _FixDescriptionOffset ?? Schema.GetOffset(0xF974B37AD5B11952);
            Schema.SetCUtlString(_Handle, _FixDescriptionOffset!.Value, value);
        }
    }
    private static nint? _FixTypeOffset;

    public ref AssetWarningFixType_t FixType
    {
        get
        {
            _FixTypeOffset = _FixTypeOffset ?? Schema.GetOffset(0xF974B37AA78E5710);
            return ref _Handle.AsRef<AssetWarningFixType_t>(_FixTypeOffset!.Value);
        }
    }

}