// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CColorCorrectionLayerImpl : SchemaClass, CColorCorrectionLayer
{
    public CColorCorrectionLayerImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x56C7CEA4D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x56C7CEA4D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _OpacityPercentOffset;

    public ref int OpacityPercent
    {
        get
        {
            _OpacityPercentOffset = _OpacityPercentOffset ?? Schema.GetOffset(0x56C7CEA79B5A93B);
            return ref _Handle.AsRef<int>(_OpacityPercentOffset!.Value);
        }
    }
    private static nint? _VisibleOffset;

    public ref bool Visible
    {
        get
        {
            _VisibleOffset = _VisibleOffset ?? Schema.GetOffset(0x56C7CEA73EEB681);
            return ref _Handle.AsRef<bool>(_VisibleOffset!.Value);
        }
    }
    private static nint? _LayerMaskOffset;
    private CLayerMaskImpl? _LayerMaskInstance;

    public CLayerMask? LayerMask
    {
        get
        {
            _LayerMaskOffset = _LayerMaskOffset ?? Schema.GetOffset(0x56C7CEADE43E2B8);
            var ptr = _Handle.Read<nint>(_LayerMaskOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _LayerMaskInstance ??= new CLayerMaskImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }

}