// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CColorTintColorCorrectionLayerImpl : CColorCorrectionLayerImpl, CColorTintColorCorrectionLayer
{
    public CColorTintColorCorrectionLayerImpl(nint handle) : base(handle) { }

    private static nint? _TintColorROffset;

    public ref int TintColorR
    {
        get
        {
            _TintColorROffset = _TintColorROffset ?? Schema.GetOffset(0x27F517C436ED864F);
            return ref _Handle.AsRef<int>(_TintColorROffset!.Value);
        }
    }
    private static nint? _TintColorGOffset;

    public ref int TintColorG
    {
        get
        {
            _TintColorGOffset = _TintColorGOffset ?? Schema.GetOffset(0x27F517C421ED6540);
            return ref _Handle.AsRef<int>(_TintColorGOffset!.Value);
        }
    }
    private static nint? _TintColorBOffset;

    public ref int TintColorB
    {
        get
        {
            _TintColorBOffset = _TintColorBOffset ?? Schema.GetOffset(0x27F517C426ED6D1F);
            return ref _Handle.AsRef<int>(_TintColorBOffset!.Value);
        }
    }
    private static nint? _StrengthOffset;

    public ref int Strength
    {
        get
        {
            _StrengthOffset = _StrengthOffset ?? Schema.GetOffset(0x27F517C4AA98CF34);
            return ref _Handle.AsRef<int>(_StrengthOffset!.Value);
        }
    }
    private static nint? _PreserveLuminosityOffset;

    public ref bool PreserveLuminosity
    {
        get
        {
            _PreserveLuminosityOffset = _PreserveLuminosityOffset ?? Schema.GetOffset(0x27F517C4D25D30C0);
            return ref _Handle.AsRef<bool>(_PreserveLuminosityOffset!.Value);
        }
    }

}