// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CColorLookupColorCorrectionLayerImpl : CColorCorrectionLayerImpl, CColorLookupColorCorrectionLayer
{
    public CColorLookupColorCorrectionLayerImpl(nint handle) : base(handle) { }

    private static nint? _FileNameOffset;

    public string FileName
    {
        get
        {
            _FileNameOffset = _FileNameOffset ?? Schema.GetOffset(0xC72ADB43C8D68508);
            return Schema.GetCUtlString(_Handle.Read<nint>(_FileNameOffset!.Value));
        }
        set
        {
            _FileNameOffset = _FileNameOffset ?? Schema.GetOffset(0xC72ADB43C8D68508);
            Schema.SetCUtlString(_Handle, _FileNameOffset!.Value, value);
        }
    }
    private static nint? _LutOffset;

    public ref CUtlVector<float> Lut
    {
        get
        {
            _LutOffset = _LutOffset ?? Schema.GetOffset(0xC72ADB433EB3048A);
            return ref _Handle.AsRef<CUtlVector<float>>(_LutOffset!.Value);
        }
    }
    private static nint? _DimOffset;

    public ref int Dim
    {
        get
        {
            _DimOffset = _DimOffset ?? Schema.GetOffset(0xC72ADB43F904CF6D);
            return ref _Handle.AsRef<int>(_DimOffset!.Value);
        }
    }

}