// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCompositeMaterialEditorDocImpl : SchemaClass, CCompositeMaterialEditorDoc
{
    public CCompositeMaterialEditorDocImpl(nint handle) : base(handle) { }

    private static nint? _VersionOffset;

    public ref int Version
    {
        get
        {
            _VersionOffset = _VersionOffset ?? Schema.GetOffset(0xEF8ED7DDB0AB8B1B);
            return ref _Handle.AsRef<int>(_VersionOffset!.Value);
        }
    }
    private static nint? _PointsOffset;

    public ref CUtlVector<CompositeMaterialEditorPoint_t> Points
    {
        get
        {
            _PointsOffset = _PointsOffset ?? Schema.GetOffset(0xEF8ED7DD2B362046);
            return ref _Handle.AsRef<CUtlVector<CompositeMaterialEditorPoint_t>>(_PointsOffset!.Value);
        }
    }
    private static nint? _KVthumbnailOffset;
    private SchemaUntypedField? _KVthumbnailInstance;

    public SchemaUntypedField KVthumbnail
    {
        get
        {
            _KVthumbnailOffset = _KVthumbnailOffset ?? Schema.GetOffset(0xEF8ED7DDAE646E40);
            var instance = _KVthumbnailInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _KVthumbnailOffset!.Value);
            return instance;
        }
    }

}