// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CConnectionProxyItemImpl : SchemaClass, CConnectionProxyItem
{
    public CConnectionProxyItemImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x7F472EA94D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x7F472EA94D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _OutputIDOffset;
    private AnimNodeOutputIDImpl? _OutputIDInstance;

    public AnimNodeOutputID OutputID
    {
        get
        {
            _OutputIDOffset = _OutputIDOffset ?? Schema.GetOffset(0x7F472EA98456A4A9);
            var instance = _OutputIDInstance ??= new AnimNodeOutputIDImpl(0);
            instance.DangerousSetHandle(_Handle + _OutputIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputConnectionOffset;
    private CAnimGraphDoc_NodeConnectionImpl? _InputConnectionInstance;

    public CAnimGraphDoc_NodeConnection InputConnection
    {
        get
        {
            _InputConnectionOffset = _InputConnectionOffset ?? Schema.GetOffset(0x7F472EA91F7849CB);
            var instance = _InputConnectionInstance ??= new CAnimGraphDoc_NodeConnectionImpl(0);
            instance.DangerousSetHandle(_Handle + _InputConnectionOffset!.Value);
            return instance;
        }
    }

}