// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CCurvesColorCorrectionLayerImpl : CColorCorrectionLayerImpl, CCurvesColorCorrectionLayer
{
    public CCurvesColorCorrectionLayerImpl(nint handle) : base(handle) { }

    private static nint? _CurvePointsRGBOffset;

    public ref CUtlVector<Vector2D> CurvePointsRGB
    {
        get
        {
            _CurvePointsRGBOffset = _CurvePointsRGBOffset ?? Schema.GetOffset(0x134C626A552ED952);
            return ref _Handle.AsRef<CUtlVector<Vector2D>>(_CurvePointsRGBOffset!.Value);
        }
    }
    private static nint? _CurvePointsROffset;

    public ref CUtlVector<Vector2D> CurvePointsR
    {
        get
        {
            _CurvePointsROffset = _CurvePointsROffset ?? Schema.GetOffset(0x134C626AEBE9CE4B);
            return ref _Handle.AsRef<CUtlVector<Vector2D>>(_CurvePointsROffset!.Value);
        }
    }
    private static nint? _CurvePointsGOffset;

    public ref CUtlVector<Vector2D> CurvePointsG
    {
        get
        {
            _CurvePointsGOffset = _CurvePointsGOffset ?? Schema.GetOffset(0x134C626AFEE9EC34);
            return ref _Handle.AsRef<CUtlVector<Vector2D>>(_CurvePointsGOffset!.Value);
        }
    }
    private static nint? _CurvePointsBOffset;

    public ref CUtlVector<Vector2D> CurvePointsB
    {
        get
        {
            _CurvePointsBOffset = _CurvePointsBOffset ?? Schema.GetOffset(0x134C626AFBE9E77B);
            return ref _Handle.AsRef<CUtlVector<Vector2D>>(_CurvePointsBOffset!.Value);
        }
    }

}