// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CDampedValueComponentImpl : CAnimGraphDoc_ComponentImpl, CDampedValueComponent
{
    public CDampedValueComponentImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xFC288A994D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xFC288A994D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _ItemsOffset;

    public ref CUtlVector<CDampedValueItem> Items
    {
        get
        {
            _ItemsOffset = _ItemsOffset ?? Schema.GetOffset(0xFC288A997A87EDAF);
            return ref _Handle.AsRef<CUtlVector<CDampedValueItem>>(_ItemsOffset!.Value);
        }
    }

}