// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFogScatteringLayerImpl : CColorCorrectionLayerImpl, CFogScatteringLayer
{
    public CFogScatteringLayerImpl(nint handle) : base(handle) { }

    private static nint? _ParamsOffset;
    private PostProcessingFogScatteringParameters_tImpl? _ParamsInstance;

    public PostProcessingFogScatteringParameters_t Params
    {
        get
        {
            _ParamsOffset = _ParamsOffset ?? Schema.GetOffset(0xABA6D715640EA8F3);
            var instance = _ParamsInstance ??= new PostProcessingFogScatteringParameters_tImpl(0);
            instance.DangerousSetHandle(_Handle + _ParamsOffset!.Value);
            return instance;
        }
    }

}