// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CFootLockItemImpl : SchemaClass, CFootLockItem
{
    public CFootLockItemImpl(nint handle) : base(handle) { }

    private static nint? _FootNameOffset;

    public string FootName
    {
        get
        {
            _FootNameOffset = _FootNameOffset ?? Schema.GetOffset(0x88F69EFE228316B2);
            return Schema.GetCUtlString(_Handle.Read<nint>(_FootNameOffset!.Value));
        }
        set
        {
            _FootNameOffset = _FootNameOffset ?? Schema.GetOffset(0x88F69EFE228316B2);
            Schema.SetCUtlString(_Handle, _FootNameOffset!.Value, value);
        }
    }
    private static nint? _TargetBoneNameOffset;

    public string TargetBoneName
    {
        get
        {
            _TargetBoneNameOffset = _TargetBoneNameOffset ?? Schema.GetOffset(0x88F69EFEAF85A2D5);
            return Schema.GetCUtlString(_Handle.Read<nint>(_TargetBoneNameOffset!.Value));
        }
        set
        {
            _TargetBoneNameOffset = _TargetBoneNameOffset ?? Schema.GetOffset(0x88F69EFEAF85A2D5);
            Schema.SetCUtlString(_Handle, _TargetBoneNameOffset!.Value, value);
        }
    }
    private static nint? _IkChainNameOffset;

    public string IkChainName
    {
        get
        {
            _IkChainNameOffset = _IkChainNameOffset ?? Schema.GetOffset(0x88F69EFE50E152ED);
            return Schema.GetCUtlString(_Handle.Read<nint>(_IkChainNameOffset!.Value));
        }
        set
        {
            _IkChainNameOffset = _IkChainNameOffset ?? Schema.GetOffset(0x88F69EFE50E152ED);
            Schema.SetCUtlString(_Handle, _IkChainNameOffset!.Value, value);
        }
    }
    private static nint? _DisableTagNameOffset;

    public ref CGlobalSymbol DisableTagName
    {
        get
        {
            _DisableTagNameOffset = _DisableTagNameOffset ?? Schema.GetOffset(0x88F69EFE853F641A);
            return ref _Handle.AsRef<CGlobalSymbol>(_DisableTagNameOffset!.Value);
        }
    }
    private static nint? _DisableTagIDOffset;
    private AnimTagIDImpl? _DisableTagIDInstance;

    public AnimTagID DisableTagID
    {
        get
        {
            _DisableTagIDOffset = _DisableTagIDOffset ?? Schema.GetOffset(0x88F69EFE13A87E94);
            var instance = _DisableTagIDInstance ??= new AnimTagIDImpl(0);
            instance.DangerousSetHandle(_Handle + _DisableTagIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _MaxRotationLeftOffset;

    public ref float MaxRotationLeft
    {
        get
        {
            _MaxRotationLeftOffset = _MaxRotationLeftOffset ?? Schema.GetOffset(0x88F69EFEFA1CDF44);
            return ref _Handle.AsRef<float>(_MaxRotationLeftOffset!.Value);
        }
    }
    private static nint? _MaxRotationRightOffset;

    public ref float MaxRotationRight
    {
        get
        {
            _MaxRotationRightOffset = _MaxRotationRightOffset ?? Schema.GetOffset(0x88F69EFE8C95FA31);
            return ref _Handle.AsRef<float>(_MaxRotationRightOffset!.Value);
        }
    }
    private static nint? _FootstepLandedTagNameOffset;

    public ref CGlobalSymbol FootstepLandedTagName
    {
        get
        {
            _FootstepLandedTagNameOffset = _FootstepLandedTagNameOffset ?? Schema.GetOffset(0x88F69EFE1DCCB156);
            return ref _Handle.AsRef<CGlobalSymbol>(_FootstepLandedTagNameOffset!.Value);
        }
    }
    private static nint? _FootstepLandedTagOffset;
    private AnimTagIDImpl? _FootstepLandedTagInstance;

    public AnimTagID FootstepLandedTag
    {
        get
        {
            _FootstepLandedTagOffset = _FootstepLandedTagOffset ?? Schema.GetOffset(0x88F69EFE87469215);
            var instance = _FootstepLandedTagInstance ??= new AnimTagIDImpl(0);
            instance.DangerousSetHandle(_Handle + _FootstepLandedTagOffset!.Value);
            return instance;
        }
    }

}