// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CGraphPreviewListImpl : SchemaClass, CGraphPreviewList
{
    public CGraphPreviewListImpl(nint handle) : base(handle) { }

    private static nint? _VolumeOffset;

    public ref float Volume
    {
        get
        {
            _VolumeOffset = _VolumeOffset ?? Schema.GetOffset(0x7A40C4727647E0C9);
            return ref _Handle.AsRef<float>(_VolumeOffset!.Value);
        }
    }
    private static nint? _PreviewListOffset;
    private CPreviewListImpl? _PreviewListInstance;

    public CPreviewList PreviewList
    {
        get
        {
            _PreviewListOffset = _PreviewListOffset ?? Schema.GetOffset(0x7A40C4727035D7DF);
            var instance = _PreviewListInstance ??= new CPreviewListImpl(0);
            instance.DangerousSetHandle(_Handle + _PreviewListOffset!.Value);
            return instance;
        }
    }

}