// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLightRigGridImpl : SchemaClass, CLightRigGrid
{
    public CLightRigGridImpl(nint handle) : base(handle) { }

    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0x9518E4486154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _ColorOffset;

    public ref Color Color
    {
        get
        {
            _ColorOffset = _ColorOffset ?? Schema.GetOffset(0x9518E448D7D017D8);
            return ref _Handle.AsRef<Color>(_ColorOffset!.Value);
        }
    }

}