// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLightRigSkyImpl : SchemaClass, CLightRigSky
{
    public CLightRigSkyImpl(nint handle) : base(handle) { }

    private static nint? _SkyMaterialOffset;

    public ref CStrongHandle<InfoForResourceTypeIMaterial2> SkyMaterial
    {
        get
        {
            _SkyMaterialOffset = _SkyMaterialOffset ?? Schema.GetOffset(0xF59FD725C887319D);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeIMaterial2>>(_SkyMaterialOffset!.Value);
        }
    }

}