// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLODComponentImpl : CAnimGraphDoc_ComponentImpl, CLODComponent
{
    public CLODComponentImpl(nint handle) : base(handle) { }

    private static nint? _ServerLODOffset;

    public ref int ServerLOD
    {
        get
        {
            _ServerLODOffset = _ServerLODOffset ?? Schema.GetOffset(0xEC615EAC244E2C75);
            return ref _Handle.AsRef<int>(_ServerLODOffset!.Value);
        }
    }

}