// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CLookComponentImpl : CAnimGraphDoc_ComponentImpl, CLookComponent
{
    public CLookComponentImpl(nint handle) : base(handle) { }

    private static nint? _NetworkLookTargetOffset;

    public ref bool NetworkLookTarget
    {
        get
        {
            _NetworkLookTargetOffset = _NetworkLookTargetOffset ?? Schema.GetOffset(0x3C5E394C39F2F527);
            return ref _Handle.AsRef<bool>(_NetworkLookTargetOffset!.Value);
        }
    }
    private static nint? _LookHeadingIDOffset;
    private AnimParamIDImpl? _LookHeadingIDInstance;

    public AnimParamID LookHeadingID
    {
        get
        {
            _LookHeadingIDOffset = _LookHeadingIDOffset ?? Schema.GetOffset(0x3C5E394CB3BC2EF5);
            var instance = _LookHeadingIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookHeadingIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookHeadingNormalizedIDOffset;
    private AnimParamIDImpl? _LookHeadingNormalizedIDInstance;

    public AnimParamID LookHeadingNormalizedID
    {
        get
        {
            _LookHeadingNormalizedIDOffset = _LookHeadingNormalizedIDOffset ?? Schema.GetOffset(0x3C5E394C741D8260);
            var instance = _LookHeadingNormalizedIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookHeadingNormalizedIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookHeadingVelocityIDOffset;
    private AnimParamIDImpl? _LookHeadingVelocityIDInstance;

    public AnimParamID LookHeadingVelocityID
    {
        get
        {
            _LookHeadingVelocityIDOffset = _LookHeadingVelocityIDOffset ?? Schema.GetOffset(0x3C5E394C99910336);
            var instance = _LookHeadingVelocityIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookHeadingVelocityIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookPitchIDOffset;
    private AnimParamIDImpl? _LookPitchIDInstance;

    public AnimParamID LookPitchID
    {
        get
        {
            _LookPitchIDOffset = _LookPitchIDOffset ?? Schema.GetOffset(0x3C5E394CDFE17EC9);
            var instance = _LookPitchIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookPitchIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookDistanceIDOffset;
    private AnimParamIDImpl? _LookDistanceIDInstance;

    public AnimParamID LookDistanceID
    {
        get
        {
            _LookDistanceIDOffset = _LookDistanceIDOffset ?? Schema.GetOffset(0x3C5E394C68237308);
            var instance = _LookDistanceIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookDistanceIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookDirectionIDOffset;
    private AnimParamIDImpl? _LookDirectionIDInstance;

    public AnimParamID LookDirectionID
    {
        get
        {
            _LookDirectionIDOffset = _LookDirectionIDOffset ?? Schema.GetOffset(0x3C5E394C82962086);
            var instance = _LookDirectionIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookDirectionIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookTargetIDOffset;
    private AnimParamIDImpl? _LookTargetIDInstance;

    public AnimParamID LookTargetID
    {
        get
        {
            _LookTargetIDOffset = _LookTargetIDOffset ?? Schema.GetOffset(0x3C5E394C0AB3FC4A);
            var instance = _LookTargetIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookTargetIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _LookTargetWorldSpaceIDOffset;
    private AnimParamIDImpl? _LookTargetWorldSpaceIDInstance;

    public AnimParamID LookTargetWorldSpaceID
    {
        get
        {
            _LookTargetWorldSpaceIDOffset = _LookTargetWorldSpaceIDOffset ?? Schema.GetOffset(0x3C5E394CDF91A630);
            var instance = _LookTargetWorldSpaceIDInstance ??= new AnimParamIDImpl(0);
            instance.DangerousSetHandle(_Handle + _LookTargetWorldSpaceIDOffset!.Value);
            return instance;
        }
    }

}