// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixDynamicsImpl : CMixPropertyBaseImpl, CMixDynamics
{
    public CMixDynamicsImpl(nint handle) : base(handle) { }

    private static nint? _ChannelsOffset;

    public ref int Channels
    {
        get
        {
            _ChannelsOffset = _ChannelsOffset ?? Schema.GetOffset(0xE4BE0FA5A815AD1);
            return ref _Handle.AsRef<int>(_ChannelsOffset!.Value);
        }
    }
    private static nint? _FldbNoiseGateThresholdOffset;

    public ref float FldbNoiseGateThreshold
    {
        get
        {
            _FldbNoiseGateThresholdOffset = _FldbNoiseGateThresholdOffset ?? Schema.GetOffset(0xE4BE0FA9838FE4D);
            return ref _Handle.AsRef<float>(_FldbNoiseGateThresholdOffset!.Value);
        }
    }
    private static nint? _FldbGainOffset;

    public ref float FldbGain
    {
        get
        {
            _FldbGainOffset = _FldbGainOffset ?? Schema.GetOffset(0xE4BE0FA31BF2DF2);
            return ref _Handle.AsRef<float>(_FldbGainOffset!.Value);
        }
    }
    private static nint? _FldbCompressionThresholdOffset;

    public ref float FldbCompressionThreshold
    {
        get
        {
            _FldbCompressionThresholdOffset = _FldbCompressionThresholdOffset ?? Schema.GetOffset(0xE4BE0FAC45CDA7C);
            return ref _Handle.AsRef<float>(_FldbCompressionThresholdOffset!.Value);
        }
    }
    private static nint? _FldbLimiterThresholdOffset;

    public ref float FldbLimiterThreshold
    {
        get
        {
            _FldbLimiterThresholdOffset = _FldbLimiterThresholdOffset ?? Schema.GetOffset(0xE4BE0FACC95E7EA);
            return ref _Handle.AsRef<float>(_FldbLimiterThresholdOffset!.Value);
        }
    }
    private static nint? _FldbKneeWidthOffset;

    public ref float FldbKneeWidth
    {
        get
        {
            _FldbKneeWidthOffset = _FldbKneeWidthOffset ?? Schema.GetOffset(0xE4BE0FA35532FF2);
            return ref _Handle.AsRef<float>(_FldbKneeWidthOffset!.Value);
        }
    }
    private static nint? _RatioOffset;

    public ref float Ratio
    {
        get
        {
            _RatioOffset = _RatioOffset ?? Schema.GetOffset(0xE4BE0FADEAD31EA);
            return ref _Handle.AsRef<float>(_RatioOffset!.Value);
        }
    }
    private static nint? _LimiterRatioOffset;

    public ref float LimiterRatio
    {
        get
        {
            _LimiterRatioOffset = _LimiterRatioOffset ?? Schema.GetOffset(0xE4BE0FAA8D830FC);
            return ref _Handle.AsRef<float>(_LimiterRatioOffset!.Value);
        }
    }
    private static nint? _AttackTimeOffset;

    public ref float AttackTime
    {
        get
        {
            _AttackTimeOffset = _AttackTimeOffset ?? Schema.GetOffset(0xE4BE0FAC5A41DD6);
            return ref _Handle.AsRef<float>(_AttackTimeOffset!.Value);
        }
    }
    private static nint? _ReleaseTimeOffset;

    public ref float ReleaseTime
    {
        get
        {
            _ReleaseTimeOffset = _ReleaseTimeOffset ?? Schema.GetOffset(0xE4BE0FA86296445);
            return ref _Handle.AsRef<float>(_ReleaseTimeOffset!.Value);
        }
    }
    private static nint? _RMSTimeOffset;

    public ref float RMSTime
    {
        get
        {
            _RMSTimeOffset = _RMSTimeOffset ?? Schema.GetOffset(0xE4BE0FA097B7746);
            return ref _Handle.AsRef<float>(_RMSTimeOffset!.Value);
        }
    }
    private static nint? _WetMixOffset;

    public ref float WetMix
    {
        get
        {
            _WetMixOffset = _WetMixOffset ?? Schema.GetOffset(0xE4BE0FAD5453C15);
            return ref _Handle.AsRef<float>(_WetMixOffset!.Value);
        }
    }
    private static nint? _PeakModeOffset;

    public ref bool PeakMode
    {
        get
        {
            _PeakModeOffset = _PeakModeOffset ?? Schema.GetOffset(0xE4BE0FA87DF35F9);
            return ref _Handle.AsRef<bool>(_PeakModeOffset!.Value);
        }
    }
    private static nint? _UIPageOffset;

    public ref int UIPage
    {
        get
        {
            _UIPageOffset = _UIPageOffset ?? Schema.GetOffset(0xE4BE0FA9AAB3D24);
            return ref _Handle.AsRef<int>(_UIPageOffset!.Value);
        }
    }

}