// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixEffectNameImpl : CMixPropertyBaseImpl, CMixEffectName
{
    public CMixEffectNameImpl(nint handle) : base(handle) { }

    private static nint? _DefaultValueOffset;

    public string DefaultValue
    {
        get
        {
            _DefaultValueOffset = _DefaultValueOffset ?? Schema.GetOffset(0x4DB97FE6BBE0341F);
            return Schema.GetCUtlString(_Handle.Read<nint>(_DefaultValueOffset!.Value));
        }
        set
        {
            _DefaultValueOffset = _DefaultValueOffset ?? Schema.GetOffset(0x4DB97FE6BBE0341F);
            Schema.SetCUtlString(_Handle, _DefaultValueOffset!.Value, value);
        }
    }

}