// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixSteamAudioPathingImpl : CMixPropertyBaseImpl, CMixSteamAudioPathing
{
    public CMixSteamAudioPathingImpl(nint handle) : base(handle) { }

    private static nint? _PathingMixLevelOffset;

    public ref float PathingMixLevel
    {
        get
        {
            _PathingMixLevelOffset = _PathingMixLevelOffset ?? Schema.GetOffset(0xAA7DDBDB2209CCF4);
            return ref _Handle.AsRef<float>(_PathingMixLevelOffset!.Value);
        }
    }
    private static nint? _PathingEQOffset;
    private SchemaFixedArray<float>? _PathingEQInstance;

    public ISchemaFixedArray<float> PathingEQ
    {
        get
        {
            _PathingEQOffset = _PathingEQOffset ?? Schema.GetOffset(0xAA7DDBDBE08EB9A0);
            var instance = _PathingEQInstance ??= new SchemaFixedArray<float>(0, 0xAA7DDBDBE08EB9A0, 3, 4, 4);
            instance.DangerousSetHandle(_Handle + _PathingEQOffset!.Value);
            return instance;
        }
    }
    private static nint? _PathingCoeffsOffset;

    public ref CUtlVector<float> PathingCoeffs
    {
        get
        {
            _PathingCoeffsOffset = _PathingCoeffsOffset ?? Schema.GetOffset(0xAA7DDBDB76224064);
            return ref _Handle.AsRef<CUtlVector<float>>(_PathingCoeffsOffset!.Value);
        }
    }
    private static nint? _PathingEQ1Offset;

    public ref CUtlVector<float> PathingEQ1
    {
        get
        {
            _PathingEQ1Offset = _PathingEQ1Offset ?? Schema.GetOffset(0xAA7DDBDB70049A34);
            return ref _Handle.AsRef<CUtlVector<float>>(_PathingEQ1Offset!.Value);
        }
    }

}