// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixVocoderImpl : CMixPropertyBaseImpl, CMixVocoder
{
    public CMixVocoderImpl(nint handle) : base(handle) { }

    private static nint? _BandCountOffset;

    public ref int BandCount
    {
        get
        {
            _BandCountOffset = _BandCountOffset ?? Schema.GetOffset(0xF274CD5872E16EF9);
            return ref _Handle.AsRef<int>(_BandCountOffset!.Value);
        }
    }
    private static nint? _BandwidthOffset;

    public ref float Bandwidth
    {
        get
        {
            _BandwidthOffset = _BandwidthOffset ?? Schema.GetOffset(0xF274CD58BB43932C);
            return ref _Handle.AsRef<float>(_BandwidthOffset!.Value);
        }
    }
    private static nint? _FldBModGainOffset;

    public ref float FldBModGain
    {
        get
        {
            _FldBModGainOffset = _FldBModGainOffset ?? Schema.GetOffset(0xF274CD581EEAC180);
            return ref _Handle.AsRef<float>(_FldBModGainOffset!.Value);
        }
    }
    private static nint? _AttackTimeOffset;

    public ref float AttackTime
    {
        get
        {
            _AttackTimeOffset = _AttackTimeOffset ?? Schema.GetOffset(0xF274CD58C5A41DD6);
            return ref _Handle.AsRef<float>(_AttackTimeOffset!.Value);
        }
    }
    private static nint? _ReleaseTimeOffset;

    public ref float ReleaseTime
    {
        get
        {
            _ReleaseTimeOffset = _ReleaseTimeOffset ?? Schema.GetOffset(0xF274CD5886296445);
            return ref _Handle.AsRef<float>(_ReleaseTimeOffset!.Value);
        }
    }
    private static nint? _FreqRangeStartOffset;

    public ref float FreqRangeStart
    {
        get
        {
            _FreqRangeStartOffset = _FreqRangeStartOffset ?? Schema.GetOffset(0xF274CD58B4752A4E);
            return ref _Handle.AsRef<float>(_FreqRangeStartOffset!.Value);
        }
    }
    private static nint? _FreqRangeEndOffset;

    public ref float FreqRangeEnd
    {
        get
        {
            _FreqRangeEndOffset = _FreqRangeEndOffset ?? Schema.GetOffset(0xF274CD58884ECF5B);
            return ref _Handle.AsRef<float>(_FreqRangeEndOffset!.Value);
        }
    }
    private static nint? _FldBUnvoicedGainOffset;

    public ref float FldBUnvoicedGain
    {
        get
        {
            _FldBUnvoicedGainOffset = _FldBUnvoicedGainOffset ?? Schema.GetOffset(0xF274CD58B45A3DEF);
            return ref _Handle.AsRef<float>(_FldBUnvoicedGainOffset!.Value);
        }
    }
    private static nint? _DebugBandOffset;

    public ref int DebugBand
    {
        get
        {
            _DebugBandOffset = _DebugBandOffset ?? Schema.GetOffset(0xF274CD586E77C31B);
            return ref _Handle.AsRef<int>(_DebugBandOffset!.Value);
        }
    }
    private static nint? _PeakModeOffset;

    public ref bool PeakMode
    {
        get
        {
            _PeakModeOffset = _PeakModeOffset ?? Schema.GetOffset(0xF274CD5887DF35F9);
            return ref _Handle.AsRef<bool>(_PeakModeOffset!.Value);
        }
    }

}