// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixBoxverb2Impl : CMixPropertyBaseImpl, CMixBoxverb2
{
    public CMixBoxverb2Impl(nint handle) : base(handle) { }

    private static nint? _SizeMaxOffset;

    public ref float SizeMax
    {
        get
        {
            _SizeMaxOffset = _SizeMaxOffset ?? Schema.GetOffset(0x2E79C1E6B9D7F5B8);
            return ref _Handle.AsRef<float>(_SizeMaxOffset!.Value);
        }
    }
    private static nint? _SizeMinOffset;

    public ref float SizeMin
    {
        get
        {
            _SizeMinOffset = _SizeMinOffset ?? Schema.GetOffset(0x2E79C1E6AFEB6DB2);
            return ref _Handle.AsRef<float>(_SizeMinOffset!.Value);
        }
    }
    private static nint? _ComplexityOffset;

    public ref float Complexity
    {
        get
        {
            _ComplexityOffset = _ComplexityOffset ?? Schema.GetOffset(0x2E79C1E6F222266B);
            return ref _Handle.AsRef<float>(_ComplexityOffset!.Value);
        }
    }
    private static nint? _ModDepthOffset;

    public ref float ModDepth
    {
        get
        {
            _ModDepthOffset = _ModDepthOffset ?? Schema.GetOffset(0x2E79C1E6F59E0B82);
            return ref _Handle.AsRef<float>(_ModDepthOffset!.Value);
        }
    }
    private static nint? _ModRateOffset;

    public ref float ModRate
    {
        get
        {
            _ModRateOffset = _ModRateOffset ?? Schema.GetOffset(0x2E79C1E60EA039FF);
            return ref _Handle.AsRef<float>(_ModRateOffset!.Value);
        }
    }
    private static nint? _ParallelOffset;

    public ref bool Parallel
    {
        get
        {
            _ParallelOffset = _ParallelOffset ?? Schema.GetOffset(0x2E79C1E68971ED92);
            return ref _Handle.AsRef<bool>(_ParallelOffset!.Value);
        }
    }
    private static nint? _FilterTypeOffset;
    private VMixFilterDesc_tImpl? _FilterTypeInstance;

    public VMixFilterDesc_t FilterType
    {
        get
        {
            _FilterTypeOffset = _FilterTypeOffset ?? Schema.GetOffset(0x2E79C1E67E582F6F);
            var instance = _FilterTypeInstance ??= new VMixFilterDesc_tImpl(0);
            instance.DangerousSetHandle(_Handle + _FilterTypeOffset!.Value);
            return instance;
        }
    }
    private static nint? _WidthOffset;

    public ref float Width
    {
        get
        {
            _WidthOffset = _WidthOffset ?? Schema.GetOffset(0x2E79C1E6B91935E1);
            return ref _Handle.AsRef<float>(_WidthOffset!.Value);
        }
    }
    private static nint? _HeightOffset;

    public ref float Height
    {
        get
        {
            _HeightOffset = _HeightOffset ?? Schema.GetOffset(0x2E79C1E6EADD7FB0);
            return ref _Handle.AsRef<float>(_HeightOffset!.Value);
        }
    }
    private static nint? _DepthOffset;

    public ref float Depth
    {
        get
        {
            _DepthOffset = _DepthOffset ?? Schema.GetOffset(0x2E79C1E6D3AD54E8);
            return ref _Handle.AsRef<float>(_DepthOffset!.Value);
        }
    }
    private static nint? _FeedbackScaleOffset;

    public ref float FeedbackScale
    {
        get
        {
            _FeedbackScaleOffset = _FeedbackScaleOffset ?? Schema.GetOffset(0x2E79C1E62CE35D6E);
            return ref _Handle.AsRef<float>(_FeedbackScaleOffset!.Value);
        }
    }
    private static nint? _FeedbackWidthOffset;

    public ref float FeedbackWidth
    {
        get
        {
            _FeedbackWidthOffset = _FeedbackWidthOffset ?? Schema.GetOffset(0x2E79C1E650275950);
            return ref _Handle.AsRef<float>(_FeedbackWidthOffset!.Value);
        }
    }
    private static nint? _FeedbackHeightOffset;

    public ref float FeedbackHeight
    {
        get
        {
            _FeedbackHeightOffset = _FeedbackHeightOffset ?? Schema.GetOffset(0x2E79C1E6FB780A47);
            return ref _Handle.AsRef<float>(_FeedbackHeightOffset!.Value);
        }
    }
    private static nint? _FeedbackDepthOffset;

    public ref float FeedbackDepth
    {
        get
        {
            _FeedbackDepthOffset = _FeedbackDepthOffset ?? Schema.GetOffset(0x2E79C1E6B71B2D09);
            return ref _Handle.AsRef<float>(_FeedbackDepthOffset!.Value);
        }
    }
    private static nint? _WetMixOffset;

    public ref float WetMix
    {
        get
        {
            _WetMixOffset = _WetMixOffset ?? Schema.GetOffset(0x2E79C1E6D5453C15);
            return ref _Handle.AsRef<float>(_WetMixOffset!.Value);
        }
    }
    private static nint? _OutputGainOffset;

    public ref float OutputGain
    {
        get
        {
            _OutputGainOffset = _OutputGainOffset ?? Schema.GetOffset(0x2E79C1E673DB9445);
            return ref _Handle.AsRef<float>(_OutputGainOffset!.Value);
        }
    }
    private static nint? _TapsOffset;

    public ref float Taps
    {
        get
        {
            _TapsOffset = _TapsOffset ?? Schema.GetOffset(0x2E79C1E65C502CB9);
            return ref _Handle.AsRef<float>(_TapsOffset!.Value);
        }
    }

}