// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixEffectChainImpl : CMixPropertyBaseImpl, CMixEffectChain
{
    public CMixEffectChainImpl(nint handle) : base(handle) { }

    private static nint? _ChannelsOffset;

    public ref int Channels
    {
        get
        {
            _ChannelsOffset = _ChannelsOffset ?? Schema.GetOffset(0x69D309D65A815AD1);
            return ref _Handle.AsRef<int>(_ChannelsOffset!.Value);
        }
    }
    private static nint? _EffectNameOffset;

    public string EffectName
    {
        get
        {
            _EffectNameOffset = _EffectNameOffset ?? Schema.GetOffset(0x69D309D64DF4F5CF);
            return Schema.GetCUtlString(_Handle.Read<nint>(_EffectNameOffset!.Value));
        }
        set
        {
            _EffectNameOffset = _EffectNameOffset ?? Schema.GetOffset(0x69D309D64DF4F5CF);
            Schema.SetCUtlString(_Handle, _EffectNameOffset!.Value, value);
        }
    }
    private static nint? _XFadeOffset;

    public ref float XFade
    {
        get
        {
            _XFadeOffset = _XFadeOffset ?? Schema.GetOffset(0x69D309D68BA73023);
            return ref _Handle.AsRef<float>(_XFadeOffset!.Value);
        }
    }

}