// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixDelayImpulseResponseImpl : CMixPropertyBaseImpl, CMixDelayImpulseResponse
{
    public CMixDelayImpulseResponseImpl(nint handle) : base(handle) { }

    private static nint? _PreDelayMSOffset;

    public ref float PreDelayMS
    {
        get
        {
            _PreDelayMSOffset = _PreDelayMSOffset ?? Schema.GetOffset(0x5AA1DA0D4EFEC8E7);
            return ref _Handle.AsRef<float>(_PreDelayMSOffset!.Value);
        }
    }

}