// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixAudioSourceImpl : CMixPropertyBaseImpl, CMixAudioSource
{
    public CMixAudioSourceImpl(nint handle) : base(handle) { }

    private static nint? _KvContainerOffset;
    private SchemaUntypedField? _KvContainerInstance;

    public SchemaUntypedField KvContainer
    {
        get
        {
            _KvContainerOffset = _KvContainerOffset ?? Schema.GetOffset(0x7573D7ABE436AC5B);
            var instance = _KvContainerInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _KvContainerOffset!.Value);
            return instance;
        }
    }

}