// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixControlMeterImpl : CMixPropertyBaseImpl, CMixControlMeter
{
    public CMixControlMeterImpl(nint handle) : base(handle) { }

    private static nint? _ValueOffset;

    public ref float Value
    {
        get
        {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0xED357A368DFCB984);
            return ref _Handle.AsRef<float>(_ValueOffset!.Value);
        }
    }

}