// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CMixSplitterBlendImpl : CMixPropertyBaseImpl, CMixSplitterBlend
{
    public CMixSplitterBlendImpl(nint handle) : base(handle) { }

    private static nint? _LockAmountOffset;

    public ref float LockAmount
    {
        get
        {
            _LockAmountOffset = _LockAmountOffset ?? Schema.GetOffset(0x9B8D35AE2127E334);
            return ref _Handle.AsRef<float>(_LockAmountOffset!.Value);
        }
    }

}