// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNavPathCostImpl : INavPathCostImpl, CNavPathCost
{
    public CNavPathCostImpl(nint handle) : base(handle) { }

    private static nint? _AllowLaddersOffset;

    public ref bool AllowLadders
    {
        get
        {
            _AllowLaddersOffset = _AllowLaddersOffset ?? Schema.GetOffset(0x2BDEF75106C7F8EB);
            return ref _Handle.AsRef<bool>(_AllowLaddersOffset!.Value);
        }
    }
    private static nint? _CanFlyOffset;

    public ref bool CanFly
    {
        get
        {
            _CanFlyOffset = _CanFlyOffset ?? Schema.GetOffset(0x2BDEF751AADF0602);
            return ref _Handle.AsRef<bool>(_CanFlyOffset!.Value);
        }
    }
    private static nint? _CanSwimOffset;

    public ref bool CanSwim
    {
        get
        {
            _CanSwimOffset = _CanSwimOffset ?? Schema.GetOffset(0x2BDEF75125F17AAD);
            return ref _Handle.AsRef<bool>(_CanSwimOffset!.Value);
        }
    }
    private static nint? _WaterToGroundMaxHeightOffset;

    public ref float WaterToGroundMaxHeight
    {
        get
        {
            _WaterToGroundMaxHeightOffset = _WaterToGroundMaxHeightOffset ?? Schema.GetOffset(0x2BDEF7515273FD09);
            return ref _Handle.AsRef<float>(_WaterToGroundMaxHeightOffset!.Value);
        }
    }
    private static nint? _GroundToWaterMaxHeightOffset;

    public ref float GroundToWaterMaxHeight
    {
        get
        {
            _GroundToWaterMaxHeightOffset = _GroundToWaterMaxHeightOffset ?? Schema.GetOffset(0x2BDEF7518C4656E1);
            return ref _Handle.AsRef<float>(_GroundToWaterMaxHeightOffset!.Value);
        }
    }
    private static nint? _GroundToWaterTransitionDistanceOffset;

    public ref float GroundToWaterTransitionDistance
    {
        get
        {
            _GroundToWaterTransitionDistanceOffset = _GroundToWaterTransitionDistanceOffset ?? Schema.GetOffset(0x2BDEF751EA8FD398);
            return ref _Handle.AsRef<float>(_GroundToWaterTransitionDistanceOffset!.Value);
        }
    }
    private static nint? _WaterToGroundTransitionDistanceOffset;

    public ref float WaterToGroundTransitionDistance
    {
        get
        {
            _WaterToGroundTransitionDistanceOffset = _WaterToGroundTransitionDistanceOffset ?? Schema.GetOffset(0x2BDEF7512C0330D0);
            return ref _Handle.AsRef<float>(_WaterToGroundTransitionDistanceOffset!.Value);
        }
    }
    private static nint? _FlyingTransitionToleranceOffset;

    public ref float FlyingTransitionTolerance
    {
        get
        {
            _FlyingTransitionToleranceOffset = _FlyingTransitionToleranceOffset ?? Schema.GetOffset(0x2BDEF751EA3D127E);
            return ref _Handle.AsRef<float>(_FlyingTransitionToleranceOffset!.Value);
        }
    }
    private static nint? _OptimizeFlySpacePathfindsOffset;

    public ref bool OptimizeFlySpacePathfinds
    {
        get
        {
            _OptimizeFlySpacePathfindsOffset = _OptimizeFlySpacePathfindsOffset ?? Schema.GetOffset(0x2BDEF751407EAEF4);
            return ref _Handle.AsRef<bool>(_OptimizeFlySpacePathfindsOffset!.Value);
        }
    }
    private static nint? _StringPullFlySpacePathfindsOffset;

    public ref bool StringPullFlySpacePathfinds
    {
        get
        {
            _StringPullFlySpacePathfindsOffset = _StringPullFlySpacePathfindsOffset ?? Schema.GetOffset(0x2BDEF7519A681477);
            return ref _Handle.AsRef<bool>(_StringPullFlySpacePathfindsOffset!.Value);
        }
    }
    private static nint? _SupportsTransitionsOffset;

    public ref bool SupportsTransitions
    {
        get
        {
            _SupportsTransitionsOffset = _SupportsTransitionsOffset ?? Schema.GetOffset(0x2BDEF7518357F4DF);
            return ref _Handle.AsRef<bool>(_SupportsTransitionsOffset!.Value);
        }
    }
    private static nint? _TransitionPenaltyOffset;

    public ref float TransitionPenalty
    {
        get
        {
            _TransitionPenaltyOffset = _TransitionPenaltyOffset ?? Schema.GetOffset(0x2BDEF751840E6E35);
            return ref _Handle.AsRef<float>(_TransitionPenaltyOffset!.Value);
        }
    }

}