// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmBlendSpace1DImpl : SchemaClass, CNmBlendSpace1D
{
    public CNmBlendSpace1DImpl(nint handle) : base(handle) { }

    private static nint? _PointsOffset;

    public ref CUtlVector<CNmBlendSpace1D__Point_t> Points
    {
        get
        {
            _PointsOffset = _PointsOffset ?? Schema.GetOffset(0xF9411CE118915D66);
            return ref _Handle.AsRef<CUtlVector<CNmBlendSpace1D__Point_t>>(_PointsOffset!.Value);
        }
    }

}