// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmBlendSpace1D__Point_tImpl : SchemaClass, CNmBlendSpace1D__Point_t
{
    public CNmBlendSpace1D__Point_tImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x2EEFC4764D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x2EEFC4764D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _ValueOffset;

    public ref float Value
    {
        get
        {
            _ValueOffset = _ValueOffset ?? Schema.GetOffset(0x2EEFC4768DFCB984);
            return ref _Handle.AsRef<float>(_ValueOffset!.Value);
        }
    }
    private static nint? _PinIDOffset;
    private SchemaUntypedField? _PinIDInstance;

    public SchemaUntypedField PinID
    {
        get
        {
            _PinIDOffset = _PinIDOffset ?? Schema.GetOffset(0x2EEFC4764A4939B9);
            var instance = _PinIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _PinIDOffset!.Value);
            return instance;
        }
    }

}