// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_FrameSnapImpl : CNmClipDocEventImpl, CNmClipDocEvent_FrameSnap
{
    public CNmClipDocEvent_FrameSnapImpl(nint handle) : base(handle) { }

    private static nint? _FrameSnapModeOffset;

    public ref NmFrameSnapEventMode_t FrameSnapMode
    {
        get
        {
            _FrameSnapModeOffset = _FrameSnapModeOffset ?? Schema.GetOffset(0x363FA52D6C68AC59);
            return ref _Handle.AsRef<NmFrameSnapEventMode_t>(_FrameSnapModeOffset!.Value);
        }
    }

}