// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_EntityAttributeImpl : CNmClipDocEventImpl, CNmClipDocEvent_EntityAttribute
{
    public CNmClipDocEvent_EntityAttributeImpl(nint handle) : base(handle) { }

    private static nint? _TargetOffset;

    public ref CNmEventTargetEntity_t Target
    {
        get
        {
            _TargetOffset = _TargetOffset ?? Schema.GetOffset(0x3AEF4E39FA08A9E8);
            return ref _Handle.AsRef<CNmEventTargetEntity_t>(_TargetOffset!.Value);
        }
    }
    private static nint? _AttributeNameOffset;

    public string AttributeName
    {
        get
        {
            _AttributeNameOffset = _AttributeNameOffset ?? Schema.GetOffset(0x3AEF4E399168F02C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_AttributeNameOffset!.Value));
        }
        set
        {
            _AttributeNameOffset = _AttributeNameOffset ?? Schema.GetOffset(0x3AEF4E399168F02C);
            Schema.SetCUtlString(_Handle, _AttributeNameOffset!.Value, value);
        }
    }
    private static nint? _ValueTypeOffset;

    public ref CNmClipDocEvent_EntityAttribute_Type_t ValueType
    {
        get
        {
            _ValueTypeOffset = _ValueTypeOffset ?? Schema.GetOffset(0x3AEF4E39255F959E);
            return ref _Handle.AsRef<CNmClipDocEvent_EntityAttribute_Type_t>(_ValueTypeOffset!.Value);
        }
    }
    private static nint? _IntValueOffset;

    public ref int IntValue
    {
        get
        {
            _IntValueOffset = _IntValueOffset ?? Schema.GetOffset(0x3AEF4E39BF67A7DB);
            return ref _Handle.AsRef<int>(_IntValueOffset!.Value);
        }
    }
    private static nint? _FloatValueOffset;
    private SchemaUntypedField? _FloatValueInstance;

    public SchemaUntypedField FloatValue
    {
        get
        {
            _FloatValueOffset = _FloatValueOffset ?? Schema.GetOffset(0x3AEF4E39ADBE62AA);
            var instance = _FloatValueInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _FloatValueOffset!.Value);
            return instance;
        }
    }

}