// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_TransitionImpl : CNmClipDocEventImpl, CNmClipDocEvent_Transition
{
    public CNmClipDocEvent_TransitionImpl(nint handle) : base(handle) { }

    private static nint? _RuleOffset;

    public ref NmTransitionRule_t Rule
    {
        get
        {
            _RuleOffset = _RuleOffset ?? Schema.GetOffset(0xD7DD9F9BBA097173);
            return ref _Handle.AsRef<NmTransitionRule_t>(_RuleOffset!.Value);
        }
    }
    private static nint? _OptionalIDOffset;

    public string OptionalID
    {
        get
        {
            _OptionalIDOffset = _OptionalIDOffset ?? Schema.GetOffset(0xD7DD9F9BBBD372DC);
            return Schema.GetCUtlString(_Handle.Read<nint>(_OptionalIDOffset!.Value));
        }
        set
        {
            _OptionalIDOffset = _OptionalIDOffset ?? Schema.GetOffset(0xD7DD9F9BBBD372DC);
            Schema.SetCUtlString(_Handle, _OptionalIDOffset!.Value, value);
        }
    }

}