// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_RootMotionImpl : CNmClipDocEventImpl, CNmClipDocEvent_RootMotion
{
    public CNmClipDocEvent_RootMotionImpl(nint handle) : base(handle) { }

    private static nint? _BlendTimeSecondsOffset;

    public ref float BlendTimeSeconds
    {
        get
        {
            _BlendTimeSecondsOffset = _BlendTimeSecondsOffset ?? Schema.GetOffset(0xF4E7B3426D3A08FC);
            return ref _Handle.AsRef<float>(_BlendTimeSecondsOffset!.Value);
        }
    }

}