// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEvent_FootImpl : CNmClipDocEventImpl, CNmClipDocEvent_Foot
{
    public CNmClipDocEvent_FootImpl(nint handle) : base(handle) { }

    private static nint? _PhaseOffset;

    public ref NmFootPhase_t Phase
    {
        get
        {
            _PhaseOffset = _PhaseOffset ?? Schema.GetOffset(0x44C1A74C4846D318);
            return ref _Handle.AsRef<NmFootPhase_t>(_PhaseOffset!.Value);
        }
    }

}