// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmClipDocEventImpl : SchemaClass, CNmClipDocEvent
{
    public CNmClipDocEventImpl(nint handle) : base(handle) { }

    private static nint? _StartTimeOffset;

    public ref float StartTime
    {
        get
        {
            _StartTimeOffset = _StartTimeOffset ?? Schema.GetOffset(0x114E858767FE9DC4);
            return ref _Handle.AsRef<float>(_StartTimeOffset!.Value);
        }
    }
    private static nint? _DurationOffset;

    public ref float Duration
    {
        get
        {
            _DurationOffset = _DurationOffset ?? Schema.GetOffset(0x114E8587BC5E3BAB);
            return ref _Handle.AsRef<float>(_DurationOffset!.Value);
        }
    }

}