// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmFloatChannelDataImpl : SchemaClass, CNmFloatChannelData
{
    public CNmFloatChannelDataImpl(nint handle) : base(handle) { }

    private static nint? _SkeletonOffset;

    public ref CStrongHandle<InfoForResourceTypeCNmSkeleton> Skeleton
    {
        get
        {
            _SkeletonOffset = _SkeletonOffset ?? Schema.GetOffset(0x15A8736EE77F030E);
            return ref _Handle.AsRef<CStrongHandle<InfoForResourceTypeCNmSkeleton>>(_SkeletonOffset!.Value);
        }
    }
    private static nint? _SetIDOffset;

    public ref CGlobalSymbol SetID
    {
        get
        {
            _SetIDOffset = _SetIDOffset ?? Schema.GetOffset(0x15A8736EA6BAFC6E);
            return ref _Handle.AsRef<CGlobalSymbol>(_SetIDOffset!.Value);
        }
    }
    private static nint? _ChannelSettingsOffset;

    public ref CUtlVector<CNmFloatChannelData__ChannelSettings_t> ChannelSettings
    {
        get
        {
            _ChannelSettingsOffset = _ChannelSettingsOffset ?? Schema.GetOffset(0x15A8736EC7F9ACA9);
            return ref _Handle.AsRef<CUtlVector<CNmFloatChannelData__ChannelSettings_t>>(_ChannelSettingsOffset!.Value);
        }
    }
    private static nint? _CompressedDataOffset;

    public ref CUtlVector<ushort> CompressedData
    {
        get
        {
            _CompressedDataOffset = _CompressedDataOffset ?? Schema.GetOffset(0x15A8736ED28B783C);
            return ref _Handle.AsRef<CUtlVector<ushort>>(_CompressedDataOffset!.Value);
        }
    }
    private static nint? _CompressedOffsetsOffset;

    public ref CUtlVector<uint> CompressedOffsets
    {
        get
        {
            _CompressedOffsetsOffset = _CompressedOffsetsOffset ?? Schema.GetOffset(0x15A8736EAB9F5B74);
            return ref _Handle.AsRef<CUtlVector<uint>>(_CompressedOffsetsOffset!.Value);
        }
    }

}