// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocVelocityBlendNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocVelocityBlendNode
{
    public CNmGraphDocVelocityBlendNodeImpl(nint handle) : base(handle) { }

    private static nint? _AllowLoopingOffset;

    public ref bool AllowLooping
    {
        get
        {
            _AllowLoopingOffset = _AllowLoopingOffset ?? Schema.GetOffset(0xC4FCA08DFEB26D98);
            return ref _Handle.AsRef<bool>(_AllowLoopingOffset!.Value);
        }
    }

}