// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CnmGraphDocFollowBoneNode__CDataImpl : CNmGraphDocVariationDataNode__CDataImpl, CnmGraphDocFollowBoneNode__CData
{
    public CnmGraphDocFollowBoneNode__CDataImpl(nint handle) : base(handle) { }

    private static nint? _BoneNameOffset;

    public string BoneName
    {
        get
        {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0x9CBF9C7BFDEE0E0C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_BoneNameOffset!.Value));
        }
        set
        {
            _BoneNameOffset = _BoneNameOffset ?? Schema.GetOffset(0x9CBF9C7BFDEE0E0C);
            Schema.SetCUtlString(_Handle, _BoneNameOffset!.Value, value);
        }
    }
    private static nint? _FollowTargetBoneNameOffset;

    public string FollowTargetBoneName
    {
        get
        {
            _FollowTargetBoneNameOffset = _FollowTargetBoneNameOffset ?? Schema.GetOffset(0x9CBF9C7BE25E20D0);
            return Schema.GetCUtlString(_Handle.Read<nint>(_FollowTargetBoneNameOffset!.Value));
        }
        set
        {
            _FollowTargetBoneNameOffset = _FollowTargetBoneNameOffset ?? Schema.GetOffset(0x9CBF9C7BE25E20D0);
            Schema.SetCUtlString(_Handle, _FollowTargetBoneNameOffset!.Value, value);
        }
    }

}