// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocBlend2DNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocBlend2DNode
{
    public CNmGraphDocBlend2DNodeImpl(nint handle) : base(handle) { }

    private static nint? _BlendSpaceOffset;
    private CNmBlendSpace2DImpl? _BlendSpaceInstance;

    public CNmBlendSpace2D BlendSpace
    {
        get
        {
            _BlendSpaceOffset = _BlendSpaceOffset ?? Schema.GetOffset(0xC98099B69DCBC41E);
            var instance = _BlendSpaceInstance ??= new CNmBlendSpace2DImpl(0);
            instance.DangerousSetHandle(_Handle + _BlendSpaceOffset!.Value);
            return instance;
        }
    }
    private static nint? _AllowLoopingOffset;

    public ref bool AllowLooping
    {
        get
        {
            _AllowLoopingOffset = _AllowLoopingOffset ?? Schema.GetOffset(0xC98099B6FEB26D98);
            return ref _Handle.AsRef<bool>(_AllowLoopingOffset!.Value);
        }
    }

}