// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocEntryOverrideNodeImpl : CNmGraphDocResultNodeImpl, CNmGraphDocEntryOverrideNode
{
    public CNmGraphDocEntryOverrideNodeImpl(nint handle) : base(handle) { }

    private static nint? _StateIDOffset;
    private SchemaUntypedField? _StateIDInstance;

    public SchemaUntypedField StateID
    {
        get
        {
            _StateIDOffset = _StateIDOffset ?? Schema.GetOffset(0xB8E549EF5362B56B);
            var instance = _StateIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _StateIDOffset!.Value);
            return instance;
        }
    }

}