// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocFloatSpringNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocFloatSpringNode
{
    public CNmGraphDocFloatSpringNodeImpl(nint handle) : base(handle) { }

    private static nint? _HertzOffset;

    public ref float Hertz
    {
        get
        {
            _HertzOffset = _HertzOffset ?? Schema.GetOffset(0x62438CDC310B9C74);
            return ref _Handle.AsRef<float>(_HertzOffset!.Value);
        }
    }
    private static nint? _DampingRatioOffset;

    public ref float DampingRatio
    {
        get
        {
            _DampingRatioOffset = _DampingRatioOffset ?? Schema.GetOffset(0x62438CDCB40C859E);
            return ref _Handle.AsRef<float>(_DampingRatioOffset!.Value);
        }
    }
    private static nint? _UseStartValueOffset;

    public ref bool UseStartValue
    {
        get
        {
            _UseStartValueOffset = _UseStartValueOffset ?? Schema.GetOffset(0x62438CDC06DE6089);
            return ref _Handle.AsRef<bool>(_UseStartValueOffset!.Value);
        }
    }
    private static nint? _StartValueOffset;

    public ref float StartValue
    {
        get
        {
            _StartValueOffset = _StartValueOffset ?? Schema.GetOffset(0x62438CDC51C82C2A);
            return ref _Handle.AsRef<float>(_StartValueOffset!.Value);
        }
    }

}