// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocFloatRangeComparisonNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocFloatRangeComparisonNode
{
    public CNmGraphDocFloatRangeComparisonNodeImpl(nint handle) : base(handle) { }

    private static nint? _RangeOffset;
    private SchemaUntypedField? _RangeInstance;

    public SchemaUntypedField Range
    {
        get
        {
            _RangeOffset = _RangeOffset ?? Schema.GetOffset(0xEC9B7F873D639CF2);
            var instance = _RangeInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _RangeOffset!.Value);
            return instance;
        }
    }
    private static nint? _IsInclusiveCheckOffset;

    public ref bool IsInclusiveCheck
    {
        get
        {
            _IsInclusiveCheckOffset = _IsInclusiveCheckOffset ?? Schema.GetOffset(0xEC9B7F875FC3DE03);
            return ref _Handle.AsRef<bool>(_IsInclusiveCheckOffset!.Value);
        }
    }

}