// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocParameterReferenceNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocParameterReferenceNode
{
    public CNmGraphDocParameterReferenceNodeImpl(nint handle) : base(handle) { }

    private static nint? _ParameterUUIDOffset;
    private SchemaUntypedField? _ParameterUUIDInstance;

    public SchemaUntypedField ParameterUUID
    {
        get
        {
            _ParameterUUIDOffset = _ParameterUUIDOffset ?? Schema.GetOffset(0x65BFEBD12AC40923);
            var instance = _ParameterUUIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ParameterUUIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _ParameterValueTypeOffset;

    public ref NmGraphValueType_t ParameterValueType
    {
        get
        {
            _ParameterValueTypeOffset = _ParameterValueTypeOffset ?? Schema.GetOffset(0x65BFEBD11E6D4129);
            return ref _Handle.AsRef<NmGraphValueType_t>(_ParameterValueTypeOffset!.Value);
        }
    }
    private static nint? _ParameterNameOffset;

    public string ParameterName
    {
        get
        {
            _ParameterNameOffset = _ParameterNameOffset ?? Schema.GetOffset(0x65BFEBD10F5FEC93);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ParameterNameOffset!.Value));
        }
        set
        {
            _ParameterNameOffset = _ParameterNameOffset ?? Schema.GetOffset(0x65BFEBD10F5FEC93);
            Schema.SetCUtlString(_Handle, _ParameterNameOffset!.Value, value);
        }
    }
    private static nint? _ParameterGroupNameOffset;

    public string ParameterGroupName
    {
        get
        {
            _ParameterGroupNameOffset = _ParameterGroupNameOffset ?? Schema.GetOffset(0x65BFEBD10EA20E58);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ParameterGroupNameOffset!.Value));
        }
        set
        {
            _ParameterGroupNameOffset = _ParameterGroupNameOffset ?? Schema.GetOffset(0x65BFEBD10EA20E58);
            Schema.SetCUtlString(_Handle, _ParameterGroupNameOffset!.Value, value);
        }
    }

}