// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocFlowGraph__Connection_tImpl : SchemaClass, CNmGraphDocFlowGraph__Connection_t
{
    public CNmGraphDocFlowGraph__Connection_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;
    private SchemaUntypedField? _IDInstance;

    public SchemaUntypedField ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0xD0AA0FB095066900);
            var instance = _IDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IDOffset!.Value);
            return instance;
        }
    }
    private static nint? _FromNodeIDOffset;
    private SchemaUntypedField? _FromNodeIDInstance;

    public SchemaUntypedField FromNodeID
    {
        get
        {
            _FromNodeIDOffset = _FromNodeIDOffset ?? Schema.GetOffset(0xD0AA0FB02405D988);
            var instance = _FromNodeIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _FromNodeIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _OutputPinIDOffset;
    private SchemaUntypedField? _OutputPinIDInstance;

    public SchemaUntypedField OutputPinID
    {
        get
        {
            _OutputPinIDOffset = _OutputPinIDOffset ?? Schema.GetOffset(0xD0AA0FB0ED9B729E);
            var instance = _OutputPinIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _OutputPinIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _ToNodeIDOffset;
    private SchemaUntypedField? _ToNodeIDInstance;

    public SchemaUntypedField ToNodeID
    {
        get
        {
            _ToNodeIDOffset = _ToNodeIDOffset ?? Schema.GetOffset(0xD0AA0FB0794D3FBD);
            var instance = _ToNodeIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _ToNodeIDOffset!.Value);
            return instance;
        }
    }
    private static nint? _InputPinIDOffset;
    private SchemaUntypedField? _InputPinIDInstance;

    public SchemaUntypedField InputPinID
    {
        get
        {
            _InputPinIDOffset = _InputPinIDOffset ?? Schema.GetOffset(0xD0AA0FB06E153BBF);
            var instance = _InputPinIDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _InputPinIDOffset!.Value);
            return instance;
        }
    }

}