// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocTargetWarpNodeImpl : CNmGraphDocVariationDataNodeImpl, CNmGraphDocTargetWarpNode
{
    public CNmGraphDocTargetWarpNodeImpl(nint handle) : base(handle) { }

    private static nint? _TargetUpdateRuleOffset;

    public ref CNmTargetWarpNode__TargetUpdateRule_t TargetUpdateRule
    {
        get
        {
            _TargetUpdateRuleOffset = _TargetUpdateRuleOffset ?? Schema.GetOffset(0x9F54D6063E2C706F);
            return ref _Handle.AsRef<CNmTargetWarpNode__TargetUpdateRule_t>(_TargetUpdateRuleOffset!.Value);
        }
    }
    private static nint? _AllowTargetUpdateOffset;

    public ref bool AllowTargetUpdate
    {
        get
        {
            _AllowTargetUpdateOffset = _AllowTargetUpdateOffset ?? Schema.GetOffset(0x9F54D6068A9C0712);
            return ref _Handle.AsRef<bool>(_AllowTargetUpdateOffset!.Value);
        }
    }
    private static nint? _AlignWithTargetAtLastWarpEventOffset;

    public ref bool AlignWithTargetAtLastWarpEvent
    {
        get
        {
            _AlignWithTargetAtLastWarpEventOffset = _AlignWithTargetAtLastWarpEventOffset ?? Schema.GetOffset(0x9F54D6066D2BBBD0);
            return ref _Handle.AsRef<bool>(_AlignWithTargetAtLastWarpEventOffset!.Value);
        }
    }
    private static nint? _SamplingModeOffset;

    public ref CNmRootMotionData__SamplingMode_t SamplingMode
    {
        get
        {
            _SamplingModeOffset = _SamplingModeOffset ?? Schema.GetOffset(0x9F54D606DDB31BE3);
            return ref _Handle.AsRef<CNmRootMotionData__SamplingMode_t>(_SamplingModeOffset!.Value);
        }
    }
    private static nint? _SamplingPositionErrorThresholdOffset;

    public ref float SamplingPositionErrorThreshold
    {
        get
        {
            _SamplingPositionErrorThresholdOffset = _SamplingPositionErrorThresholdOffset ?? Schema.GetOffset(0x9F54D6069B4C2A98);
            return ref _Handle.AsRef<float>(_SamplingPositionErrorThresholdOffset!.Value);
        }
    }
    private static nint? _MaxTangentLengthOffset;

    public ref float MaxTangentLength
    {
        get
        {
            _MaxTangentLengthOffset = _MaxTangentLengthOffset ?? Schema.GetOffset(0x9F54D60646EAA410);
            return ref _Handle.AsRef<float>(_MaxTangentLengthOffset!.Value);
        }
    }
    private static nint? _LerpFallbackDistanceThresholdOffset;

    public ref float LerpFallbackDistanceThreshold
    {
        get
        {
            _LerpFallbackDistanceThresholdOffset = _LerpFallbackDistanceThresholdOffset ?? Schema.GetOffset(0x9F54D606BBC41F32);
            return ref _Handle.AsRef<float>(_LerpFallbackDistanceThresholdOffset!.Value);
        }
    }
    private static nint? _TargetUpdateDistanceThresholdDegreesOffset;

    public ref float TargetUpdateDistanceThresholdDegrees
    {
        get
        {
            _TargetUpdateDistanceThresholdDegreesOffset = _TargetUpdateDistanceThresholdDegreesOffset ?? Schema.GetOffset(0x9F54D60691F16158);
            return ref _Handle.AsRef<float>(_TargetUpdateDistanceThresholdDegreesOffset!.Value);
        }
    }
    private static nint? _TargetUpdateAngleThresholdDegreesOffset;

    public ref float TargetUpdateAngleThresholdDegrees
    {
        get
        {
            _TargetUpdateAngleThresholdDegreesOffset = _TargetUpdateAngleThresholdDegreesOffset ?? Schema.GetOffset(0x9F54D6066D1A0A7E);
            return ref _Handle.AsRef<float>(_TargetUpdateAngleThresholdDegreesOffset!.Value);
        }
    }

}