// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocGraphImpl : SchemaClass, CNmGraphDocGraph
{
    public CNmGraphDocGraphImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;
    private SchemaUntypedField? _IDInstance;

    public SchemaUntypedField ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0xDCDC103395066900);
            var instance = _IDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IDOffset!.Value);
            return instance;
        }
    }
    private static nint? _NodesOffset;

    public ref CUtlVector<PointerTo<CNmGraphDocNode>> Nodes
    {
        get
        {
            _NodesOffset = _NodesOffset ?? Schema.GetOffset(0xDCDC1033780F027A);
            return ref _Handle.AsRef<CUtlVector<PointerTo<CNmGraphDocNode>>>(_NodesOffset!.Value);
        }
    }
    private static nint? _GraphTypeOffset;

    public ref NmGraphDocGraphType_t GraphType
    {
        get
        {
            _GraphTypeOffset = _GraphTypeOffset ?? Schema.GetOffset(0xDCDC1033EDFA861F);
            return ref _Handle.AsRef<NmGraphDocGraphType_t>(_GraphTypeOffset!.Value);
        }
    }
    private static nint? _ViewOffsetOffset;

    public ref Vector2D ViewOffset
    {
        get
        {
            _ViewOffsetOffset = _ViewOffsetOffset ?? Schema.GetOffset(0xDCDC10337DABD58B);
            return ref _Handle.AsRef<Vector2D>(_ViewOffsetOffset!.Value);
        }
    }
    private static nint? _ViewZoomOffset;

    public ref float ViewZoom
    {
        get
        {
            _ViewZoomOffset = _ViewZoomOffset ?? Schema.GetOffset(0xDCDC1033FCC38C81);
            return ref _Handle.AsRef<float>(_ViewZoomOffset!.Value);
        }
    }

}