// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocCachedTargetNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocCachedTargetNode
{
    public CNmGraphDocCachedTargetNodeImpl(nint handle) : base(handle) { }

    private static nint? _ModeOffset;

    public ref NmCachedValueMode_t Mode
    {
        get
        {
            _ModeOffset = _ModeOffset ?? Schema.GetOffset(0x5A5C3D1E90FD5BB2);
            return ref _Handle.AsRef<NmCachedValueMode_t>(_ModeOffset!.Value);
        }
    }

}