// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CnmGraphDocTwoBoneIKNode__CDataImpl : CNmGraphDocVariationDataNode__CDataImpl, CnmGraphDocTwoBoneIKNode__CData
{
    public CnmGraphDocTwoBoneIKNode__CDataImpl(nint handle) : base(handle) { }

    private static nint? _EffectorBoneNameOffset;

    public string EffectorBoneName
    {
        get
        {
            _EffectorBoneNameOffset = _EffectorBoneNameOffset ?? Schema.GetOffset(0xBC56ECC0507D3A80);
            return Schema.GetCUtlString(_Handle.Read<nint>(_EffectorBoneNameOffset!.Value));
        }
        set
        {
            _EffectorBoneNameOffset = _EffectorBoneNameOffset ?? Schema.GetOffset(0xBC56ECC0507D3A80);
            Schema.SetCUtlString(_Handle, _EffectorBoneNameOffset!.Value, value);
        }
    }
    private static nint? _BlendTimeSecondsOffset;

    public ref float BlendTimeSeconds
    {
        get
        {
            _BlendTimeSecondsOffset = _BlendTimeSecondsOffset ?? Schema.GetOffset(0xBC56ECC06D3A08FC);
            return ref _Handle.AsRef<float>(_BlendTimeSecondsOffset!.Value);
        }
    }

}