// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocument__DebugParameterSet_tImpl : SchemaClass, CNmGraphDocument__DebugParameterSet_t
{
    public CNmGraphDocument__DebugParameterSet_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;

    public ref CGlobalSymbol ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0xAF145ED995066900);
            return ref _Handle.AsRef<CGlobalSymbol>(_IDOffset!.Value);
        }
    }
    private static nint? _BoolValuesOffset;

    public ref CUtlLeanVector<SchemaUntypedField, int> BoolValues
    {
        get
        {
            _BoolValuesOffset = _BoolValuesOffset ?? Schema.GetOffset(0xAF145ED957C27AE3);
            return ref _Handle.AsRef<CUtlLeanVector<SchemaUntypedField, int>>(_BoolValuesOffset!.Value);
        }
    }
    private static nint? _FloatValuesOffset;

    public ref CUtlLeanVector<SchemaUntypedField, int> FloatValues
    {
        get
        {
            _FloatValuesOffset = _FloatValuesOffset ?? Schema.GetOffset(0xAF145ED925D898FB);
            return ref _Handle.AsRef<CUtlLeanVector<SchemaUntypedField, int>>(_FloatValuesOffset!.Value);
        }
    }
    private static nint? _IDValuesOffset;

    public ref CUtlLeanVector<SchemaUntypedField, int> IDValues
    {
        get
        {
            _IDValuesOffset = _IDValuesOffset ?? Schema.GetOffset(0xAF145ED906EC5C66);
            return ref _Handle.AsRef<CUtlLeanVector<SchemaUntypedField, int>>(_IDValuesOffset!.Value);
        }
    }
    private static nint? _VectorValuesOffset;

    public ref CUtlLeanVector<SchemaUntypedField, int> VectorValues
    {
        get
        {
            _VectorValuesOffset = _VectorValuesOffset ?? Schema.GetOffset(0xAF145ED91FBF8A28);
            return ref _Handle.AsRef<CUtlLeanVector<SchemaUntypedField, int>>(_VectorValuesOffset!.Value);
        }
    }
    private static nint? _TargetValuesOffset;

    public ref CUtlLeanVector<SchemaUntypedField, int> TargetValues
    {
        get
        {
            _TargetValuesOffset = _TargetValuesOffset ?? Schema.GetOffset(0xAF145ED9913AEBFE);
            return ref _Handle.AsRef<CUtlLeanVector<SchemaUntypedField, int>>(_TargetValuesOffset!.Value);
        }
    }

}