// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocCommentNodeImpl : CNmGraphDocNodeImpl, CNmGraphDocCommentNode
{
    public CNmGraphDocCommentNodeImpl(nint handle) : base(handle) { }

    private static nint? _SizeOffset;

    public ref Vector2D Size
    {
        get
        {
            _SizeOffset = _SizeOffset ?? Schema.GetOffset(0x1961982EE3F672FC);
            return ref _Handle.AsRef<Vector2D>(_SizeOffset!.Value);
        }
    }
    private static nint? _CommentOffset;

    public string Comment
    {
        get
        {
            _CommentOffset = _CommentOffset ?? Schema.GetOffset(0x1961982E3F52117E);
            return Schema.GetCUtlString(_Handle.Read<nint>(_CommentOffset!.Value));
        }
        set
        {
            _CommentOffset = _CommentOffset ?? Schema.GetOffset(0x1961982E3F52117E);
            Schema.SetCUtlString(_Handle, _CommentOffset!.Value, value);
        }
    }
    private static nint? _NodeColorOffset;

    public ref Color NodeColor
    {
        get
        {
            _NodeColorOffset = _NodeColorOffset ?? Schema.GetOffset(0x1961982ED74C1AA0);
            return ref _Handle.AsRef<Color>(_NodeColorOffset!.Value);
        }
    }

}