// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocStateNode__TimedStateEvent_tImpl : SchemaClass, CNmGraphDocStateNode__TimedStateEvent_t
{
    public CNmGraphDocStateNode__TimedStateEvent_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;

    public ref CGlobalSymbol ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0x4825D24995066900);
            return ref _Handle.AsRef<CGlobalSymbol>(_IDOffset!.Value);
        }
    }
    private static nint? _TypeOffset;

    public ref CNmGraphDocStateNode__TimedStateEventType_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0x4825D2490F04B4ED);
            return ref _Handle.AsRef<CNmGraphDocStateNode__TimedStateEventType_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _ComparisonOperatorOffset;

    public ref CNmStateNode__TimedEvent_t__Comparison_t ComparisonOperator
    {
        get
        {
            _ComparisonOperatorOffset = _ComparisonOperatorOffset ?? Schema.GetOffset(0x4825D24923E70A14);
            return ref _Handle.AsRef<CNmStateNode__TimedEvent_t__Comparison_t>(_ComparisonOperatorOffset!.Value);
        }
    }
    private static nint? _TimeValueSecondsOffset;

    public ref float TimeValueSeconds
    {
        get
        {
            _TimeValueSecondsOffset = _TimeValueSecondsOffset ?? Schema.GetOffset(0x4825D2493B175F1C);
            return ref _Handle.AsRef<float>(_TimeValueSecondsOffset!.Value);
        }
    }

}