// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocDataDictionary__IDSet_tImpl : SchemaClass, CNmGraphDocDataDictionary__IDSet_t
{
    public CNmGraphDocDataDictionary__IDSet_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;
    private SchemaUntypedField? _IDInstance;

    public SchemaUntypedField ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0x7842FBB795066900);
            var instance = _IDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IDOffset!.Value);
            return instance;
        }
    }
    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x7842FBB74D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0x7842FBB74D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _GraphIDsOffset;

    public ref CUtlVector<CGlobalSymbol> GraphIDs
    {
        get
        {
            _GraphIDsOffset = _GraphIDsOffset ?? Schema.GetOffset(0x7842FBB7BA5A365B);
            return ref _Handle.AsRef<CUtlVector<CGlobalSymbol>>(_GraphIDsOffset!.Value);
        }
    }

}