// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CnmGraphDocFollowBoneNodeImpl : CNmGraphDocVariationDataNodeImpl, CnmGraphDocFollowBoneNode
{
    public CnmGraphDocFollowBoneNodeImpl(nint handle) : base(handle) { }

    private static nint? _ModeOffset;

    public ref NmFollowBoneMode_t Mode
    {
        get
        {
            _ModeOffset = _ModeOffset ?? Schema.GetOffset(0x2C56403E90FD5BB2);
            return ref _Handle.AsRef<NmFollowBoneMode_t>(_ModeOffset!.Value);
        }
    }

}