// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocGraphEventConditionNode__Condition_tImpl : SchemaClass, CNmGraphDocGraphEventConditionNode__Condition_t
{
    public CNmGraphDocGraphEventConditionNode__Condition_tImpl(nint handle) : base(handle) { }

    private static nint? _EventIDOffset;

    public ref CGlobalSymbol EventID
    {
        get
        {
            _EventIDOffset = _EventIDOffset ?? Schema.GetOffset(0xF9A0B7649D798A72);
            return ref _Handle.AsRef<CGlobalSymbol>(_EventIDOffset!.Value);
        }
    }
    private static nint? _TypeOffset;

    public ref NmGraphEventTypeCondition_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0xF9A0B7640F04B4ED);
            return ref _Handle.AsRef<NmGraphEventTypeCondition_t>(_TypeOffset!.Value);
        }
    }

}