// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocVariationDataNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocVariationDataNode
{
    public CNmGraphDocVariationDataNodeImpl(nint handle) : base(handle) { }

    private static nint? _DefaultVariationDataOffset;
    private CNmGraphDocVariationDataNode__CDataImpl? _DefaultVariationDataInstance;

    public CNmGraphDocVariationDataNode__CData? DefaultVariationData
    {
        get
        {
            _DefaultVariationDataOffset = _DefaultVariationDataOffset ?? Schema.GetOffset(0xC41C7EC7E001FD);
            var ptr = _Handle.Read<nint>(_DefaultVariationDataOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _DefaultVariationDataInstance ??= new CNmGraphDocVariationDataNode__CDataImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }
    private static nint? _OverridesOffset;

    public ref CUtlVector<CNmGraphDocVariationDataNode__OverrideValue_t> Overrides
    {
        get
        {
            _OverridesOffset = _OverridesOffset ?? Schema.GetOffset(0xC41C7EEC1C75EA);
            return ref _Handle.AsRef<CUtlVector<CNmGraphDocVariationDataNode__OverrideValue_t>>(_OverridesOffset!.Value);
        }
    }
    private static nint? _DefaultResourceNameOffset;
    private SchemaUntypedField? _DefaultResourceNameInstance;

    public SchemaUntypedField DefaultResourceName
    {
        get
        {
            _DefaultResourceNameOffset = _DefaultResourceNameOffset ?? Schema.GetOffset(0xC41C7E5D152705);
            var instance = _DefaultResourceNameInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _DefaultResourceNameOffset!.Value);
            return instance;
        }
    }

}