// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocIDComparisonNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocIDComparisonNode
{
    public CNmGraphDocIDComparisonNodeImpl(nint handle) : base(handle) { }

    private static nint? _ComparisonOffset;

    public ref CNmIDComparisonNode__Comparison_t Comparison
    {
        get
        {
            _ComparisonOffset = _ComparisonOffset ?? Schema.GetOffset(0xC38D81AD897F8DE4);
            return ref _Handle.AsRef<CNmIDComparisonNode__Comparison_t>(_ComparisonOffset!.Value);
        }
    }
    private static nint? _ValuesOffset;

    public ref CUtlVector<CGlobalSymbol> Values
    {
        get
        {
            _ValuesOffset = _ValuesOffset ?? Schema.GetOffset(0xC38D81ADFBEDDADB);
            return ref _Handle.AsRef<CUtlVector<CGlobalSymbol>>(_ValuesOffset!.Value);
        }
    }

}