// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocTimeConditionNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocTimeConditionNode
{
    public CNmGraphDocTimeConditionNodeImpl(nint handle) : base(handle) { }

    private static nint? _ComparandOffset;

    public ref float Comparand
    {
        get
        {
            _ComparandOffset = _ComparandOffset ?? Schema.GetOffset(0x6CA4DF950CF10B48);
            return ref _Handle.AsRef<float>(_ComparandOffset!.Value);
        }
    }
    private static nint? _TypeOffset;

    public ref CNmTimeConditionNode__ComparisonType_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0x6CA4DF950F04B4ED);
            return ref _Handle.AsRef<CNmTimeConditionNode__ComparisonType_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _OperatorOffset;

    public ref CNmTimeConditionNode__Operator_t Operator
    {
        get
        {
            _OperatorOffset = _OperatorOffset ?? Schema.GetOffset(0x6CA4DF958ABE049D);
            return ref _Handle.AsRef<CNmTimeConditionNode__Operator_t>(_OperatorOffset!.Value);
        }
    }

}