// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocTransitionNodeImpl : CNmGraphDocResultNodeImpl, CNmGraphDocTransitionNode
{
    public CNmGraphDocTransitionNodeImpl(nint handle) : base(handle) { }

    private static nint? _DurationSecondsOffset;

    public ref float DurationSeconds
    {
        get
        {
            _DurationSecondsOffset = _DurationSecondsOffset ?? Schema.GetOffset(0x4A9B4C52917797C0);
            return ref _Handle.AsRef<float>(_DurationSecondsOffset!.Value);
        }
    }
    private static nint? _ClampDurationToSourceOffset;

    public ref bool ClampDurationToSource
    {
        get
        {
            _ClampDurationToSourceOffset = _ClampDurationToSourceOffset ?? Schema.GetOffset(0x4A9B4C52BF5EDDA0);
            return ref _Handle.AsRef<bool>(_ClampDurationToSourceOffset!.Value);
        }
    }
    private static nint? _RootMotionBlendOffset;

    public ref NmRootMotionBlendMode_t RootMotionBlend
    {
        get
        {
            _RootMotionBlendOffset = _RootMotionBlendOffset ?? Schema.GetOffset(0x4A9B4C528DADB2AE);
            return ref _Handle.AsRef<NmRootMotionBlendMode_t>(_RootMotionBlendOffset!.Value);
        }
    }
    private static nint? _BlendWeightEasingOffset;

    public ref NmEasingOperation_t BlendWeightEasing
    {
        get
        {
            _BlendWeightEasingOffset = _BlendWeightEasingOffset ?? Schema.GetOffset(0x4A9B4C52E7454DC5);
            return ref _Handle.AsRef<NmEasingOperation_t>(_BlendWeightEasingOffset!.Value);
        }
    }
    private static nint? _BoneMaskBlendInTimePercentageOffset;

    public ref float BoneMaskBlendInTimePercentage
    {
        get
        {
            _BoneMaskBlendInTimePercentageOffset = _BoneMaskBlendInTimePercentageOffset ?? Schema.GetOffset(0x4A9B4C521F75ED42);
            return ref _Handle.AsRef<float>(_BoneMaskBlendInTimePercentageOffset!.Value);
        }
    }
    private static nint? _TimeMatchModeOffset;

    public ref CNmGraphDocTransitionNode__TimeMatchMode_t TimeMatchMode
    {
        get
        {
            _TimeMatchModeOffset = _TimeMatchModeOffset ?? Schema.GetOffset(0x4A9B4C52C601AAEA);
            return ref _Handle.AsRef<CNmGraphDocTransitionNode__TimeMatchMode_t>(_TimeMatchModeOffset!.Value);
        }
    }
    private static nint? _TimeOffsetOffset;

    public ref float TimeOffset
    {
        get
        {
            _TimeOffsetOffset = _TimeOffsetOffset ?? Schema.GetOffset(0x4A9B4C526F4EE629);
            return ref _Handle.AsRef<float>(_TimeOffsetOffset!.Value);
        }
    }
    private static nint? _CanBeForcedOffset;

    public ref bool CanBeForced
    {
        get
        {
            _CanBeForcedOffset = _CanBeForcedOffset ?? Schema.GetOffset(0x4A9B4C52B6EB0555);
            return ref _Handle.AsRef<bool>(_CanBeForcedOffset!.Value);
        }
    }

}