// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocParameterizedSelectorNodeImpl : CNmGraphDocVariationDataNodeImpl, CNmGraphDocParameterizedSelectorNode
{
    public CNmGraphDocParameterizedSelectorNodeImpl(nint handle) : base(handle) { }

    private static nint? _OptionLabelsOffset;

    public ref CUtlVector<CUtlString> OptionLabels
    {
        get
        {
            _OptionLabelsOffset = _OptionLabelsOffset ?? Schema.GetOffset(0x72BF64F3D071C433);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_OptionLabelsOffset!.Value);
        }
    }
    private static nint? _IgnoreInvalidOptionsOffset;

    public ref bool IgnoreInvalidOptions
    {
        get
        {
            _IgnoreInvalidOptionsOffset = _IgnoreInvalidOptionsOffset ?? Schema.GetOffset(0x72BF64F3507C679C);
            return ref _Handle.AsRef<bool>(_IgnoreInvalidOptionsOffset!.Value);
        }
    }

}