// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocFlowGraphImpl : CNmGraphDocGraphImpl, CNmGraphDocFlowGraph
{
    public CNmGraphDocFlowGraphImpl(nint handle) : base(handle) { }

    private static nint? _ConnectionsOffset;

    public ref CUtlVector<CNmGraphDocFlowGraph__Connection_t> Connections
    {
        get
        {
            _ConnectionsOffset = _ConnectionsOffset ?? Schema.GetOffset(0x47E1D81358F33FBE);
            return ref _Handle.AsRef<CUtlVector<CNmGraphDocFlowGraph__Connection_t>>(_ConnectionsOffset!.Value);
        }
    }

}