// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmGraphDocIDEventNodeImpl : CNmGraphDocFlowNodeImpl, CNmGraphDocIDEventNode
{
    public CNmGraphDocIDEventNodeImpl(nint handle) : base(handle) { }

    private static nint? _DefaultValueOffset;

    public ref CGlobalSymbol DefaultValue
    {
        get
        {
            _DefaultValueOffset = _DefaultValueOffset ?? Schema.GetOffset(0x8E80B558BBE0341F);
            return ref _Handle.AsRef<CGlobalSymbol>(_DefaultValueOffset!.Value);
        }
    }
    private static nint? _LimitSearchToSourceStateOffset;

    public ref bool LimitSearchToSourceState
    {
        get
        {
            _LimitSearchToSourceStateOffset = _LimitSearchToSourceStateOffset ?? Schema.GetOffset(0x8E80B55815D4BD01);
            return ref _Handle.AsRef<bool>(_LimitSearchToSourceStateOffset!.Value);
        }
    }
    private static nint? _PriorityRuleOffset;

    public ref NmEventPriorityRule_t PriorityRule
    {
        get
        {
            _PriorityRuleOffset = _PriorityRuleOffset ?? Schema.GetOffset(0x8E80B55816C8898F);
            return ref _Handle.AsRef<NmEventPriorityRule_t>(_PriorityRuleOffset!.Value);
        }
    }
    private static nint? _IgnoreInactiveBranchEventsOffset;

    public ref bool IgnoreInactiveBranchEvents
    {
        get
        {
            _IgnoreInactiveBranchEventsOffset = _IgnoreInactiveBranchEventsOffset ?? Schema.GetOffset(0x8E80B55840B77877);
            return ref _Handle.AsRef<bool>(_IgnoreInactiveBranchEventsOffset!.Value);
        }
    }

}