// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CnmGraphDocSpeedScaleNodeImpl : CNmGraphDocFlowNodeImpl, CnmGraphDocSpeedScaleNode
{
    public CnmGraphDocSpeedScaleNodeImpl(nint handle) : base(handle) { }

    private static nint? _MultiplierOffset;

    public ref float Multiplier
    {
        get
        {
            _MultiplierOffset = _MultiplierOffset ?? Schema.GetOffset(0x2B9B7912A8E53394);
            return ref _Handle.AsRef<float>(_MultiplierOffset!.Value);
        }
    }

}