// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CNmSkeletonDocument__SecondarySkeleton_tImpl : SchemaClass, CNmSkeletonDocument__SecondarySkeleton_t
{
    public CNmSkeletonDocument__SecondarySkeleton_tImpl(nint handle) : base(handle) { }

    private static nint? _SkeletonOffset;

    public string Skeleton
    {
        get
        {
            _SkeletonOffset = _SkeletonOffset ?? Schema.GetOffset(0xEEFE71E77F030E);
            return Schema.GetCUtlString(_Handle.Read<nint>(_SkeletonOffset!.Value));
        }
        set
        {
            _SkeletonOffset = _SkeletonOffset ?? Schema.GetOffset(0xEEFE71E77F030E);
            Schema.SetCUtlString(_Handle, _SkeletonOffset!.Value, value);
        }
    }
    private static nint? _AttachToBoneIDOffset;

    public ref CGlobalSymbol AttachToBoneID
    {
        get
        {
            _AttachToBoneIDOffset = _AttachToBoneIDOffset ?? Schema.GetOffset(0xEEFE71B2F06B3A);
            return ref _Handle.AsRef<CGlobalSymbol>(_AttachToBoneIDOffset!.Value);
        }
    }

}