// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CompositeMaterialInputLooseVariable_tImpl : SchemaClass, CompositeMaterialInputLooseVariable_t
{
    public CompositeMaterialInputLooseVariable_tImpl(nint handle) : base(handle) { }

    private static nint? _StrNameOffset;

    public string StrName
    {
        get
        {
            _StrNameOffset = _StrNameOffset ?? Schema.GetOffset(0xAB8A0BE8BF1A7E13);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrNameOffset!.Value));
        }
        set
        {
            _StrNameOffset = _StrNameOffset ?? Schema.GetOffset(0xAB8A0BE8BF1A7E13);
            Schema.SetCUtlString(_Handle, _StrNameOffset!.Value, value);
        }
    }
    private static nint? _ExposeExternallyOffset;

    public ref bool ExposeExternally
    {
        get
        {
            _ExposeExternallyOffset = _ExposeExternallyOffset ?? Schema.GetOffset(0xAB8A0BE852CA5AD1);
            return ref _Handle.AsRef<bool>(_ExposeExternallyOffset!.Value);
        }
    }
    private static nint? _StrExposedFriendlyNameOffset;

    public string StrExposedFriendlyName
    {
        get
        {
            _StrExposedFriendlyNameOffset = _StrExposedFriendlyNameOffset ?? Schema.GetOffset(0xAB8A0BE89897332C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrExposedFriendlyNameOffset!.Value));
        }
        set
        {
            _StrExposedFriendlyNameOffset = _StrExposedFriendlyNameOffset ?? Schema.GetOffset(0xAB8A0BE89897332C);
            Schema.SetCUtlString(_Handle, _StrExposedFriendlyNameOffset!.Value, value);
        }
    }
    private static nint? _StrExposedFriendlyGroupNameOffset;

    public string StrExposedFriendlyGroupName
    {
        get
        {
            _StrExposedFriendlyGroupNameOffset = _StrExposedFriendlyGroupNameOffset ?? Schema.GetOffset(0xAB8A0BE8FD28A195);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrExposedFriendlyGroupNameOffset!.Value));
        }
        set
        {
            _StrExposedFriendlyGroupNameOffset = _StrExposedFriendlyGroupNameOffset ?? Schema.GetOffset(0xAB8A0BE8FD28A195);
            Schema.SetCUtlString(_Handle, _StrExposedFriendlyGroupNameOffset!.Value, value);
        }
    }
    private static nint? _ExposedVariableIsFixedRangeOffset;

    public ref bool ExposedVariableIsFixedRange
    {
        get
        {
            _ExposedVariableIsFixedRangeOffset = _ExposedVariableIsFixedRangeOffset ?? Schema.GetOffset(0xAB8A0BE8BD2C8944);
            return ref _Handle.AsRef<bool>(_ExposedVariableIsFixedRangeOffset!.Value);
        }
    }
    private static nint? _StrExposedVisibleWhenTrueOffset;

    public string StrExposedVisibleWhenTrue
    {
        get
        {
            _StrExposedVisibleWhenTrueOffset = _StrExposedVisibleWhenTrueOffset ?? Schema.GetOffset(0xAB8A0BE8088F76C6);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrExposedVisibleWhenTrueOffset!.Value));
        }
        set
        {
            _StrExposedVisibleWhenTrueOffset = _StrExposedVisibleWhenTrueOffset ?? Schema.GetOffset(0xAB8A0BE8088F76C6);
            Schema.SetCUtlString(_Handle, _StrExposedVisibleWhenTrueOffset!.Value, value);
        }
    }
    private static nint? _StrExposedHiddenWhenTrueOffset;

    public string StrExposedHiddenWhenTrue
    {
        get
        {
            _StrExposedHiddenWhenTrueOffset = _StrExposedHiddenWhenTrueOffset ?? Schema.GetOffset(0xAB8A0BE84FD98974);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrExposedHiddenWhenTrueOffset!.Value));
        }
        set
        {
            _StrExposedHiddenWhenTrueOffset = _StrExposedHiddenWhenTrueOffset ?? Schema.GetOffset(0xAB8A0BE84FD98974);
            Schema.SetCUtlString(_Handle, _StrExposedHiddenWhenTrueOffset!.Value, value);
        }
    }
    private static nint? _StrExposedValueListOffset;

    public string StrExposedValueList
    {
        get
        {
            _StrExposedValueListOffset = _StrExposedValueListOffset ?? Schema.GetOffset(0xAB8A0BE85AFE334D);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrExposedValueListOffset!.Value));
        }
        set
        {
            _StrExposedValueListOffset = _StrExposedValueListOffset ?? Schema.GetOffset(0xAB8A0BE85AFE334D);
            Schema.SetCUtlString(_Handle, _StrExposedValueListOffset!.Value, value);
        }
    }
    private static nint? _VariableTypeOffset;

    public ref CompositeMaterialInputLooseVariableType_t VariableType
    {
        get
        {
            _VariableTypeOffset = _VariableTypeOffset ?? Schema.GetOffset(0xAB8A0BE874B2A8F1);
            return ref _Handle.AsRef<CompositeMaterialInputLooseVariableType_t>(_VariableTypeOffset!.Value);
        }
    }
    private static nint? _ValueBooleanOffset;

    public ref bool ValueBoolean
    {
        get
        {
            _ValueBooleanOffset = _ValueBooleanOffset ?? Schema.GetOffset(0xAB8A0BE84DE46152);
            return ref _Handle.AsRef<bool>(_ValueBooleanOffset!.Value);
        }
    }
    private static nint? _ValueIntXOffset;

    public ref int ValueIntX
    {
        get
        {
            _ValueIntXOffset = _ValueIntXOffset ?? Schema.GetOffset(0xAB8A0BE8DCCAE4B5);
            return ref _Handle.AsRef<int>(_ValueIntXOffset!.Value);
        }
    }
    private static nint? _ValueIntYOffset;

    public ref int ValueIntY
    {
        get
        {
            _ValueIntYOffset = _ValueIntYOffset ?? Schema.GetOffset(0xAB8A0BE8DBCAE322);
            return ref _Handle.AsRef<int>(_ValueIntYOffset!.Value);
        }
    }
    private static nint? _ValueIntZOffset;

    public ref int ValueIntZ
    {
        get
        {
            _ValueIntZOffset = _ValueIntZOffset ?? Schema.GetOffset(0xAB8A0BE8DACAE18F);
            return ref _Handle.AsRef<int>(_ValueIntZOffset!.Value);
        }
    }
    private static nint? _ValueIntWOffset;

    public ref int ValueIntW
    {
        get
        {
            _ValueIntWOffset = _ValueIntWOffset ?? Schema.GetOffset(0xAB8A0BE8DDCAE648);
            return ref _Handle.AsRef<int>(_ValueIntWOffset!.Value);
        }
    }
    private static nint? _HasFloatBoundsOffset;

    public ref bool HasFloatBounds
    {
        get
        {
            _HasFloatBoundsOffset = _HasFloatBoundsOffset ?? Schema.GetOffset(0xAB8A0BE8A94BE1E2);
            return ref _Handle.AsRef<bool>(_HasFloatBoundsOffset!.Value);
        }
    }
    private static nint? _ValueFloatXOffset;

    public ref float ValueFloatX
    {
        get
        {
            _ValueFloatXOffset = _ValueFloatXOffset ?? Schema.GetOffset(0xAB8A0BE8BE0B10AA);
            return ref _Handle.AsRef<float>(_ValueFloatXOffset!.Value);
        }
    }
    private static nint? _ValueFloatX_MinOffset;

    public ref float ValueFloatX_Min
    {
        get
        {
            _ValueFloatX_MinOffset = _ValueFloatX_MinOffset ?? Schema.GetOffset(0xAB8A0BE885C07CE9);
            return ref _Handle.AsRef<float>(_ValueFloatX_MinOffset!.Value);
        }
    }
    private static nint? _ValueFloatX_MaxOffset;

    public ref float ValueFloatX_Max
    {
        get
        {
            _ValueFloatX_MaxOffset = _ValueFloatX_MaxOffset ?? Schema.GetOffset(0xAB8A0BE877ACDF27);
            return ref _Handle.AsRef<float>(_ValueFloatX_MaxOffset!.Value);
        }
    }
    private static nint? _ValueFloatYOffset;

    public ref float ValueFloatY
    {
        get
        {
            _ValueFloatYOffset = _ValueFloatYOffset ?? Schema.GetOffset(0xAB8A0BE8BF0B123D);
            return ref _Handle.AsRef<float>(_ValueFloatYOffset!.Value);
        }
    }
    private static nint? _ValueFloatY_MinOffset;

    public ref float ValueFloatY_Min
    {
        get
        {
            _ValueFloatY_MinOffset = _ValueFloatY_MinOffset ?? Schema.GetOffset(0xAB8A0BE81AB13F32);
            return ref _Handle.AsRef<float>(_ValueFloatY_MinOffset!.Value);
        }
    }
    private static nint? _ValueFloatY_MaxOffset;

    public ref float ValueFloatY_Max
    {
        get
        {
            _ValueFloatY_MaxOffset = _ValueFloatY_MaxOffset ?? Schema.GetOffset(0xAB8A0BE8249DC738);
            return ref _Handle.AsRef<float>(_ValueFloatY_MaxOffset!.Value);
        }
    }
    private static nint? _ValueFloatZOffset;

    public ref float ValueFloatZ
    {
        get
        {
            _ValueFloatZOffset = _ValueFloatZOffset ?? Schema.GetOffset(0xAB8A0BE8BC0B0D84);
            return ref _Handle.AsRef<float>(_ValueFloatZOffset!.Value);
        }
    }
    private static nint? _ValueFloatZ_MinOffset;

    public ref float ValueFloatZ_Min
    {
        get
        {
            _ValueFloatZ_MinOffset = _ValueFloatZ_MinOffset ?? Schema.GetOffset(0xAB8A0BE8B82D845B);
            return ref _Handle.AsRef<float>(_ValueFloatZ_MinOffset!.Value);
        }
    }
    private static nint? _ValueFloatZ_MaxOffset;

    public ref float ValueFloatZ_Max
    {
        get
        {
            _ValueFloatZ_MaxOffset = _ValueFloatZ_MaxOffset ?? Schema.GetOffset(0xAB8A0BE8AE19ECE5);
            return ref _Handle.AsRef<float>(_ValueFloatZ_MaxOffset!.Value);
        }
    }
    private static nint? _ValueFloatWOffset;

    public ref float ValueFloatW
    {
        get
        {
            _ValueFloatWOffset = _ValueFloatWOffset ?? Schema.GetOffset(0xAB8A0BE8B10AFC33);
            return ref _Handle.AsRef<float>(_ValueFloatWOffset!.Value);
        }
    }
    private static nint? _ValueFloatW_MinOffset;

    public ref float ValueFloatW_Min
    {
        get
        {
            _ValueFloatW_MinOffset = _ValueFloatW_MinOffset ?? Schema.GetOffset(0xAB8A0BE81793AAD8);
            return ref _Handle.AsRef<float>(_ValueFloatW_MinOffset!.Value);
        }
    }
    private static nint? _ValueFloatW_MaxOffset;

    public ref float ValueFloatW_Max
    {
        get
        {
            _ValueFloatW_MaxOffset = _ValueFloatW_MaxOffset ?? Schema.GetOffset(0xAB8A0BE82DA75532);
            return ref _Handle.AsRef<float>(_ValueFloatW_MaxOffset!.Value);
        }
    }
    private static nint? _CValueColor4Offset;

    public ref Color CValueColor4
    {
        get
        {
            _CValueColor4Offset = _CValueColor4Offset ?? Schema.GetOffset(0xAB8A0BE801701ACA);
            return ref _Handle.AsRef<Color>(_CValueColor4Offset!.Value);
        }
    }
    private static nint? _ValueSystemVarOffset;

    public ref CompositeMaterialVarSystemVar_t ValueSystemVar
    {
        get
        {
            _ValueSystemVarOffset = _ValueSystemVarOffset ?? Schema.GetOffset(0xAB8A0BE834FC3B84);
            return ref _Handle.AsRef<CompositeMaterialVarSystemVar_t>(_ValueSystemVarOffset!.Value);
        }
    }
    private static nint? _StrResourceMaterialOffset;
    private SchemaUntypedField? _StrResourceMaterialInstance;

    public SchemaUntypedField StrResourceMaterial
    {
        get
        {
            _StrResourceMaterialOffset = _StrResourceMaterialOffset ?? Schema.GetOffset(0xAB8A0BE898D8918D);
            var instance = _StrResourceMaterialInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _StrResourceMaterialOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrTextureContentAssetPathOffset;

    public string StrTextureContentAssetPath
    {
        get
        {
            _StrTextureContentAssetPathOffset = _StrTextureContentAssetPathOffset ?? Schema.GetOffset(0xAB8A0BE8683601D3);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrTextureContentAssetPathOffset!.Value));
        }
        set
        {
            _StrTextureContentAssetPathOffset = _StrTextureContentAssetPathOffset ?? Schema.GetOffset(0xAB8A0BE8683601D3);
            Schema.SetCUtlString(_Handle, _StrTextureContentAssetPathOffset!.Value, value);
        }
    }
    private static nint? _StrTextureRuntimeResourcePathOffset;
    private SchemaUntypedField? _StrTextureRuntimeResourcePathInstance;

    public SchemaUntypedField StrTextureRuntimeResourcePath
    {
        get
        {
            _StrTextureRuntimeResourcePathOffset = _StrTextureRuntimeResourcePathOffset ?? Schema.GetOffset(0xAB8A0BE8FAF89B8E);
            var instance = _StrTextureRuntimeResourcePathInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _StrTextureRuntimeResourcePathOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrTextureCompilationVtexTemplateOffset;

    public string StrTextureCompilationVtexTemplate
    {
        get
        {
            _StrTextureCompilationVtexTemplateOffset = _StrTextureCompilationVtexTemplateOffset ?? Schema.GetOffset(0xAB8A0BE83103EA5F);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrTextureCompilationVtexTemplateOffset!.Value));
        }
        set
        {
            _StrTextureCompilationVtexTemplateOffset = _StrTextureCompilationVtexTemplateOffset ?? Schema.GetOffset(0xAB8A0BE83103EA5F);
            Schema.SetCUtlString(_Handle, _StrTextureCompilationVtexTemplateOffset!.Value, value);
        }
    }
    private static nint? _TextureTypeOffset;

    public ref CompositeMaterialInputTextureType_t TextureType
    {
        get
        {
            _TextureTypeOffset = _TextureTypeOffset ?? Schema.GetOffset(0xAB8A0BE8499BE6C8);
            return ref _Handle.AsRef<CompositeMaterialInputTextureType_t>(_TextureTypeOffset!.Value);
        }
    }
    private static nint? _StrStringOffset;

    public string StrString
    {
        get
        {
            _StrStringOffset = _StrStringOffset ?? Schema.GetOffset(0xAB8A0BE866B150B9);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrStringOffset!.Value));
        }
        set
        {
            _StrStringOffset = _StrStringOffset ?? Schema.GetOffset(0xAB8A0BE866B150B9);
            Schema.SetCUtlString(_Handle, _StrStringOffset!.Value, value);
        }
    }
    private static nint? _StrPanoramaPanelPathOffset;

    public string StrPanoramaPanelPath
    {
        get
        {
            _StrPanoramaPanelPathOffset = _StrPanoramaPanelPathOffset ?? Schema.GetOffset(0xAB8A0BE8E142442C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrPanoramaPanelPathOffset!.Value));
        }
        set
        {
            _StrPanoramaPanelPathOffset = _StrPanoramaPanelPathOffset ?? Schema.GetOffset(0xAB8A0BE8E142442C);
            Schema.SetCUtlString(_Handle, _StrPanoramaPanelPathOffset!.Value, value);
        }
    }
    private static nint? _PanoramaRenderResOffset;

    public ref int PanoramaRenderRes
    {
        get
        {
            _PanoramaRenderResOffset = _PanoramaRenderResOffset ?? Schema.GetOffset(0xAB8A0BE8C6C9330C);
            return ref _Handle.AsRef<int>(_PanoramaRenderResOffset!.Value);
        }
    }

}