// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CompMatMutatorCondition_tImpl : SchemaClass, CompMatMutatorCondition_t
{
    public CompMatMutatorCondition_tImpl(nint handle) : base(handle) { }

    private static nint? _MutatorConditionOffset;

    public ref CompMatPropertyMutatorConditionType_t MutatorCondition
    {
        get
        {
            _MutatorConditionOffset = _MutatorConditionOffset ?? Schema.GetOffset(0xF34FC6BC15498DCE);
            return ref _Handle.AsRef<CompMatPropertyMutatorConditionType_t>(_MutatorConditionOffset!.Value);
        }
    }
    private static nint? _StrMutatorConditionContainerNameOffset;

    public string StrMutatorConditionContainerName
    {
        get
        {
            _StrMutatorConditionContainerNameOffset = _StrMutatorConditionContainerNameOffset ?? Schema.GetOffset(0xF34FC6BC0DEE1B79);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrMutatorConditionContainerNameOffset!.Value));
        }
        set
        {
            _StrMutatorConditionContainerNameOffset = _StrMutatorConditionContainerNameOffset ?? Schema.GetOffset(0xF34FC6BC0DEE1B79);
            Schema.SetCUtlString(_Handle, _StrMutatorConditionContainerNameOffset!.Value, value);
        }
    }
    private static nint? _StrMutatorConditionContainerVarNameOffset;

    public string StrMutatorConditionContainerVarName
    {
        get
        {
            _StrMutatorConditionContainerVarNameOffset = _StrMutatorConditionContainerVarNameOffset ?? Schema.GetOffset(0xF34FC6BCE96A00DC);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrMutatorConditionContainerVarNameOffset!.Value));
        }
        set
        {
            _StrMutatorConditionContainerVarNameOffset = _StrMutatorConditionContainerVarNameOffset ?? Schema.GetOffset(0xF34FC6BCE96A00DC);
            Schema.SetCUtlString(_Handle, _StrMutatorConditionContainerVarNameOffset!.Value, value);
        }
    }
    private static nint? _StrMutatorConditionContainerVarValueOffset;

    public string StrMutatorConditionContainerVarValue
    {
        get
        {
            _StrMutatorConditionContainerVarValueOffset = _StrMutatorConditionContainerVarValueOffset ?? Schema.GetOffset(0xF34FC6BC8F774E14);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrMutatorConditionContainerVarValueOffset!.Value));
        }
        set
        {
            _StrMutatorConditionContainerVarValueOffset = _StrMutatorConditionContainerVarValueOffset ?? Schema.GetOffset(0xF34FC6BC8F774E14);
            Schema.SetCUtlString(_Handle, _StrMutatorConditionContainerVarValueOffset!.Value, value);
        }
    }
    private static nint? _PassWhenTrueOffset;

    public ref bool PassWhenTrue
    {
        get
        {
            _PassWhenTrueOffset = _PassWhenTrueOffset ?? Schema.GetOffset(0xF34FC6BC5B723AC8);
            return ref _Handle.AsRef<bool>(_PassWhenTrueOffset!.Value);
        }
    }

}