// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CompMatPropertyMutator_tImpl : SchemaClass, CompMatPropertyMutator_t
{
    public CompMatPropertyMutator_tImpl(nint handle) : base(handle) { }

    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0xEB12CF7E6154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _MutatorCommandTypeOffset;

    public ref CompMatPropertyMutatorType_t MutatorCommandType
    {
        get
        {
            _MutatorCommandTypeOffset = _MutatorCommandTypeOffset ?? Schema.GetOffset(0xEB12CF7E628BEC12);
            return ref _Handle.AsRef<CompMatPropertyMutatorType_t>(_MutatorCommandTypeOffset!.Value);
        }
    }
    private static nint? _StrInitWith_ContainerOffset;

    public string StrInitWith_Container
    {
        get
        {
            _StrInitWith_ContainerOffset = _StrInitWith_ContainerOffset ?? Schema.GetOffset(0xEB12CF7EE0E4DD7E);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrInitWith_ContainerOffset!.Value));
        }
        set
        {
            _StrInitWith_ContainerOffset = _StrInitWith_ContainerOffset ?? Schema.GetOffset(0xEB12CF7EE0E4DD7E);
            Schema.SetCUtlString(_Handle, _StrInitWith_ContainerOffset!.Value, value);
        }
    }
    private static nint? _StrCopyProperty_InputContainerSrcOffset;

    public string StrCopyProperty_InputContainerSrc
    {
        get
        {
            _StrCopyProperty_InputContainerSrcOffset = _StrCopyProperty_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E97FFC2E4);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyProperty_InputContainerSrcOffset!.Value));
        }
        set
        {
            _StrCopyProperty_InputContainerSrcOffset = _StrCopyProperty_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E97FFC2E4);
            Schema.SetCUtlString(_Handle, _StrCopyProperty_InputContainerSrcOffset!.Value, value);
        }
    }
    private static nint? _StrCopyProperty_InputContainerPropertyOffset;

    public string StrCopyProperty_InputContainerProperty
    {
        get
        {
            _StrCopyProperty_InputContainerPropertyOffset = _StrCopyProperty_InputContainerPropertyOffset ?? Schema.GetOffset(0xEB12CF7EAF6A02BB);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyProperty_InputContainerPropertyOffset!.Value));
        }
        set
        {
            _StrCopyProperty_InputContainerPropertyOffset = _StrCopyProperty_InputContainerPropertyOffset ?? Schema.GetOffset(0xEB12CF7EAF6A02BB);
            Schema.SetCUtlString(_Handle, _StrCopyProperty_InputContainerPropertyOffset!.Value, value);
        }
    }
    private static nint? _StrCopyProperty_TargetPropertyOffset;

    public string StrCopyProperty_TargetProperty
    {
        get
        {
            _StrCopyProperty_TargetPropertyOffset = _StrCopyProperty_TargetPropertyOffset ?? Schema.GetOffset(0xEB12CF7E50528D89);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyProperty_TargetPropertyOffset!.Value));
        }
        set
        {
            _StrCopyProperty_TargetPropertyOffset = _StrCopyProperty_TargetPropertyOffset ?? Schema.GetOffset(0xEB12CF7E50528D89);
            Schema.SetCUtlString(_Handle, _StrCopyProperty_TargetPropertyOffset!.Value, value);
        }
    }
    private static nint? _StrRandomRollInputVars_SeedInputVarOffset;

    public string StrRandomRollInputVars_SeedInputVar
    {
        get
        {
            _StrRandomRollInputVars_SeedInputVarOffset = _StrRandomRollInputVars_SeedInputVarOffset ?? Schema.GetOffset(0xEB12CF7E24701F53);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrRandomRollInputVars_SeedInputVarOffset!.Value));
        }
        set
        {
            _StrRandomRollInputVars_SeedInputVarOffset = _StrRandomRollInputVars_SeedInputVarOffset ?? Schema.GetOffset(0xEB12CF7E24701F53);
            Schema.SetCUtlString(_Handle, _StrRandomRollInputVars_SeedInputVarOffset!.Value, value);
        }
    }
    private static nint? _RandomRollInputVars_InputVarsToRollOffset;

    public ref CUtlVector<CUtlString> RandomRollInputVars_InputVarsToRoll
    {
        get
        {
            _RandomRollInputVars_InputVarsToRollOffset = _RandomRollInputVars_InputVarsToRollOffset ?? Schema.GetOffset(0xEB12CF7E8F96A462);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_RandomRollInputVars_InputVarsToRollOffset!.Value);
        }
    }
    private static nint? _StrCopyMatchingKeys_InputContainerSrcOffset;

    public string StrCopyMatchingKeys_InputContainerSrc
    {
        get
        {
            _StrCopyMatchingKeys_InputContainerSrcOffset = _StrCopyMatchingKeys_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E758E1692);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyMatchingKeys_InputContainerSrcOffset!.Value));
        }
        set
        {
            _StrCopyMatchingKeys_InputContainerSrcOffset = _StrCopyMatchingKeys_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E758E1692);
            Schema.SetCUtlString(_Handle, _StrCopyMatchingKeys_InputContainerSrcOffset!.Value, value);
        }
    }
    private static nint? _StrCopyKeysWithSuffix_InputContainerSrcOffset;

    public string StrCopyKeysWithSuffix_InputContainerSrc
    {
        get
        {
            _StrCopyKeysWithSuffix_InputContainerSrcOffset = _StrCopyKeysWithSuffix_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7ED1F25E0C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyKeysWithSuffix_InputContainerSrcOffset!.Value));
        }
        set
        {
            _StrCopyKeysWithSuffix_InputContainerSrcOffset = _StrCopyKeysWithSuffix_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7ED1F25E0C);
            Schema.SetCUtlString(_Handle, _StrCopyKeysWithSuffix_InputContainerSrcOffset!.Value, value);
        }
    }
    private static nint? _StrCopyKeysWithSuffix_FindSuffixOffset;

    public string StrCopyKeysWithSuffix_FindSuffix
    {
        get
        {
            _StrCopyKeysWithSuffix_FindSuffixOffset = _StrCopyKeysWithSuffix_FindSuffixOffset ?? Schema.GetOffset(0xEB12CF7E5C3A67DF);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyKeysWithSuffix_FindSuffixOffset!.Value));
        }
        set
        {
            _StrCopyKeysWithSuffix_FindSuffixOffset = _StrCopyKeysWithSuffix_FindSuffixOffset ?? Schema.GetOffset(0xEB12CF7E5C3A67DF);
            Schema.SetCUtlString(_Handle, _StrCopyKeysWithSuffix_FindSuffixOffset!.Value, value);
        }
    }
    private static nint? _StrCopyKeysWithSuffix_ReplaceSuffixOffset;

    public string StrCopyKeysWithSuffix_ReplaceSuffix
    {
        get
        {
            _StrCopyKeysWithSuffix_ReplaceSuffixOffset = _StrCopyKeysWithSuffix_ReplaceSuffixOffset ?? Schema.GetOffset(0xEB12CF7EE5133506);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCopyKeysWithSuffix_ReplaceSuffixOffset!.Value));
        }
        set
        {
            _StrCopyKeysWithSuffix_ReplaceSuffixOffset = _StrCopyKeysWithSuffix_ReplaceSuffixOffset ?? Schema.GetOffset(0xEB12CF7EE5133506);
            Schema.SetCUtlString(_Handle, _StrCopyKeysWithSuffix_ReplaceSuffixOffset!.Value, value);
        }
    }
    private static nint? _SetValue_ValueOffset;
    private CompositeMaterialInputLooseVariable_tImpl? _SetValue_ValueInstance;

    public CompositeMaterialInputLooseVariable_t SetValue_Value
    {
        get
        {
            _SetValue_ValueOffset = _SetValue_ValueOffset ?? Schema.GetOffset(0xEB12CF7E28DF3C36);
            var instance = _SetValue_ValueInstance ??= new CompositeMaterialInputLooseVariable_tImpl(0);
            instance.DangerousSetHandle(_Handle + _SetValue_ValueOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrGenerateTexture_TargetParamOffset;

    public string StrGenerateTexture_TargetParam
    {
        get
        {
            _StrGenerateTexture_TargetParamOffset = _StrGenerateTexture_TargetParamOffset ?? Schema.GetOffset(0xEB12CF7E13621927);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrGenerateTexture_TargetParamOffset!.Value));
        }
        set
        {
            _StrGenerateTexture_TargetParamOffset = _StrGenerateTexture_TargetParamOffset ?? Schema.GetOffset(0xEB12CF7E13621927);
            Schema.SetCUtlString(_Handle, _StrGenerateTexture_TargetParamOffset!.Value, value);
        }
    }
    private static nint? _StrGenerateTexture_InitialContainerOffset;

    public string StrGenerateTexture_InitialContainer
    {
        get
        {
            _StrGenerateTexture_InitialContainerOffset = _StrGenerateTexture_InitialContainerOffset ?? Schema.GetOffset(0xEB12CF7EDF864C94);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrGenerateTexture_InitialContainerOffset!.Value));
        }
        set
        {
            _StrGenerateTexture_InitialContainerOffset = _StrGenerateTexture_InitialContainerOffset ?? Schema.GetOffset(0xEB12CF7EDF864C94);
            Schema.SetCUtlString(_Handle, _StrGenerateTexture_InitialContainerOffset!.Value, value);
        }
    }
    private static nint? _ResolutionOffset;

    public ref int Resolution
    {
        get
        {
            _ResolutionOffset = _ResolutionOffset ?? Schema.GetOffset(0xEB12CF7EC1FCE953);
            return ref _Handle.AsRef<int>(_ResolutionOffset!.Value);
        }
    }
    private static nint? _IsScratchTargetOffset;

    public ref bool IsScratchTarget
    {
        get
        {
            _IsScratchTargetOffset = _IsScratchTargetOffset ?? Schema.GetOffset(0xEB12CF7EE1E462C8);
            return ref _Handle.AsRef<bool>(_IsScratchTargetOffset!.Value);
        }
    }
    private static nint? _StrCompressionFormatOffset;

    public string StrCompressionFormat
    {
        get
        {
            _StrCompressionFormatOffset = _StrCompressionFormatOffset ?? Schema.GetOffset(0xEB12CF7E548D5E59);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrCompressionFormatOffset!.Value));
        }
        set
        {
            _StrCompressionFormatOffset = _StrCompressionFormatOffset ?? Schema.GetOffset(0xEB12CF7E548D5E59);
            Schema.SetCUtlString(_Handle, _StrCompressionFormatOffset!.Value, value);
        }
    }
    private static nint? _SplatDebugInfoOffset;

    public ref bool SplatDebugInfo
    {
        get
        {
            _SplatDebugInfoOffset = _SplatDebugInfoOffset ?? Schema.GetOffset(0xEB12CF7E722647BA);
            return ref _Handle.AsRef<bool>(_SplatDebugInfoOffset!.Value);
        }
    }
    private static nint? _CaptureInRenderDocOffset;

    public ref bool CaptureInRenderDoc
    {
        get
        {
            _CaptureInRenderDocOffset = _CaptureInRenderDocOffset ?? Schema.GetOffset(0xEB12CF7E230CDE58);
            return ref _Handle.AsRef<bool>(_CaptureInRenderDocOffset!.Value);
        }
    }
    private static nint? _TexGenInstructionsOffset;

    public ref CUtlVector<CompMatPropertyMutator_t> TexGenInstructions
    {
        get
        {
            _TexGenInstructionsOffset = _TexGenInstructionsOffset ?? Schema.GetOffset(0xEB12CF7E72FC83A5);
            return ref _Handle.AsRef<CUtlVector<CompMatPropertyMutator_t>>(_TexGenInstructionsOffset!.Value);
        }
    }
    private static nint? _ConditionalMutatorsOffset;

    public ref CUtlVector<CompMatPropertyMutator_t> ConditionalMutators
    {
        get
        {
            _ConditionalMutatorsOffset = _ConditionalMutatorsOffset ?? Schema.GetOffset(0xEB12CF7E924F46D0);
            return ref _Handle.AsRef<CUtlVector<CompMatPropertyMutator_t>>(_ConditionalMutatorsOffset!.Value);
        }
    }
    private static nint? _StrPopInputQueue_ContainerOffset;

    public string StrPopInputQueue_Container
    {
        get
        {
            _StrPopInputQueue_ContainerOffset = _StrPopInputQueue_ContainerOffset ?? Schema.GetOffset(0xEB12CF7E185AB388);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrPopInputQueue_ContainerOffset!.Value));
        }
        set
        {
            _StrPopInputQueue_ContainerOffset = _StrPopInputQueue_ContainerOffset ?? Schema.GetOffset(0xEB12CF7E185AB388);
            Schema.SetCUtlString(_Handle, _StrPopInputQueue_ContainerOffset!.Value, value);
        }
    }
    private static nint? _StrDrawText_InputContainerSrcOffset;

    public string StrDrawText_InputContainerSrc
    {
        get
        {
            _StrDrawText_InputContainerSrcOffset = _StrDrawText_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E6BDEAC79);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrDrawText_InputContainerSrcOffset!.Value));
        }
        set
        {
            _StrDrawText_InputContainerSrcOffset = _StrDrawText_InputContainerSrcOffset ?? Schema.GetOffset(0xEB12CF7E6BDEAC79);
            Schema.SetCUtlString(_Handle, _StrDrawText_InputContainerSrcOffset!.Value, value);
        }
    }
    private static nint? _StrDrawText_InputContainerPropertyOffset;

    public string StrDrawText_InputContainerProperty
    {
        get
        {
            _StrDrawText_InputContainerPropertyOffset = _StrDrawText_InputContainerPropertyOffset ?? Schema.GetOffset(0xEB12CF7E409D0898);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrDrawText_InputContainerPropertyOffset!.Value));
        }
        set
        {
            _StrDrawText_InputContainerPropertyOffset = _StrDrawText_InputContainerPropertyOffset ?? Schema.GetOffset(0xEB12CF7E409D0898);
            Schema.SetCUtlString(_Handle, _StrDrawText_InputContainerPropertyOffset!.Value, value);
        }
    }
    private static nint? _DrawText_PositionOffset;

    public ref Vector2D DrawText_Position
    {
        get
        {
            _DrawText_PositionOffset = _DrawText_PositionOffset ?? Schema.GetOffset(0xEB12CF7E81ED9616);
            return ref _Handle.AsRef<Vector2D>(_DrawText_PositionOffset!.Value);
        }
    }
    private static nint? _ColDrawText_ColorOffset;

    public ref Color ColDrawText_Color
    {
        get
        {
            _ColDrawText_ColorOffset = _ColDrawText_ColorOffset ?? Schema.GetOffset(0xEB12CF7E685D5088);
            return ref _Handle.AsRef<Color>(_ColDrawText_ColorOffset!.Value);
        }
    }
    private static nint? _StrDrawText_FontOffset;

    public string StrDrawText_Font
    {
        get
        {
            _StrDrawText_FontOffset = _StrDrawText_FontOffset ?? Schema.GetOffset(0xEB12CF7E2467A823);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrDrawText_FontOffset!.Value));
        }
        set
        {
            _StrDrawText_FontOffset = _StrDrawText_FontOffset ?? Schema.GetOffset(0xEB12CF7E2467A823);
            Schema.SetCUtlString(_Handle, _StrDrawText_FontOffset!.Value, value);
        }
    }
    private static nint? _ConditionsOffset;

    public ref CUtlVector<CompMatMutatorCondition_t> Conditions
    {
        get
        {
            _ConditionsOffset = _ConditionsOffset ?? Schema.GetOffset(0xEB12CF7ED6884117);
            return ref _Handle.AsRef<CUtlVector<CompMatMutatorCondition_t>>(_ConditionsOffset!.Value);
        }
    }

}