// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CompositeMaterialInputContainer_tImpl : SchemaClass, CompositeMaterialInputContainer_t
{
    public CompositeMaterialInputContainer_tImpl(nint handle) : base(handle) { }

    private static nint? _EnabledOffset;

    public ref bool Enabled
    {
        get
        {
            _EnabledOffset = _EnabledOffset ?? Schema.GetOffset(0x6B247F56154EB7E);
            return ref _Handle.AsRef<bool>(_EnabledOffset!.Value);
        }
    }
    private static nint? _CompositeMaterialInputContainerSourceTypeOffset;

    public ref CompositeMaterialInputContainerSourceType_t CompositeMaterialInputContainerSourceType
    {
        get
        {
            _CompositeMaterialInputContainerSourceTypeOffset = _CompositeMaterialInputContainerSourceTypeOffset ?? Schema.GetOffset(0x6B247F5999ADAAF);
            return ref _Handle.AsRef<CompositeMaterialInputContainerSourceType_t>(_CompositeMaterialInputContainerSourceTypeOffset!.Value);
        }
    }
    private static nint? _StrSpecificContainerMaterialOffset;
    private SchemaUntypedField? _StrSpecificContainerMaterialInstance;

    public SchemaUntypedField StrSpecificContainerMaterial
    {
        get
        {
            _StrSpecificContainerMaterialOffset = _StrSpecificContainerMaterialOffset ?? Schema.GetOffset(0x6B247F5EA588AF6);
            var instance = _StrSpecificContainerMaterialInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _StrSpecificContainerMaterialOffset!.Value);
            return instance;
        }
    }
    private static nint? _StrAttrNameOffset;

    public string StrAttrName
    {
        get
        {
            _StrAttrNameOffset = _StrAttrNameOffset ?? Schema.GetOffset(0x6B247F53B064C18);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrAttrNameOffset!.Value));
        }
        set
        {
            _StrAttrNameOffset = _StrAttrNameOffset ?? Schema.GetOffset(0x6B247F53B064C18);
            Schema.SetCUtlString(_Handle, _StrAttrNameOffset!.Value, value);
        }
    }
    private static nint? _StrAliasOffset;

    public string StrAlias
    {
        get
        {
            _StrAliasOffset = _StrAliasOffset ?? Schema.GetOffset(0x6B247F503F2D55C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrAliasOffset!.Value));
        }
        set
        {
            _StrAliasOffset = _StrAliasOffset ?? Schema.GetOffset(0x6B247F503F2D55C);
            Schema.SetCUtlString(_Handle, _StrAliasOffset!.Value, value);
        }
    }
    private static nint? _LooseVariablesOffset;

    public ref CUtlVector<CompositeMaterialInputLooseVariable_t> LooseVariables
    {
        get
        {
            _LooseVariablesOffset = _LooseVariablesOffset ?? Schema.GetOffset(0x6B247F59ED0926E);
            return ref _Handle.AsRef<CUtlVector<CompositeMaterialInputLooseVariable_t>>(_LooseVariablesOffset!.Value);
        }
    }
    private static nint? _StrAttrNameForVarOffset;

    public string StrAttrNameForVar
    {
        get
        {
            _StrAttrNameForVarOffset = _StrAttrNameForVarOffset ?? Schema.GetOffset(0x6B247F5360DD69C);
            return Schema.GetCUtlString(_Handle.Read<nint>(_StrAttrNameForVarOffset!.Value));
        }
        set
        {
            _StrAttrNameForVarOffset = _StrAttrNameForVarOffset ?? Schema.GetOffset(0x6B247F5360DD69C);
            Schema.SetCUtlString(_Handle, _StrAttrNameForVarOffset!.Value, value);
        }
    }
    private static nint? _ExposeExternallyOffset;

    public ref bool ExposeExternally
    {
        get
        {
            _ExposeExternallyOffset = _ExposeExternallyOffset ?? Schema.GetOffset(0x6B247F552CA5AD1);
            return ref _Handle.AsRef<bool>(_ExposeExternallyOffset!.Value);
        }
    }

}