// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPointOffScreenIndicatorUiImpl : C_PointClientUIWorldPanelImpl, CPointOffScreenIndicatorUi
{
    public CPointOffScreenIndicatorUiImpl(nint handle) : base(handle) { }

    private static nint? _BeenEnabledOffset;

    public ref bool BeenEnabled
    {
        get
        {
            _BeenEnabledOffset = _BeenEnabledOffset ?? Schema.GetOffset(0x25A993307631D6F8);
            return ref _Handle.AsRef<bool>(_BeenEnabledOffset!.Value);
        }
    }
    private static nint? _HideOffset;

    public ref bool Hide
    {
        get
        {
            _HideOffset = _HideOffset ?? Schema.GetOffset(0x25A993302D926E0D);
            return ref _Handle.AsRef<bool>(_HideOffset!.Value);
        }
    }
    private static nint? _SeenTargetTimeOffset;

    public ref float SeenTargetTime
    {
        get
        {
            _SeenTargetTimeOffset = _SeenTargetTimeOffset ?? Schema.GetOffset(0x25A99330DCFFF61C);
            return ref _Handle.AsRef<float>(_SeenTargetTimeOffset!.Value);
        }
    }
    private static nint? _TargetPanelOffset;
    private C_PointClientUIWorldPanelImpl? _TargetPanelInstance;

    public C_PointClientUIWorldPanel? TargetPanel
    {
        get
        {
            _TargetPanelOffset = _TargetPanelOffset ?? Schema.GetOffset(0x25A99330678AAF10);
            var ptr = _Handle.Read<nint>(_TargetPanelOffset!.Value);
            if (!ptr.IsValidPtr()) return null;
            var instance = _TargetPanelInstance ??= new C_PointClientUIWorldPanelImpl(0);
            instance.DangerousSetHandle(ptr);
            return instance;
        }
    }

}