// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CPreviewEntryImpl : SchemaClass, CPreviewEntry
{
    public CPreviewEntryImpl(nint handle) : base(handle) { }

    private static nint? _SoundNameOffset;

    public string SoundName
    {
        get
        {
            _SoundNameOffset = _SoundNameOffset ?? Schema.GetOffset(0x55F6D97653204B8F);
            return Schema.GetCUtlString(_Handle.Read<nint>(_SoundNameOffset!.Value));
        }
        set
        {
            _SoundNameOffset = _SoundNameOffset ?? Schema.GetOffset(0x55F6D97653204B8F);
            Schema.SetCUtlString(_Handle, _SoundNameOffset!.Value, value);
        }
    }
    private static nint? _TrackNameOffset;

    public string TrackName
    {
        get
        {
            _TrackNameOffset = _TrackNameOffset ?? Schema.GetOffset(0x55F6D9766B424377);
            return Schema.GetCUtlString(_Handle.Read<nint>(_TrackNameOffset!.Value));
        }
        set
        {
            _TrackNameOffset = _TrackNameOffset ?? Schema.GetOffset(0x55F6D9766B424377);
            Schema.SetCUtlString(_Handle, _TrackNameOffset!.Value, value);
        }
    }
    private static nint? _IsSoundEventOffset;

    public ref bool IsSoundEvent
    {
        get
        {
            _IsSoundEventOffset = _IsSoundEventOffset ?? Schema.GetOffset(0x55F6D976490F281C);
            return ref _Handle.AsRef<bool>(_IsSoundEventOffset!.Value);
        }
    }

}