// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CResourceAssetTypeInfoImpl : CSimpleAssetTypeInfoImpl, CResourceAssetTypeInfo
{
    public CResourceAssetTypeInfoImpl(nint handle) : base(handle) { }

    private static nint? _CompilerIdentifierOffset;

    public string CompilerIdentifier
    {
        get
        {
            _CompilerIdentifierOffset = _CompilerIdentifierOffset ?? Schema.GetOffset(0x52E684CE62A92E77);
            return Schema.GetCUtlString(_Handle.Read<nint>(_CompilerIdentifierOffset!.Value));
        }
        set
        {
            _CompilerIdentifierOffset = _CompilerIdentifierOffset ?? Schema.GetOffset(0x52E684CE62A92E77);
            Schema.SetCUtlString(_Handle, _CompilerIdentifierOffset!.Value, value);
        }
    }
    private static nint? _CompileDependsOnResourceTypesOffset;

    public ref CUtlVector<CUtlString> CompileDependsOnResourceTypes
    {
        get
        {
            _CompileDependsOnResourceTypesOffset = _CompileDependsOnResourceTypesOffset ?? Schema.GetOffset(0x52E684CEE92763E9);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_CompileDependsOnResourceTypesOffset!.Value);
        }
    }
    private static nint? _BlocksOffset;

    public ref CUtlVector<ResourceBlockTypeInfo_t> Blocks
    {
        get
        {
            _BlocksOffset = _BlocksOffset ?? Schema.GetOffset(0x52E684CE84AE5A43);
            return ref _Handle.AsRef<CUtlVector<ResourceBlockTypeInfo_t>>(_BlocksOffset!.Value);
        }
    }
    private static nint? _RequiredSpecialDependencyOffset;

    public string RequiredSpecialDependency
    {
        get
        {
            _RequiredSpecialDependencyOffset = _RequiredSpecialDependencyOffset ?? Schema.GetOffset(0x52E684CE626234AE);
            return Schema.GetCUtlString(_Handle.Read<nint>(_RequiredSpecialDependencyOffset!.Value));
        }
        set
        {
            _RequiredSpecialDependencyOffset = _RequiredSpecialDependencyOffset ?? Schema.GetOffset(0x52E684CE626234AE);
            Schema.SetCUtlString(_Handle, _RequiredSpecialDependencyOffset!.Value, value);
        }
    }
    private static nint? _PreventDirectCompileOffset;

    public ref bool PreventDirectCompile
    {
        get
        {
            _PreventDirectCompileOffset = _PreventDirectCompileOffset ?? Schema.GetOffset(0x52E684CE546CB159);
            return ref _Handle.AsRef<bool>(_PreventDirectCompileOffset!.Value);
        }
    }
    private static nint? _CannotBeAMultiParentChildCompileOffset;

    public ref bool CannotBeAMultiParentChildCompile
    {
        get
        {
            _CannotBeAMultiParentChildCompileOffset = _CannotBeAMultiParentChildCompileOffset ?? Schema.GetOffset(0x52E684CE9FFE30B0);
            return ref _Handle.AsRef<bool>(_CannotBeAMultiParentChildCompileOffset!.Value);
        }
    }
    private static nint? _PrefersIconForThumbnailOffset;

    public ref bool PrefersIconForThumbnail
    {
        get
        {
            _PrefersIconForThumbnailOffset = _PrefersIconForThumbnailOffset ?? Schema.GetOffset(0x52E684CE36ACCD44);
            return ref _Handle.AsRef<bool>(_PrefersIconForThumbnailOffset!.Value);
        }
    }
    private static nint? _AllowedToCompileInTestModeOffset;

    public ref bool AllowedToCompileInTestMode
    {
        get
        {
            _AllowedToCompileInTestModeOffset = _AllowedToCompileInTestModeOffset ?? Schema.GetOffset(0x52E684CE8C4711C3);
            return ref _Handle.AsRef<bool>(_AllowedToCompileInTestModeOffset!.Value);
        }
    }

}