// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSolveIKChainAnimNodeChainDataImpl : SchemaClass, CSolveIKChainAnimNodeChainData
{
    public CSolveIKChainAnimNodeChainDataImpl(nint handle) : base(handle) { }

    private static nint? _IkChainOffset;

    public string IkChain
    {
        get
        {
            _IkChainOffset = _IkChainOffset ?? Schema.GetOffset(0x44F7608CA2987ACE);
            return Schema.GetCUtlString(_Handle.Read<nint>(_IkChainOffset!.Value));
        }
        set
        {
            _IkChainOffset = _IkChainOffset ?? Schema.GetOffset(0x44F7608CA2987ACE);
            Schema.SetCUtlString(_Handle, _IkChainOffset!.Value, value);
        }
    }
    private static nint? _SolverSettingSourceOffset;

    public ref SolveIKChainAnimNodeSettingSource SolverSettingSource
    {
        get
        {
            _SolverSettingSourceOffset = _SolverSettingSourceOffset ?? Schema.GetOffset(0x44F7608CA1467B0F);
            return ref _Handle.AsRef<SolveIKChainAnimNodeSettingSource>(_SolverSettingSourceOffset!.Value);
        }
    }
    private static nint? _OverrideSolverSettingsOffset;
    private IKSolverSettings_tImpl? _OverrideSolverSettingsInstance;

    public IKSolverSettings_t OverrideSolverSettings
    {
        get
        {
            _OverrideSolverSettingsOffset = _OverrideSolverSettingsOffset ?? Schema.GetOffset(0x44F7608CC8BAF10B);
            var instance = _OverrideSolverSettingsInstance ??= new IKSolverSettings_tImpl(0);
            instance.DangerousSetHandle(_Handle + _OverrideSolverSettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _TargetSettingSourceOffset;

    public ref SolveIKChainAnimNodeSettingSource TargetSettingSource
    {
        get
        {
            _TargetSettingSourceOffset = _TargetSettingSourceOffset ?? Schema.GetOffset(0x44F7608C376B5F01);
            return ref _Handle.AsRef<SolveIKChainAnimNodeSettingSource>(_TargetSettingSourceOffset!.Value);
        }
    }
    private static nint? _OverrideTargetSettingsOffset;
    private IKTargetSettings_tImpl? _OverrideTargetSettingsInstance;

    public IKTargetSettings_t OverrideTargetSettings
    {
        get
        {
            _OverrideTargetSettingsOffset = _OverrideTargetSettingsOffset ?? Schema.GetOffset(0x44F7608CD383D3CD);
            var instance = _OverrideTargetSettingsInstance ??= new IKTargetSettings_tImpl(0);
            instance.DangerousSetHandle(_Handle + _OverrideTargetSettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _DebugSettingOffset;

    public ref SolveIKChainAnimNodeDebugSetting DebugSetting
    {
        get
        {
            _DebugSettingOffset = _DebugSettingOffset ?? Schema.GetOffset(0x44F7608C624CC0B4);
            return ref _Handle.AsRef<SolveIKChainAnimNodeDebugSetting>(_DebugSettingOffset!.Value);
        }
    }
    private static nint? _DebugNormalizedLengthOffset;

    public ref float DebugNormalizedLength
    {
        get
        {
            _DebugNormalizedLengthOffset = _DebugNormalizedLengthOffset ?? Schema.GetOffset(0x44F7608C7FACD6EB);
            return ref _Handle.AsRef<float>(_DebugNormalizedLengthOffset!.Value);
        }
    }
    private static nint? _DebugOffsetOffset;

    public ref Vector DebugOffset
    {
        get
        {
            _DebugOffsetOffset = _DebugOffsetOffset ?? Schema.GetOffset(0x44F7608C2FF28BBF);
            return ref _Handle.AsRef<Vector>(_DebugOffsetOffset!.Value);
        }
    }

}