// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSprayedDataPresetImpl : SchemaClass, CSprayedDataPreset
{
    public CSprayedDataPresetImpl(nint handle) : base(handle) { }

    private static nint? _CounterMinOffset;

    public ref int CounterMin
    {
        get
        {
            _CounterMinOffset = _CounterMinOffset ?? Schema.GetOffset(0xDE33C3715B40FDD9);
            return ref _Handle.AsRef<int>(_CounterMinOffset!.Value);
        }
    }
    private static nint? _CounterMaxOffset;

    public ref int CounterMax
    {
        get
        {
            _CounterMaxOffset = _CounterMaxOffset ?? Schema.GetOffset(0xDE33C3716D2BFF77);
            return ref _Handle.AsRef<int>(_CounterMaxOffset!.Value);
        }
    }
    private static nint? _SpacingOffset;

    public ref float Spacing
    {
        get
        {
            _SpacingOffset = _SpacingOffset ?? Schema.GetOffset(0xDE33C3712B86F1BC);
            return ref _Handle.AsRef<float>(_SpacingOffset!.Value);
        }
    }
    private static nint? _RadiusOffset;

    public ref float Radius
    {
        get
        {
            _RadiusOffset = _RadiusOffset ?? Schema.GetOffset(0xDE33C3715ACFC08D);
            return ref _Handle.AsRef<float>(_RadiusOffset!.Value);
        }
    }
    private static nint? _EraseAmountOffset;

    public ref float EraseAmount
    {
        get
        {
            _EraseAmountOffset = _EraseAmountOffset ?? Schema.GetOffset(0xDE33C3711106ED57);
            return ref _Handle.AsRef<float>(_EraseAmountOffset!.Value);
        }
    }
    private static nint? _ConstantDensityOffset;

    public ref bool ConstantDensity
    {
        get
        {
            _ConstantDensityOffset = _ConstantDensityOffset ?? Schema.GetOffset(0xDE33C371F35E5CFB);
            return ref _Handle.AsRef<bool>(_ConstantDensityOffset!.Value);
        }
    }
    private static nint? _OnlyHitMeshesOffset;

    public ref bool OnlyHitMeshes
    {
        get
        {
            _OnlyHitMeshesOffset = _OnlyHitMeshesOffset ?? Schema.GetOffset(0xDE33C37106993061);
            return ref _Handle.AsRef<bool>(_OnlyHitMeshesOffset!.Value);
        }
    }
    private static nint? _RadialFalloffOffset;

    public ref bool RadialFalloff
    {
        get
        {
            _RadialFalloffOffset = _RadialFalloffOffset ?? Schema.GetOffset(0xDE33C3714F915238);
            return ref _Handle.AsRef<bool>(_RadialFalloffOffset!.Value);
        }
    }
    private static nint? _ElementsOffset;

    public ref CUtlVector<CSprayedDataPresetElement> Elements
    {
        get
        {
            _ElementsOffset = _ElementsOffset ?? Schema.GetOffset(0xDE33C3716B0FA56C);
            return ref _Handle.AsRef<CUtlVector<CSprayedDataPresetElement>>(_ElementsOffset!.Value);
        }
    }

}