// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSteamAudioBakedOcclusionDataImpl : SchemaClass, CSteamAudioBakedOcclusionData
{
    public CSteamAudioBakedOcclusionDataImpl(nint handle) : base(handle) { }

    private static nint? _SettingsOffset;
    private SteamAudioCustomDataOcclusionSettings_tImpl? _SettingsInstance;

    public SteamAudioCustomDataOcclusionSettings_t Settings
    {
        get
        {
            _SettingsOffset = _SettingsOffset ?? Schema.GetOffset(0x2D94E8C0B3DE33A8);
            var instance = _SettingsInstance ??= new SteamAudioCustomDataOcclusionSettings_tImpl(0);
            instance.DangerousSetHandle(_Handle + _SettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _ProbesOffset;
    private CSteamAudioProbeDataImpl? _ProbesInstance;

    public CSteamAudioProbeData Probes
    {
        get
        {
            _ProbesOffset = _ProbesOffset ?? Schema.GetOffset(0x2D94E8C049D37E06);
            var instance = _ProbesInstance ??= new CSteamAudioProbeDataImpl(0);
            instance.DangerousSetHandle(_Handle + _ProbesOffset!.Value);
            return instance;
        }
    }
    private static nint? _PathingRatioOffset;

    public ref CUtlVector<float> PathingRatio
    {
        get
        {
            _PathingRatioOffset = _PathingRatioOffset ?? Schema.GetOffset(0x2D94E8C0851D8DE9);
            return ref _Handle.AsRef<CUtlVector<float>>(_PathingRatioOffset!.Value);
        }
    }
    private static nint? _PathingDeviationOffset;

    public ref CUtlVector<float> PathingDeviation
    {
        get
        {
            _PathingDeviationOffset = _PathingDeviationOffset ?? Schema.GetOffset(0x2D94E8C0808E85C5);
            return ref _Handle.AsRef<CUtlVector<float>>(_PathingDeviationOffset!.Value);
        }
    }
    private static nint? _ReflectionEnergyOffset;

    public ref CUtlVector<float> ReflectionEnergy
    {
        get
        {
            _ReflectionEnergyOffset = _ReflectionEnergyOffset ?? Schema.GetOffset(0x2D94E8C0E22F61C8);
            return ref _Handle.AsRef<CUtlVector<float>>(_ReflectionEnergyOffset!.Value);
        }
    }

}