// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSteamAudioBakedDimensionsDataImpl : SchemaClass, CSteamAudioBakedDimensionsData
{
    public CSteamAudioBakedDimensionsDataImpl(nint handle) : base(handle) { }

    private static nint? _SettingsOffset;
    private SteamAudioCustomDataDimensionsSettings_tImpl? _SettingsInstance;

    public SteamAudioCustomDataDimensionsSettings_t Settings
    {
        get
        {
            _SettingsOffset = _SettingsOffset ?? Schema.GetOffset(0xB8BDCBF6B3DE33A8);
            var instance = _SettingsInstance ??= new SteamAudioCustomDataDimensionsSettings_tImpl(0);
            instance.DangerousSetHandle(_Handle + _SettingsOffset!.Value);
            return instance;
        }
    }
    private static nint? _ProbesOffset;
    private CSteamAudioProbeDataImpl? _ProbesInstance;

    public CSteamAudioProbeData Probes
    {
        get
        {
            _ProbesOffset = _ProbesOffset ?? Schema.GetOffset(0xB8BDCBF649D37E06);
            var instance = _ProbesInstance ??= new CSteamAudioProbeDataImpl(0);
            instance.DangerousSetHandle(_Handle + _ProbesOffset!.Value);
            return instance;
        }
    }
    private static nint? _InOutOffset;

    public ref CUtlVector<float> InOut
    {
        get
        {
            _InOutOffset = _InOutOffset ?? Schema.GetOffset(0xB8BDCBF6F387EE22);
            return ref _Handle.AsRef<CUtlVector<float>>(_InOutOffset!.Value);
        }
    }
    private static nint? _SizeOffset;

    public ref CUtlVector<float> Size
    {
        get
        {
            _SizeOffset = _SizeOffset ?? Schema.GetOffset(0xB8BDCBF6DABBAEBC);
            return ref _Handle.AsRef<CUtlVector<float>>(_SizeOffset!.Value);
        }
    }
    private static nint? _OutsideFieldOffset;

    public ref CUtlVector<CSteamAudioAmbisonicsField> OutsideField
    {
        get
        {
            _OutsideFieldOffset = _OutsideFieldOffset ?? Schema.GetOffset(0xB8BDCBF64CC1CB58);
            return ref _Handle.AsRef<CUtlVector<CSteamAudioAmbisonicsField>>(_OutsideFieldOffset!.Value);
        }
    }
    private static nint? _InsideSmallSizeFieldOffset;

    public ref CUtlVector<CSteamAudioAmbisonicsField> InsideSmallSizeField
    {
        get
        {
            _InsideSmallSizeFieldOffset = _InsideSmallSizeFieldOffset ?? Schema.GetOffset(0xB8BDCBF6BA49C7DF);
            return ref _Handle.AsRef<CUtlVector<CSteamAudioAmbisonicsField>>(_InsideSmallSizeFieldOffset!.Value);
        }
    }
    private static nint? _MovablesOffset;
    private SchemaUntypedField? _MovablesInstance;

    public SchemaUntypedField Movables
    {
        get
        {
            _MovablesOffset = _MovablesOffset ?? Schema.GetOffset(0xB8BDCBF6D92B2A8E);
            var instance = _MovablesInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _MovablesOffset!.Value);
            return instance;
        }
    }

}