// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSteamAudioBakedPathingDataImpl : SchemaClass, CSteamAudioBakedPathingData
{
    public CSteamAudioBakedPathingDataImpl(nint handle) : base(handle) { }

    private static nint? _BandsOffset;

    public ref int Bands
    {
        get
        {
            _BandsOffset = _BandsOffset ?? Schema.GetOffset(0x8B98B2B004C6EFF3);
            return ref _Handle.AsRef<int>(_BandsOffset!.Value);
        }
    }
    private static nint? _ProbesOffset;
    private CSteamAudioProbeDataImpl? _ProbesInstance;

    public CSteamAudioProbeData Probes
    {
        get
        {
            _ProbesOffset = _ProbesOffset ?? Schema.GetOffset(0x8B98B2B049D37E06);
            var instance = _ProbesInstance ??= new CSteamAudioProbeDataImpl(0);
            instance.DangerousSetHandle(_Handle + _ProbesOffset!.Value);
            return instance;
        }
    }
    private static nint? _MovablesOffset;
    private SchemaUntypedField? _MovablesInstance;

    public SchemaUntypedField Movables
    {
        get
        {
            _MovablesOffset = _MovablesOffset ?? Schema.GetOffset(0x8B98B2B0D92B2A8E);
            var instance = _MovablesInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _MovablesOffset!.Value);
            return instance;
        }
    }

}