// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSteamAudioBakedMaterialsDataImpl : SchemaClass, CSteamAudioBakedMaterialsData
{
    public CSteamAudioBakedMaterialsDataImpl(nint handle) : base(handle) { }

    private static nint? _ProbesOffset;
    private CSteamAudioProbeDataImpl? _ProbesInstance;

    public CSteamAudioProbeData Probes
    {
        get
        {
            _ProbesOffset = _ProbesOffset ?? Schema.GetOffset(0xDC9AF7EF49D37E06);
            var instance = _ProbesInstance ??= new CSteamAudioProbeDataImpl(0);
            instance.DangerousSetHandle(_Handle + _ProbesOffset!.Value);
            return instance;
        }
    }
    private static nint? _MaterialTokensOffset;

    public ref CUtlVector<uint> MaterialTokens
    {
        get
        {
            _MaterialTokensOffset = _MaterialTokensOffset ?? Schema.GetOffset(0xDC9AF7EF023FE732);
            return ref _Handle.AsRef<CUtlVector<uint>>(_MaterialTokensOffset!.Value);
        }
    }
    private static nint? _MaterialWeightsOffset;

    public ref CUtlVector<float> MaterialWeights
    {
        get
        {
            _MaterialWeightsOffset = _MaterialWeightsOffset ?? Schema.GetOffset(0xDC9AF7EF809822A9);
            return ref _Handle.AsRef<CUtlVector<float>>(_MaterialWeightsOffset!.Value);
        }
    }

}