// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSteamAudioAmbisonicsFieldImpl : SchemaClass, CSteamAudioAmbisonicsField
{
    public CSteamAudioAmbisonicsFieldImpl(nint handle) : base(handle) { }

    private static nint? _FieldOffset;

    public ref CUtlVector<float> Field
    {
        get
        {
            _FieldOffset = _FieldOffset ?? Schema.GetOffset(0x920A99EAA09F287);
            return ref _Handle.AsRef<CUtlVector<float>>(_FieldOffset!.Value);
        }
    }

}