// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CSubassetTypeInfoImpl : SchemaClass, CSubassetTypeInfo
{
    public CSubassetTypeInfoImpl(nint handle) : base(handle) { }

    private static nint? _FollowReferencesOffset;

    public ref bool FollowReferences
    {
        get
        {
            _FollowReferencesOffset = _FollowReferencesOffset ?? Schema.GetOffset(0x3F92DA146F6EB35A);
            return ref _Handle.AsRef<bool>(_FollowReferencesOffset!.Value);
        }
    }
    private static nint? _AllowDefinitionsOffset;

    public ref bool AllowDefinitions
    {
        get
        {
            _AllowDefinitionsOffset = _AllowDefinitionsOffset ?? Schema.GetOffset(0x3F92DA14C74D6030);
            return ref _Handle.AsRef<bool>(_AllowDefinitionsOffset!.Value);
        }
    }
    private static nint? _AllowReferencesOffset;

    public ref bool AllowReferences
    {
        get
        {
            _AllowReferencesOffset = _AllowReferencesOffset ?? Schema.GetOffset(0x3F92DA149BE87EDC);
            return ref _Handle.AsRef<bool>(_AllowReferencesOffset!.Value);
        }
    }

}