// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CTextureSheetDoc_FrameImpl : SchemaClass, CTextureSheetDoc_Frame
{
    public CTextureSheetDoc_FrameImpl(nint handle) : base(handle) { }

    private static nint? _ImageNameOffset;

    public string ImageName
    {
        get
        {
            _ImageNameOffset = _ImageNameOffset ?? Schema.GetOffset(0x764E70F034294EA4);
            return Schema.GetCUtlString(_Handle.Read<nint>(_ImageNameOffset!.Value));
        }
        set
        {
            _ImageNameOffset = _ImageNameOffset ?? Schema.GetOffset(0x764E70F034294EA4);
            Schema.SetCUtlString(_Handle, _ImageNameOffset!.Value, value);
        }
    }
    private static nint? _DisplayTimeOffset;

    public ref float DisplayTime
    {
        get
        {
            _DisplayTimeOffset = _DisplayTimeOffset ?? Schema.GetOffset(0x764E70F03D1A1D08);
            return ref _Handle.AsRef<float>(_DisplayTimeOffset!.Value);
        }
    }
    private static nint? _CropEnabledOffset;

    public ref bool CropEnabled
    {
        get
        {
            _CropEnabledOffset = _CropEnabledOffset ?? Schema.GetOffset(0x764E70F0F81160AC);
            return ref _Handle.AsRef<bool>(_CropEnabledOffset!.Value);
        }
    }
    private static nint? _SrcCropXStartOffset;

    public ref int SrcCropXStart
    {
        get
        {
            _SrcCropXStartOffset = _SrcCropXStartOffset ?? Schema.GetOffset(0x764E70F09B5F5983);
            return ref _Handle.AsRef<int>(_SrcCropXStartOffset!.Value);
        }
    }
    private static nint? _SrcCropYStartOffset;

    public ref int SrcCropYStart
    {
        get
        {
            _SrcCropYStartOffset = _SrcCropYStartOffset ?? Schema.GetOffset(0x764E70F0779DC66E);
            return ref _Handle.AsRef<int>(_SrcCropYStartOffset!.Value);
        }
    }
    private static nint? _SrcCropXEndOffset;

    public ref int SrcCropXEnd
    {
        get
        {
            _SrcCropXEndOffset = _SrcCropXEndOffset ?? Schema.GetOffset(0x764E70F0825EC076);
            return ref _Handle.AsRef<int>(_SrcCropXEndOffset!.Value);
        }
    }
    private static nint? _SrcCropYEndOffset;

    public ref int SrcCropYEnd
    {
        get
        {
            _SrcCropYEndOffset = _SrcCropYEndOffset ?? Schema.GetOffset(0x764E70F0D46EED7B);
            return ref _Handle.AsRef<int>(_SrcCropYEndOffset!.Value);
        }
    }

}