// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CToolsConfigImpl : SchemaClass, CToolsConfig
{
    public CToolsConfigImpl(nint handle) : base(handle) { }

    private static nint? _EngineToolsOffset;

    public ref CUtlVector<CEngineToolInfo> EngineTools
    {
        get
        {
            _EngineToolsOffset = _EngineToolsOffset ?? Schema.GetOffset(0xF03B672FC9DC7B32);
            return ref _Handle.AsRef<CUtlVector<CEngineToolInfo>>(_EngineToolsOffset!.Value);
        }
    }
    private static nint? _ExternalToolsOffset;

    public ref CUtlVector<CExternalToolInfo> ExternalTools
    {
        get
        {
            _ExternalToolsOffset = _ExternalToolsOffset ?? Schema.GetOffset(0xF03B672F8905AFF5);
            return ref _Handle.AsRef<CUtlVector<CExternalToolInfo>>(_ExternalToolsOffset!.Value);
        }
    }
    private static nint? _EngineModulesThatReferenceAssetsOffset;

    public ref CUtlVector<CUtlString> EngineModulesThatReferenceAssets
    {
        get
        {
            _EngineModulesThatReferenceAssetsOffset = _EngineModulesThatReferenceAssetsOffset ?? Schema.GetOffset(0xF03B672F329F14A7);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_EngineModulesThatReferenceAssetsOffset!.Value);
        }
    }

}