// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVibranceColorCorrectionLayerImpl : CColorCorrectionLayerImpl, CVibranceColorCorrectionLayer
{
    public CVibranceColorCorrectionLayerImpl(nint handle) : base(handle) { }

    private static nint? _VibranceOffset;

    public ref int Vibrance
    {
        get
        {
            _VibranceOffset = _VibranceOffset ?? Schema.GetOffset(0xB8E9FDD0555BA1AB);
            return ref _Handle.AsRef<int>(_VibranceOffset!.Value);
        }
    }
    private static nint? _SaturationOffset;

    public ref int Saturation
    {
        get
        {
            _SaturationOffset = _SaturationOffset ?? Schema.GetOffset(0xB8E9FDD05BA84D3D);
            return ref _Handle.AsRef<int>(_SaturationOffset!.Value);
        }
    }

}