// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class CVNodeTypeDescImpl : SchemaClass, CVNodeTypeDesc
{
    public CVNodeTypeDescImpl(nint handle) : base(handle) { }

    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xAF0908914D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xAF0908914D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _IconNameOffset;

    public string IconName
    {
        get
        {
            _IconNameOffset = _IconNameOffset ?? Schema.GetOffset(0xAF09089168CD8333);
            return Schema.GetCUtlString(_Handle.Read<nint>(_IconNameOffset!.Value));
        }
        set
        {
            _IconNameOffset = _IconNameOffset ?? Schema.GetOffset(0xAF09089168CD8333);
            Schema.SetCUtlString(_Handle, _IconNameOffset!.Value, value);
        }
    }
    private static nint? _PrefixOffset;

    public string Prefix
    {
        get
        {
            _PrefixOffset = _PrefixOffset ?? Schema.GetOffset(0xAF0908913EF59269);
            return Schema.GetCUtlString(_Handle.Read<nint>(_PrefixOffset!.Value));
        }
        set
        {
            _PrefixOffset = _PrefixOffset ?? Schema.GetOffset(0xAF0908913EF59269);
            Schema.SetCUtlString(_Handle, _PrefixOffset!.Value, value);
        }
    }
    private static nint? _InputNamesOffset;

    public ref CUtlVector<CUtlString> InputNames
    {
        get
        {
            _InputNamesOffset = _InputNamesOffset ?? Schema.GetOffset(0xAF09089176A053A9);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_InputNamesOffset!.Value);
        }
    }
    private static nint? _OutputNamesOffset;

    public ref CUtlVector<CUtlString> OutputNames
    {
        get
        {
            _OutputNamesOffset = _OutputNamesOffset ?? Schema.GetOffset(0xAF0908919A86A024);
            return ref _Handle.AsRef<CUtlVector<CUtlString>>(_OutputNamesOffset!.Value);
        }
    }
    private static nint? _InputTypeIdsOffset;

    public ref CUtlVector<int> InputTypeIds
    {
        get
        {
            _InputTypeIdsOffset = _InputTypeIdsOffset ?? Schema.GetOffset(0xAF09089187D74807);
            return ref _Handle.AsRef<CUtlVector<int>>(_InputTypeIdsOffset!.Value);
        }
    }
    private static nint? _OutputTypeIdsOffset;

    public ref CUtlVector<int> OutputTypeIds
    {
        get
        {
            _OutputTypeIdsOffset = _OutputTypeIdsOffset ?? Schema.GetOffset(0xAF0908913828B896);
            return ref _Handle.AsRef<CUtlVector<int>>(_OutputTypeIdsOffset!.Value);
        }
    }
    private static nint? _IsGroupOffset;

    public ref bool IsGroup
    {
        get
        {
            _IsGroupOffset = _IsGroupOffset ?? Schema.GetOffset(0xAF090891B68D3FDC);
            return ref _Handle.AsRef<bool>(_IsGroupOffset!.Value);
        }
    }
    private static nint? _AppliesToMainGraphOffset;

    public ref bool AppliesToMainGraph
    {
        get
        {
            _AppliesToMainGraphOffset = _AppliesToMainGraphOffset ?? Schema.GetOffset(0xAF090891DA89834D);
            return ref _Handle.AsRef<bool>(_AppliesToMainGraphOffset!.Value);
        }
    }
    private static nint? _AppliesToVoiceGraphOffset;

    public ref bool AppliesToVoiceGraph
    {
        get
        {
            _AppliesToVoiceGraphOffset = _AppliesToVoiceGraphOffset ?? Schema.GetOffset(0xAF090891E04068DC);
            return ref _Handle.AsRef<bool>(_AppliesToVoiceGraphOffset!.Value);
        }
    }
    private static nint? _IsAudioTrackOffset;

    public ref bool IsAudioTrack
    {
        get
        {
            _IsAudioTrackOffset = _IsAudioTrackOffset ?? Schema.GetOffset(0xAF0908910467CCE0);
            return ref _Handle.AsRef<bool>(_IsAudioTrackOffset!.Value);
        }
    }
    private static nint? _IsAudioOutputOffset;

    public ref bool IsAudioOutput
    {
        get
        {
            _IsAudioOutputOffset = _IsAudioOutputOffset ?? Schema.GetOffset(0xAF090891683460C0);
            return ref _Handle.AsRef<bool>(_IsAudioOutputOffset!.Value);
        }
    }
    private static nint? _IsControlInputOffset;

    public ref bool IsControlInput
    {
        get
        {
            _IsControlInputOffset = _IsControlInputOffset ?? Schema.GetOffset(0xAF090891A37BD2D2);
            return ref _Handle.AsRef<bool>(_IsControlInputOffset!.Value);
        }
    }
    private static nint? _IsControlOutputOffset;

    public ref bool IsControlOutput
    {
        get
        {
            _IsControlOutputOffset = _IsControlOutputOffset ?? Schema.GetOffset(0xAF090891A9E7BAC7);
            return ref _Handle.AsRef<bool>(_IsControlOutputOffset!.Value);
        }
    }
    private static nint? _IsSubgraphNodeOffset;

    public ref bool IsSubgraphNode
    {
        get
        {
            _IsSubgraphNodeOffset = _IsSubgraphNodeOffset ?? Schema.GetOffset(0xAF09089112D102A7);
            return ref _Handle.AsRef<bool>(_IsSubgraphNodeOffset!.Value);
        }
    }

}