// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class inv_image_map_tImpl : SchemaClass, inv_image_map_t
{
    public inv_image_map_tImpl(nint handle) : base(handle) { }

    private static nint? _Map_nameOffset;

    public string Map_name
    {
        get
        {
            _Map_nameOffset = _Map_nameOffset ?? Schema.GetOffset(0x3733F21C2BC80471);
            return Schema.GetCUtlString(_Handle.Read<nint>(_Map_nameOffset!.Value));
        }
        set
        {
            _Map_nameOffset = _Map_nameOffset ?? Schema.GetOffset(0x3733F21C2BC80471);
            Schema.SetCUtlString(_Handle, _Map_nameOffset!.Value, value);
        }
    }
    private static nint? _Map_rotationOffset;

    public ref float Map_rotation
    {
        get
        {
            _Map_rotationOffset = _Map_rotationOffset ?? Schema.GetOffset(0x3733F21CBEE35778);
            return ref _Handle.AsRef<float>(_Map_rotationOffset!.Value);
        }
    }

}