// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class locksound_tImpl : SchemaClass, locksound_t
{
    public locksound_tImpl(nint handle) : base(handle) { }

    private static nint? _LockedSoundOffset;

    public SchemaUntypedField LockedSound
    {
        get
        {
            _LockedSoundOffset = _LockedSoundOffset ?? Schema.GetOffset(0xDAD0AE229881D7AB);
            return new SchemaUntypedField(_Handle + _LockedSoundOffset!.Value);
        }
    }
    private static nint? _UnlockedSoundOffset;

    public SchemaUntypedField UnlockedSound
    {
        get
        {
            _UnlockedSoundOffset = _UnlockedSoundOffset ?? Schema.GetOffset(0xDAD0AE227EE88276);
            return new SchemaUntypedField(_Handle + _UnlockedSoundOffset!.Value);
        }
    }
    private static nint? _FlwaitSoundOffset;

    public GameTime_t FlwaitSound
    {
        get
        {
            _FlwaitSoundOffset = _FlwaitSoundOffset ?? Schema.GetOffset(0xDAD0AE2297A4A845);
            return new GameTime_tImpl(_Handle + _FlwaitSoundOffset!.Value);
        }
    }

}