// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class NmGraphDocPin_tImpl : SchemaClass, NmGraphDocPin_t
{
    public NmGraphDocPin_tImpl(nint handle) : base(handle) { }

    private static nint? _IDOffset;
    private SchemaUntypedField? _IDInstance;

    public SchemaUntypedField ID
    {
        get
        {
            _IDOffset = _IDOffset ?? Schema.GetOffset(0xA05A46B695066900);
            var instance = _IDInstance ??= new SchemaUntypedField(0);
            instance.DangerousSetHandle(_Handle + _IDOffset!.Value);
            return instance;
        }
    }
    private static nint? _NameOffset;

    public string Name
    {
        get
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xA05A46B64D8F5786);
            return Schema.GetCUtlString(_Handle.Read<nint>(_NameOffset!.Value));
        }
        set
        {
            _NameOffset = _NameOffset ?? Schema.GetOffset(0xA05A46B64D8F5786);
            Schema.SetCUtlString(_Handle, _NameOffset!.Value, value);
        }
    }
    private static nint? _TypeOffset;

    public ref NmGraphValueType_t Type
    {
        get
        {
            _TypeOffset = _TypeOffset ?? Schema.GetOffset(0xA05A46B60F04B4ED);
            return ref _Handle.AsRef<NmGraphValueType_t>(_TypeOffset!.Value);
        }
    }
    private static nint? _IsDynamicPinOffset;

    public ref bool IsDynamicPin
    {
        get
        {
            _IsDynamicPinOffset = _IsDynamicPinOffset ?? Schema.GetOffset(0xA05A46B61C247775);
            return ref _Handle.AsRef<bool>(_IsDynamicPinOffset!.Value);
        }
    }
    private static nint? _AllowMultipleOutConnectionsOffset;

    public ref bool AllowMultipleOutConnections
    {
        get
        {
            _AllowMultipleOutConnectionsOffset = _AllowMultipleOutConnectionsOffset ?? Schema.GetOffset(0xA05A46B6CF01AE0F);
            return ref _Handle.AsRef<bool>(_AllowMultipleOutConnectionsOffset!.Value);
        }
    }

}