// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class screenfade_tImpl : SchemaClass, screenfade_t
{
    public screenfade_tImpl(nint handle) : base(handle) { }

    private static nint? _SpeedOffset;

    public ref float Speed
    {
        get
        {
            _SpeedOffset = _SpeedOffset ?? Schema.GetOffset(0x613989A40A6B8020);
            return ref _Handle.AsRef<float>(_SpeedOffset!.Value);
        }
    }
    private static nint? _EndOffset;

    public ref float End
    {
        get
        {
            _EndOffset = _EndOffset ?? Schema.GetOffset(0x613989A4CF93764A);
            return ref _Handle.AsRef<float>(_EndOffset!.Value);
        }
    }
    private static nint? _ResetOffset;

    public ref float Reset
    {
        get
        {
            _ResetOffset = _ResetOffset ?? Schema.GetOffset(0x613989A40AC8A560);
            return ref _Handle.AsRef<float>(_ResetOffset!.Value);
        }
    }
    private static nint? _ColorOffset;

    public ref Color Color
    {
        get
        {
            _ColorOffset = _ColorOffset ?? Schema.GetOffset(0x613989A4D7D017D8);
            return ref _Handle.AsRef<Color>(_ColorOffset!.Value);
        }
    }
    private static nint? _FlagsOffset;

    public ref int Flags
    {
        get
        {
            _FlagsOffset = _FlagsOffset ?? Schema.GetOffset(0x613989A44222EBCC);
            return ref _Handle.AsRef<int>(_FlagsOffset!.Value);
        }
    }

}