// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class TexturesOptionsEditableData_tImpl : SchemaClass, TexturesOptionsEditableData_t
{
    public TexturesOptionsEditableData_tImpl(nint handle) : base(handle) { }

    private static nint? _DefaultMaterialNameOffset;

    public string DefaultMaterialName
    {
        get
        {
            _DefaultMaterialNameOffset = _DefaultMaterialNameOffset ?? Schema.GetOffset(0x2F343A4A268F7B28);
            return Schema.GetCUtlString(_Handle.Read<nint>(_DefaultMaterialNameOffset!.Value));
        }
        set
        {
            _DefaultMaterialNameOffset = _DefaultMaterialNameOffset ?? Schema.GetOffset(0x2F343A4A268F7B28);
            Schema.SetCUtlString(_Handle, _DefaultMaterialNameOffset!.Value, value);
        }
    }

}