// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class View2DOptionsEditableData_tImpl : SchemaClass, View2DOptionsEditableData_t
{
    public View2DOptionsEditableData_tImpl(nint handle) : base(handle) { }

    private static nint? _NudgeOffset;

    public ref bool Nudge
    {
        get
        {
            _NudgeOffset = _NudgeOffset ?? Schema.GetOffset(0x8F6FE90F9F1088B8);
            return ref _Handle.AsRef<bool>(_NudgeOffset!.Value);
        }
    }
    private static nint? _UsegroupcolorsOffset;

    public ref bool Usegroupcolors
    {
        get
        {
            _UsegroupcolorsOffset = _UsegroupcolorsOffset ?? Schema.GetOffset(0x8F6FE90F225A42FF);
            return ref _Handle.AsRef<bool>(_UsegroupcolorsOffset!.Value);
        }
    }
    private static nint? _GridIntensityOffset;

    public ref int GridIntensity
    {
        get
        {
            _GridIntensityOffset = _GridIntensityOffset ?? Schema.GetOffset(0x8F6FE90F42AE0495);
            return ref _Handle.AsRef<int>(_GridIntensityOffset!.Value);
        }
    }
    private static nint? _ShowEntityNamesOffset;

    public ref bool ShowEntityNames
    {
        get
        {
            _ShowEntityNamesOffset = _ShowEntityNamesOffset ?? Schema.GetOffset(0x8F6FE90F142BF375);
            return ref _Handle.AsRef<bool>(_ShowEntityNamesOffset!.Value);
        }
    }

}