// <auto-generated />
#pragma warning disable CS0108
#nullable enable

using System;
using System.Threading;
using SwiftlyS2.Core.Schemas;
using SwiftlyS2.Shared.Schemas;
using SwiftlyS2.Shared.Natives;
using SwiftlyS2.Core.Extensions;
using SwiftlyS2.Shared.SchemaDefinitions;

namespace SwiftlyS2.Core.SchemaDefinitions;

internal partial class VPhysEntityId_tImpl : SchemaClass, VPhysEntityId_t
{
    public VPhysEntityId_tImpl(nint handle) : base(handle) { }

    private static nint? _IdOffset;

    public ref uint Id
    {
        get
        {
            _IdOffset = _IdOffset ?? Schema.GetOffset(0x490269B0B5069B60);
            return ref _Handle.AsRef<uint>(_IdOffset!.Value);
        }
    }

}